## Installation

In [1]:
#!brew install poppler

In [ ]:
import os
os.environ["OPENAI_API_KEY"] = ""

In [ ]:
os.environ["ANTHROPIC_API_KEY"] =""

## Test Extractors

### Rubric Extractor

In [4]:
import fitz  # PyMuPDF

def extract_rubric(pdf_path):
    doc = fitz.open(pdf_path)
    text = ""

    for page in doc:
        text += page.get_text()

    return text.strip()

In [5]:
rubric = extract_rubric("../data/ExamQuestionAndRubric.pdf")

In [35]:
rubric

'Exam question \nCase study (3 points): In this exercise, your task is to apply the Bad Actors Modeling strategy to the \nSmartCity solution described in the scenario below: \n• \nChoose 3 different categories among the five in the Bad Actors Modeling strategy (money, \npolitics, entertainment, ideas, self-interest).  \n• \nThen for each of the categories you have chosen: identify and describe one harmful action a \nbad actor could take and how it could negatively impact stakeholders (1-2 sentences for \neach). Actions must be different from each other.  \nScenario: The Swiss company SmartCity wants to help local authorities to better manage city \ninfrastructures and resources by deploying a solution based on the Internet of Things (IoT) - a \nnetwork of objects with computing capabilities connected to the Internet through Wi-Fi or 5G. The \nsolution proposed by SmartCity uses a range of connected devices to monitor waste-bins, traffic flow \nas well as weather conditions throughout a city. Level monitoring sensors on waste-bins allow waste \ncollection services to optimize their routes. Cameras on major roads and intersections are connected \nto machine learning models to analyze real-time traffic data and dynamically adjust green light times. \nUsing real-time weather data, indoor ventilation and temperature are automatically adjusted to keep \nbuilding occupants comfortable while minimizing energy use. Weather data is also used in predictive \nanalytics to identify health risks and aggregated information is communicated to local communities in \na public app, for instance in case of air pollution or heatwave. Staff from the city authorities can \nmonitor and control the system remotely from a centralized dashboard. SmartCity plans to roll out its \nsolution in a number of European countries with large cities, including France, Germany, Italy and \nSpain.  \n \nGrading rubric \n1 point per bad actor action (total = 3 points) \n• \n0.5 the action described corresponds to the category (check the cheatsheet)  \n• \n0.5 the description makes clear how the action is harmful / negatively impacts stakeholders \nand is specific to SmartCity (i.e. adapted to the scenario)   \nPenalizations:  \n• \n-0.5 if two actions are too similar to each other  \n• \n-0.25 if negative impact is not sufficiently described'

'Exam question \nCase study (3 points): In this exercise, your task is to apply the Bad Actors Modeling strategy to the \nSmartCity solution described in the scenario below: \n• \nChoose 3 different categories among the five in the Bad Actors Modeling strategy (money, \npolitics, entertainment, ideas, self-interest).  \n• \nThen for each of the categories you have chosen: identify and describe one harmful action a \nbad actor could take and how it could negatively impact stakeholders (1-2 sentences for \neach). Actions must be different from each other.  \nScenario: The Swiss company SmartCity wants to help local authorities to better manage city \ninfrastructures and resources by deploying a solution based on the Internet of Things (IoT) - a \nnetwork of objects with computing capabilities connected to the Internet through Wi-Fi or 5G. The \nsolution proposed by SmartCity uses a range of connected devices to monitor waste-bins, traffic flow \nas well as weather conditions throughout a city. Level monitoring sensors on waste-bins allow waste \ncollection services to optimize their routes. Cameras on major roads and intersections are connected \nto machine learning models to analyze real-time traffic data and dynamically adjust green light times. \nUsing real-time weather data, indoor ventilation and temperature are automatically adjusted to keep \nbuilding occupants comfortable while minimizing energy use. Weather data is also used in predictive \nanalytics to identify health risks and aggregated information is communicated to local communities in \na public app, for instance in case of air pollution or heatwave. Staff from the city authorities can \nmonitor and control the system remotely from a centralized dashboard. SmartCity plans to roll out its \nsolution in a number of European countries with large cities, including France, Germany, Italy and \nSpain.  \n \nGrading rubric \n1 point per bad actor action (total = 3 points) \n• \n0.5 the action described corresponds to the category (check the cheatsheet)  \n• \n0.5 the description makes clear how the action is harmful / negatively impacts stakeholders \nand is specific to SmartCity (i.e. adapted to the scenario)   \nPenalizations:  \n• \n-0.5 if two actions are too similar to each other  \n• \n-0.25 if negative impact is not sufficiently described'

### Student Answer Extractor

In [13]:
import pytesseract
from pdf2image import convert_from_path

def extract_student_answers(paths):
    results = []

    for path in paths:
        pages = convert_from_path(path)
        text = ""

        for page in pages:
            text += pytesseract.image_to_string(page)

        results.append(text.strip())

    return results

In [6]:

from openai import OpenAI
import fitz
import base64
import json
import os

client = OpenAI()


def pdf_to_images(pdf_path, dpi=200):
    doc = fitz.open(pdf_path)
    images = []

    for page in doc:
        pix = page.get_pixmap(dpi=dpi)
        img_bytes = pix.tobytes("png")
        b64 = base64.b64encode(img_bytes).decode("utf-8")
        images.append(f"data:image/png;base64,{b64}")

    return images
def extract_student_transcription(pdf_paths, output_file="student_transcriptions.json"):
    results = []

    for path in pdf_paths:
        images = pdf_to_images(path)

        response = client.responses.create(
            model="gpt-4.1-mini",
            input=[{
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": """
You are a transcription system for handwritten exam answers.

IMPORTANT:
- Do NOT summarize
- Do NOT interpret
- Do NOT improve grammar
- Preserve structure
- Use [unclear] if needed

Return STRICT JSON:

{
  "transcription": "...",
  "uncertain_words": [],
  "confidence": 0-100
}
"""
                    },
                    *[
                        {
                            "type": "input_image",
                            "image_url": img,
                            "detail": "high"
                        }
                        for img in images
                    ]
                ]
            }]
        )

        raw_output = response.output_text

        try:
            parsed = json.loads(raw_output)
        except:
            parsed = {
                "transcription": raw_output,
                "uncertain_words": [],
                "confidence": 0
            }

        results.append({
            "file": path,
            "result": parsed
        })

    # 💾 SAVE TO FILE
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    return results

In [7]:
students = extract_student_transcription([
        "../data/StudentAnswer-Student1.pdf",
        "../data/StudentAnswer-Student2.pdf",
        "../data/StudentAnswer-Student3.pdf"
    ])

In [28]:
students

{'transcription': 'Money: A competitor of the company Smartcity can hack the centralized monitoring system, this would lead to a mess with the traffic and the bins. The company Smartcity would be negatively impacted in their reputation and this would lead to the loss of money by not signing contract with other European countries. The motivation for the competitor is the money they gain some part of the market.\nPolitics: A competitor of the current "maire (chef de la ville)" can disturb the sensors on waste-bins, the harm would be that citizens wouldn\'t be happy anymore with the council of the city because there would be bins everywhere due to the disruption of the sensors. The motivation for the competitor would be to be elected in the next elections.\nIdeas: A group of people pro-privacy can destroy/cover the cameras used to analyze the real-time traffic arguing that it is not in their ideology to be looked after by ML augmented cameras. The stakeholders harmed would be all the users of the road. They wouldn\'t have any information about traffic jams anymore. And the traffic light can malfunction due to the loss of information.',
 'uncertain_words': [],
 'confidence': 95}

#### OCR Extraction

In [24]:
students

['Politics Tictillig amen Cam Vee\n| [ws pero fe ihe ud ji bet\nom y . bt a a7\n\nbeg a have ey pad Pecan\nHe Robhas drm tube Hue vwheable\n\nWeld weticle - furor’, Lomeas , Hutter\nwae be soll Huon oe Oh a “a\ntrtibaiebuat Y Some bad deler aol\nHe wore ellecton ewer bY many ula\nde. Pauses for mahe Hw Wwarte~colle ae,\nLrteot Hu lallredors be He Come Lacobialen\n\nSeren [yes',
 '© Cateye “F Z vl ene?\n\naH lef 7 | waa te bo lA i a or even 14 ulingy iC\n\n6S iMce pl mig at 4 Bowe esol l eS ets Se vf\n\nOr it cen eucoy Tehe dre on authori fies te speek\noN lod “| ia me a\n\n‘ Catyer7 . Sel “interest | | .\n\nSome pepe might vse ot for dl puaformedon | sme\nnt can pobtly veh peed, . They could\niw he posped ea the wes cud ollow {he ao les |\nput could hetm Lee fj” Qoeng le 1 t fetsen\n\nAs tet eM\nwhe might hewve Ce oli kt Ly 2 bave Toe street\n\nent eu yt anil Freve le fi" yre Th We\nond Jem rere Wee being adj Ktedh mutters ie My wih\nagen dence on Thee weefler outside o¢ The enviunat\nthen otter | end This Cov lef presy bleed 4\nvagern ess bet eeu pee which coolh probe bly',
 'Homan > A compehte: of the Com ppans Smastkoity can hack te\nRo Rralfic amd the Dinds . he compana Gmarkety cree Qe megadaly\nde mec Now Codtacl wrk, thon Eunepoon cocahdoy . do\nmobioahion Jor Whe compote ds We moray Ahoy gan some pant\noh We manksh, |\n\nPolaticag A compat of te cumodt "maine (chop de Da ville) «\nCan dictunl Me rw wre - Pim, , the Daron coord fe\ntack CRy ow cxrullu\'t te Dappy Amore WEL Ae coumalh\nof the, coke, Decarro Phone wow Re Dim swenguathonrs due te\nHe dixnuprion of Bhe rmrors. The mottoahion pn the\nCompatitn would De He be shectid da We mack Qo chery -\n\nDPdeass A growp of people pne— privacy can dartreg /eoven the\nCamere wrod to analyze dhe roal-hine tnaffre ange dmg\nWhe IK dy mob Man Hhern ddookega te be Looked after\nMeg HL anganortad camanes, The thakelsldory Irarmod\nWowk be all We www of We now. Mag woellalt\nDove Ona Moforunat} gn obese trap pre fom OnnWmore .\nAud We tnappre DraDdt Can pra Quuction due ter Pre']

### Teaching Material Extractor

In [8]:
import fitz
import base64
import json
import os
from datetime import datetime
from openai import OpenAI

client = OpenAI()


# ----------------------------
# 1. Convert PDF → images
# ----------------------------
def pdf_to_base64_images(pdf_path: str):
    doc = fitz.open(pdf_path)
    images = []

    for i, page in enumerate(doc):
        pix = page.get_pixmap(dpi=200)
        img_bytes = pix.tobytes("png")
        base64_img = base64.b64encode(img_bytes).decode("utf-8")

        images.append({
            "type": "input_image",
            "image_url": f"data:image/png;base64,{base64_img}",
            "detail": "high"
        })

    return images


# ----------------------------
# 2. Extract structured content
# ----------------------------
def extract_teaching_material(pdf_path: str, save_output: bool = True):

    images = pdf_to_base64_images(pdf_path)

    response = client.responses.create(
        model="gpt-4.1-mini",
        input=[{
            "role": "user",
            "content": [
                {
                    "type": "input_text",
                    "text": """
You are extracting teaching material from a PDF.

IMPORTANT:
- Do NOT summarize.
- Extract EVERYTHING visible.
- Preserve structure exactly.
- Include diagram content (WENN diagrams, arrows, boxes).
- If text is in a figure, transcribe it.
- If relationships exist, describe them explicitly.

OUTPUT FORMAT (strict JSON):

{
  "key_concepts": [],
  "definitions": [],
  "diagram_explanations": [],
  "relationships": [],
  "raw_notes": []
}

Rules:
- Be exhaustive
- Do not omit small details
- Do not interpret beyond visible information
"""
                },
                *images
            ]
        }]
    )

    extracted_text = response.output_text

    # ----------------------------
    # 3. Save output for inspection
    # ----------------------------
    if save_output:
        os.makedirs("outputs", exist_ok=True)

        filename = f"outputs/teaching_material_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"

        try:
            parsed = json.loads(extracted_text)
        except Exception:
            parsed = {"raw_output": extracted_text}

        with open(filename, "w", encoding="utf-8") as f:
            json.dump(parsed, f, indent=2, ensure_ascii=False)

        print(f"[Saved] {filename}")

    return extracted_text

In [9]:
teaching = extract_teaching_material("../data/TeachingResource-BAD_ACTORS_STRATEGY.pdf")

[Saved] outputs/teaching_material_20260421_012425.json

In [5]:
teaching

'- **Fundamentals of the strategy**\n\n  - **Goal**:  \n    - Minimize vulnerabilities from the beginning of software design through risk assessment and mitigation.\n\n  - **When to use it**:  \n    - During the software design phase  \n    - Prior to any updates  \n    - During audits and inspections  \n    - As part of incident response  \n    - While improving the software\n\n- **What is a Bad actor?**\n\n  - Definition:  \n    - A "bad actor" or "threat actor" is a person or group that tries to exploit a system to achieve their own personal goals.\n\n  - Key points:  \n    - Multiple types of bad actors exist.  \n    - They are driven by different motivations.  \n    - Understanding and categorizing these motivations is essential for threat modeling.\n\n- **Assessment questions** (to guide risk analysis)\n\n  - Who would want to misuse the software or use it in an unintended way?  \n  - What would be the consequences of such misuse?  \n  - How could the negative consequences be prevented?\n\n- **Bad Actors Motivation Categories** (shown as overlapping sets in a Venn diagram)\n\n  - **Money**  \n    - Examples of bad actors: companies, hackers, scammers, competitors, criminal infrastructure providers, big game hunters  \n    - Threats include: data theft, ransomware, sabotage by competitors\n\n  - **Politics**  \n    - Examples of bad actors: nation state actors, political candidates, governmental intelligence agencies  \n    - Threats include: data disclosure, disinformation spreading, strategic sabotage, infrastructure attacks\n\n  - **Entertainment**  \n    - Examples of bad actors: trolls, thrill seekers  \n    - Threats include: looking up personal information such as celebrity medical records, browsing personal photos, random system attacks, misinformation spreading\n\n  - **Self-Interest**  \n    - Examples: revenge seekers, self-promoting persons, obsessive persons, insiders  \n    - Threats include: harassing messages, communication monitoring, location tracking, grade changing\n\n  - **Ideas**  \n    - Examples: extremists, religious persons, hacktivists, terrorists, conspiracy theorists  \n    - Threats include: spreading personal beliefs, discrediting other groups, DoS attacks, data leaks, website defacement\n\n- **Relationships & Overlaps**\n\n  - Motivation categories overlap and some malicious actions can fall into more than one category. For example, certain attacks may be politically motivated but also aimed at financial gain.\n\n  - The exact classification is less important than identifying a broad spectrum of potential scenarios that could threaten system security (to protect the system) and user safety (to protect people using the system).\n\n---\n\n### Summary\n\n- **Bad actors** exploit software systems driven by motivations such as money, politics, entertainment, self-interest, and ideas.  \n- Early risk assessment and mitigation reduce vulnerabilities to these threats.  \n- Understanding motivation categories helps frame assessment questions: Who, What, and How?  \n- Motivation categories overlap, highlighting complex threat landscapes.  \n- Goal: Enhance system security and user safety by anticipating possible threats.'

## Test pipeline

In [15]:
import json, hashlib, os

CACHE_FILE = "cache.json"


def cache_key(text):
    return hashlib.md5(text.encode()).hexdigest()


def load_cache():
    if not os.path.exists(CACHE_FILE):
        return {}
    with open(CACHE_FILE) as f:
        return json.load(f)


def save_cache(data):
    with open(CACHE_FILE, "w") as f:
        json.dump(data, f, indent=2)


def cached_call(key, fn):
    cache = load_cache()

    if key in cache:
        return cache[key]

    result = fn()
    cache[key] = result
    save_cache(cache)

    return result

In [16]:
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

In [17]:

import logging
from openai import AsyncOpenAI

async_client = AsyncOpenAI(api_key=OPENAI_API_KEY)
client = OpenAI(api_key=OPENAI_API_KEY)
logger = logging.getLogger(__name__)

In [22]:
import time


def normalize(text):
    return " ".join(text.split())


def call_llm(prompt, model, temperature=0.0, retries=3):

    key = cache_key(f"{model}:{temperature}:{normalize(prompt)}")

    def run():
        for i in range(retries):
            try:
                res = client.responses.create(
                    model=model,
                    input=prompt,
                    temperature=temperature
                )
                return getattr(res, "output_text", "")
            except Exception as e:
                logger.warning(f"Retry {i+1}: {e}")
                time.sleep(1.5 * (i+1))

        raise RuntimeError("LLM failed after retries")

    return cached_call(key, run)

In [19]:
import json
import re


def extract_json(text):
    match = re.search(r"\{.*\}", text, re.DOTALL)

    if not match:
        raise ValueError(f"Invalid JSON output: {text[:200]}")

    try:
        return json.loads(match.group())
    except Exception as e:
        raise ValueError(f"JSON parse error: {e} | Raw: {text[:200]}")

### Parse Rubric

In [184]:
import re

def parse_rubric(rubric_text):

    # split sections
    case_section = re.search(
        r"Case study.*?Grading rubric.*?(?=Penalizations:|$)",
        rubric_text,
        re.DOTALL
    )

    penalty_section = re.search(
        r"Penalizations:(.*)",
        rubric_text,
        re.DOTALL
    )

    # -----------------------
    # TASK + SCENARIO
    # -----------------------
    task_block = case_section.group(0) if case_section else rubric_text

    instructions = []
    scenario_lines = []

    for line in task_block.split("\n"):
        l = line.strip()

        if not l:
            continue

        if "choose" in l.lower() or "apply" in l.lower():
            instructions.append(l)
        elif "scenario" in l.lower() or "smartcity" in l.lower():
            scenario_lines.append(l)

    # -----------------------
    # SCORING RULES
    # -----------------------
    per_action_rules = [
        {
            "name": "category_match",
            "weight": 0.5,
            "rule": "action corresponds to category"
        },
        {
            "name": "harm_description",
            "weight": 0.5,
            "rule": "clear harmful impact + specificity to SmartCity"
        }
    ]

    # -----------------------
    # PENALTIES
    # -----------------------
    penalties = []

    if penalty_section:
        for line in penalty_section.group(1).split("\n"):
            l = line.strip()
            if "-0.5" in l:
                penalties.append({
                    "name": "similar_actions",
                    "value": -0.5,
                    "rule": l
                })
            elif "-0.25" in l:
                penalties.append({
                    "name": "weak_impact",
                    "value": -0.25,
                    "rule": l
                })

    return {
        "task": {
            "name": "Case study",
            "total_points": 3,
            "instructions": instructions,
            "scenario": "\n".join(scenario_lines)
        },
        "scoring": {
            "per_action": per_action_rules,
            "penalties": penalties
        }
    }

In [185]:
# 1. STRUCTURE
rubric_structured = parse_rubric(rubric)

In [186]:
rubric_structured

{'task': {'name': 'Case study',
  'total_points': 3,
  'instructions': ['Case study (3 points): In this exercise, your task is to apply the Bad Actors Modeling strategy to the',
   'Choose 3 different categories among the five in the Bad Actors Modeling strategy (money,'],
  'scenario': 'SmartCity solution described in the scenario below:\nScenario: The Swiss company SmartCity wants to help local authorities to better manage city\nsolution proposed by SmartCity uses a range of connected devices to monitor waste-bins, traffic flow\nmonitor and control the system remotely from a centralized dashboard. SmartCity plans to roll out its\nand is specific to SmartCity (i.e. adapted to the scenario)'},
 'scoring': {'per_action': [{'name': 'category_match',
    'weight': 0.5,
    'rule': 'action corresponds to category'},
   {'name': 'harm_description',
    'weight': 0.5,
    'rule': 'clear harmful impact + specificity to SmartCity'}],
  'penalties': [{'name': 'similar_actions',
    'value': -0.5,
    'rule': '-0.5 if two actions are too similar to each other'},
   {'name': 'weak_impact',
    'value': -0.25,
    'rule': '-0.25 if negative impact is not sufficiently described'}]}}

#### Analyze Rubric

In [23]:
MODEL_GRADING = "gpt-4.1"
MODEL_EXTRACTION = "gpt-4.1-mini"
MODEL_ANALYSIS = "gpt-4.1"

In [24]:


def analyze_rubric(rubric, teaching_material):
    prompt = f"""
You are an expert in exam design.

Your task is to evaluate how well the rubric aligns with the teaching material.

RUBRIC:
{rubric}

TEACHING MATERIAL:
{teaching_material}

IMPORTANT:
- Focus on alignment with teaching
- Identify missing concepts
- Identify unclear grading rules
- Do NOT invent new criteria

Evaluate it on:

1. Ambiguity → Is the rubric formulated with the objective, unambiguous criteria?
2. Applicability → Does the rubric cover the diversity of possible student responses?
3. Discrimination → Does the rubric clearly separate excellent from poor work?

Return STRICT JSON:

{{
  "ambiguity_issues": ["..."],
  "applicability_issues": ["..."],
  "discrimination_issues": ["..."],
  "alignment_issues": ["..."]
}}
"""
    output = call_llm(prompt, model= MODEL_ANALYSIS, temperature=0.4)
    return extract_json(output)

In [25]:
rubric_analysis = analyze_rubric(rubric, teaching)

In [26]:
rubric_analysis

{'ambiguity_issues': ["The rubric refers to 'the cheatsheet' for checking if an action corresponds to a category, but does not specify what constitutes sufficient alignment—this may be unclear to students or graders.",
  "The phrase 'actions must be different from each other' is not precisely defined; it is ambiguous how much overlap is allowed between actions.",
  "The penalty '-0.5 if two actions are too similar to each other' is subjective and does not define what 'too similar' means.",
  "The penalty '-0.25 if negative impact is not sufficiently described' does not specify what level of detail or specificity is required for sufficiency."],
 'applicability_issues': ['The rubric assumes students will choose three categories, but does not address how to grade if a student chooses fewer or more than three.',
  'There is no explicit guidance on how to handle partially correct answers, such as when an action fits a category but the negative impact is generic or only partially related to the scenario.',
  'The rubric does not account for responses that may fit multiple categories due to overlapping motivations, as described in the teaching material.'],
 'discrimination_issues': ["The rubric awards points in 0.5 increments, but does not provide clear examples or thresholds for what constitutes a 'good' versus 'excellent' answer versus a 'poor' one.",
  'There is no distinction between a minimal, generic response and a detailed, scenario-specific response beyond the 0.5 point for specificity, which may not sufficiently reward depth or insight.'],
 'alignment_issues': ["The rubric does not explicitly require students to consider the assessment questions from the teaching material (e.g., 'Who would like to use my software maliciously? What would be the consequences?'), which are central to the Bad Actors Modeling strategy.",
  'The rubric does not prompt students to consider or discuss the overlapping nature of motivation categories, which is highlighted in the teaching material.',
  "The rubric does not emphasize the importance of linking actions to specific stakeholders, as described in the teaching material's focus on both system and user threats.",
  'The rubric does not require or encourage students to consider risk assessment or mitigation, which are stated goals of the strategy in the teaching material.']}

### Generate Synthetic Answers

In [27]:



def generate_synthetic_answers(teaching, rubric):
    """
    Generates calibration dataset:
    - good answers
    - bad answers
    - edge cases
    """

    prompt = f"""
You are generating synthetic student answers for rubric evaluation.

TEACHING MATERIAL:
{teaching}

RUBRIC:
{rubric}

Generate:

1. 4 HIGH-QUALITY answers (full understanding)
2. 4 LOW-QUALITY answers (misunderstanding / missing parts)
3. 3 EDGE CASE answers (partially correct but ambiguous)

Return STRICT JSON:

{{
  "good": ["..."],
  "bad": ["..."],
  "edge": ["..."]
}}
"""

    return extract_json(call_llm(prompt, MODEL_ANALYSIS, 0.4))

In [28]:
synthetic = generate_synthetic_answers(teaching, rubric)

In [29]:
synthetic

{'good': ['1. Money: A hacker could deploy ransomware on the SmartCity IoT network, locking city officials out of waste-bin monitoring and traffic control systems until a ransom is paid. This would disrupt essential city services, causing delays in waste collection and traffic congestion, negatively affecting residents and city operations.\n2. Politics: A nation-state actor could manipulate the traffic data to create artificial congestion during a major political event, making it difficult for attendees and emergency services to reach the area. This could undermine public trust in local authorities and disrupt civic activities.\n3. Self-Interest: An insider working for the city could alter weather sensor data to falsely indicate extreme heat, triggering unnecessary ventilation and cooling in public buildings. This would waste city resources and increase operational costs, impacting taxpayers.',
  '1. Ideas: Hacktivists could deface the public app that shares aggregated weather and pollution data, spreading misinformation about health risks. This could cause panic or mistrust among citizens, leading to unnecessary worry or disregard for real warnings.\n2. Money: Criminals could steal and sell traffic camera footage to insurance scammers or competitors, violating privacy and potentially leading to fraudulent claims.\n3. Entertainment: Thrill-seekers might remotely tamper with traffic light timings for fun, causing unexpected traffic jams and increasing the risk of accidents, endangering public safety.',
  '1. Entertainment: Trolls could gain access to the waste-bin sensors and send false alerts about overflowing bins in random neighborhoods, causing unnecessary dispatches and confusion for waste management staff.\n2. Politics: Political activists might manipulate pollution data in the public app to exaggerate air quality issues during an election, undermining the credibility of local authorities.\n3. Money: Competitors could sabotage the SmartCity system by introducing malware, causing system downtime and financial losses for the company and the cities relying on the service.',
  "1. Self-Interest: An employee with access to the centralized dashboard could monitor the movements of a specific individual by tracking their location data from traffic cameras, violating privacy rights and potentially enabling stalking.\n2. Money: Cybercriminals could intercept and sell real-time weather and traffic data to unauthorized third parties, breaching data protection laws and putting citizens' information at risk.\n3. Ideas: Extremist groups might use the system to spread propaganda by injecting false alerts into the public app, causing confusion and fear among city residents."],
 'bad': ['1. Money: Someone could hack the system to make money. This would be bad for the city.\n2. Politics: A person could use the system for political reasons. This could hurt people.\n3. Entertainment: Someone might play a prank on the system. This could be annoying.',
  '1. Ideas: Hackers could use the SmartCity system to spread their ideas. This might cause trouble.\n2. Money: A bad actor could steal money from the system, which is harmful.\n3. Self-Interest: Someone could use the system for their own benefit, which is unfair.',
  '1. Entertainment: A bad actor could use SmartCity to have fun. This could be bad for the city.\n2. Politics: Someone could change something for political reasons. This might cause issues.\n3. Money: A person could try to get money from the city using the system.',
  '1. Self-Interest: An employee could use the system for themselves. This is not good for the city.\n2. Ideas: Someone could spread ideas using SmartCity. This could be harmful.\n3. Entertainment: A person could use the system to entertain themselves, which is not allowed.'],
 'edge': ["1. Money: A competitor could try to access SmartCity's data to gain an advantage in the market. This could make SmartCity lose business, but it's not clear how they would do it.\n2. Politics: Someone might try to influence local elections by using SmartCity's public app, but the exact method is not specified.\n3. Entertainment: A person could try to mess with the traffic lights for fun, but the impact on stakeholders is not fully explained.",
  "1. Self-Interest: An insider could use the system to track a person they know, which could be harmful if discovered, but the consequences are not detailed.\n2. Ideas: A group could post messages in the public app about pollution that aren't true, causing some confusion among users.\n3. Money: Hackers could try to make money from the system, but it's not clear what method they would use or who would be affected.",
  "1. Politics: A foreign group could use SmartCity data to embarrass local authorities, though the specific harm isn't described.\n2. Entertainment: Someone could try to trigger false waste-bin alerts just to see what happens, possibly wasting resources.\n3. Ideas: Activists might use the app to promote their cause, but the negative impact on stakeholders is vague."]}

In [30]:
synthetic_good = synthetic["good"]
synthetic_bad = synthetic["bad"]

In [31]:
synthetic_edge = synthetic["edge"]

In [34]:
!pip install anthropic

Collecting anthropic
  Downloading anthropic-0.96.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from anthropic) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from anthropic) (1.9.0)
Collecting docstring-parser<1,>=0.15 (from anthropic)
  Downloading docstring_parser-0.18.0-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: httpx<1,>=0.25.0 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from anthropic) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from anthropic) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from anthropic) (2.13.2)
Requirement already satisfied: sniffio in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from anthropic) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from anthropic) (4.15.0)
Requirement already satisfied: idna>=2.8 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from anyio<5,>=3.5.0->anthropic) (3.11)
Requirement already satisfied: certifi in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from httpx<1,>=0.25.0->anthropic) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from httpx<1,>=0.25.0->anthropic) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.25.0->anthropic) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->anthropic) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.2 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->anthropic) (2.46.2)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->anthropic) (0.4.2)
Downloading anthropic-0.96.0-py3-none-any.whl (635 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 635.9/635.9 kB 7.0 MB/s  0:00:00
Downloading docstring_parser-0.18.0-py3-none-any.whl (22 kB)
Installing collected packages: docstring-parser, anthropic
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [anthropic]/2 [anthropic]
Successfully installed anthropic-0.96.0 docstring-parser-0.18.0

In [46]:


import asyncio
from openai import AsyncOpenAI
from anthropic import AsyncAnthropic
#from app.utils.json_utils import extract_json
#from app.config import OPENAI_API_KEY, ANTHROPIC_API_KEY

openai_client = AsyncOpenAI(api_key=OPENAI_API_KEY)
claude_client = AsyncAnthropic(api_key=ANTHROPIC_API_KEY)


def build_prompt(rubric, answer):
    return f"""
Strict grader.

RUBRIC:
{rubric}

ANSWER:
{answer}

Return STRICT JSON:

{{
  "criteria_scores": [
    {{
      "criterion": "string",
      "max_score": number,
      "score": number,
      "reason": "string",
      "is_ambiguous": true
    }}
  ],
  "final_grade": number,
  "overall_reason": "string"
}}
"""


async def grade_answer_openai_async(rubric, answer):
    prompt = build_prompt(rubric, answer)

    res = await openai_client.responses.create(
        model="gpt-4.1",
        input=prompt,
        temperature=0.0
    )
    try:
        return extract_json(res.output_text)
    except Exception as e:
        return {
            "criteria_scores": [],
            "final_grade": 0,
            "overall_reason": "Parsing failed",
            "error": str(e),
            "raw_output": res.output_text
        }


async def grade_answer_claude_async(rubric, answer):
    prompt = build_prompt(rubric, answer)

    res = await claude_client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=1000,
        messages=[{"role": "user", "content": prompt}]
    )

    try:
        return extract_json(res.content[0].text)
    except Exception as e:
        return {
            "criteria_scores": [],
            "final_grade": 0,
            "overall_reason": "Parsing failed",
            "error": str(e),
            "raw_output": res.content[0].text
        }


async def grade_student(rubric, answer):
    o, c = await asyncio.gather(
        grade_answer_openai_async(rubric, answer),
        grade_answer_claude_async(rubric, answer)
    )

    return {"openai": o, "claude": c}

### Simulate Grading Async

In [47]:
import asyncio
#from app.grading.grader_async import grade_student


async def simulate_grading_async(rubric, students, runs=3):
    all_runs = []

    for _ in range(runs):
        tasks = [grade_student(rubric, s) for s in students]
        results = await asyncio.gather(*tasks)
        all_runs.append(results)

    return all_runs


async def simulate_all(rubric, students, synthetic):
    return await asyncio.gather(
        simulate_grading_async(rubric, students),
        simulate_grading_async(rubric, synthetic["good"]),
        simulate_grading_async(rubric, synthetic["bad"]),
        simulate_grading_async(rubric, synthetic["edge"])
    )


def build_rater_runs(grading_runs_multi):
    """
    Converts:
    runs x students x models

    → raters x students

    Each (run, model) = one rater for ICC
    """
    runs = []

    for run in grading_runs_multi:
        runs.append([r["openai"] for r in run])
        runs.append([r["claude"] for r in run])

    return runs

In [48]:
grading_runs_multi, good_runs_multi, bad_runs_multi, edge_runs_multi = await simulate_all(
    rubric, students, synthetic
)

/opt/homebrew/Cellar/python@3.12/3.12.11/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py:984: RuntimeWarning: coroutine 'simulate_all' was never awaited
  exceptions.append(my_exceptions)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

In [49]:
grading_runs_multi

[[{'openai': {'criteria_scores': [{'criterion': 'Politics',
      'max_score': 1,
      'score': 1,
      'reason': "The action (intelligence agencies using the system to gather information) fits the 'politics' category and the negative impact (loss of privacy and security for countries and their populations) is clearly described and specific to the SmartCity scenario.",
      'is_ambiguous': False},
     {'criterion': 'Money',
      'max_score': 1,
      'score': 1,
      'reason': "The action (robbers stealing valuable installed materials) fits the 'money' category and the negative impact (financial cost to reinstall materials) is clearly described and specific to the scenario.",
      'is_ambiguous': False},
     {'criterion': 'Entertainment',
      'max_score': 1,
      'score': 1,
      'reason': "The action (trolling waste collection services by manipulating sensors) fits the 'entertainment' category and the negative impact (waste collection services being misdirected repeatedly) is clearly described and specific to the SmartCity scenario.",
      'is_ambiguous': False}],
    'final_grade': 3,
    'overall_reason': 'All three actions are clearly linked to different categories, are distinct from each other, and the negative impacts are sufficiently described and specific to the SmartCity scenario. No penalizations apply.'},
   'claude': {'criteria_scores': [{'criterion': 'Politics Category - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Intelligence agencies using surveillance tools for information gathering is a valid political bad actor scenario.',
      'is_ambiguous': False},
     {'criterion': 'Politics Category - Harmful impact description',
      'max_score': 0.5,
      'score': 0.25,
      'reason': "The answer states privacy and security loss but lacks specificity to SmartCity's infrastructure. Does not clearly explain HOW the IoT network (waste bins, cameras, weather sensors) enables this surveillance or which specific stakeholders are impacted.",
      'is_ambiguous': False},
     {'criterion': 'Money Category - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Physical theft of valuable hardware for financial gain is a valid money-motivated bad actor scenario.',
      'is_ambiguous': False},
     {'criterion': 'Money Category - Harmful impact description',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Clearly explains the harmful impact: reinstallation costs to city authorities and service disruption. Specific to SmartCity's connected devices.",
      'is_ambiguous': False},
     {'criterion': 'Entertainment Category - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Trolling and malicious manipulation for amusement is a valid entertainment/self-amusement motivated bad actor scenario.',
      'is_ambiguous': False},
     {'criterion': 'Entertainment Category - Harmful impact description',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Clearly describes the negative impact: waste collection services are redirected inefficiently, wasting time, fuel, and resources. Specific to the waste-bin sensor component.',
      'is_ambiguous': False},
     {'criterion': 'Action Distinctiveness',
      'max_score': 0,
      'score': -0.5,
      'reason': 'Politics and Money actions are too similar: both involve exploitation of the SmartCity infrastructure by bad actors for resource extraction (information vs. physical materials). Both describe theft/unauthorized access of system assets.',
      'is_ambiguous': False},
     {'criterion': 'Overall Specificity to Scenario',
      'max_score': 0,
      'score': 0,
      'reason': 'Politics action lacks detailed explanation of how IoT devices specifically enable surveillance or how the multi-country rollout amplifies this risk.',
      'is_ambiguous': False}],
    'final_grade': 2.25,
    'overall_reason': "Student correctly identified 3 categories with valid bad actor scenarios. Money and Entertainment categories are well-described with clear, specific harmful impacts (1 point each). Politics category shows conceptual understanding but lacks specificity to SmartCity's infrastructure (0.75 points). A 0.5-point penalty applied for similarity between Politics and Money actions—both frame bad actors exploiting SmartCity assets for personal gain without sufficient differentiation. The Politics action also needed clearer explanation of HOW the connected devices enable surveillance and which stakeholders are affected."}},
  {'openai': {'criteria_scores': [{'criterion': 'Money - Action corresponds to category and negative impact is specific to SmartCity',
      'max_score': 1,
      'score': 0.5,
      'reason': "The answer discusses high costs and local authorities spending a lot of money, which fits the 'money' category. However, it does not clearly describe a bad actor's harmful action (e.g., price gouging, bribery, or financial fraud) but rather a general risk or consequence. The negative impact is somewhat described but lacks specificity about a bad actor's role.",
      'is_ambiguous': True},
     {'criterion': 'Self-interest - Action corresponds to category and negative impact is specific to SmartCity',
      'max_score': 1,
      'score': 0.5,
      'reason': "The answer mentions disinformation and people being harmed by false information, which fits 'self-interest' if the bad actor is manipulating data for personal gain. However, the example is vague and not clearly tied to a specific bad actor's action (e.g., a city employee falsifying data to avoid blame). The negative impact is described but not very specific to the SmartCity context.",
      'is_ambiguous': True},
     {'criterion': 'Ideas - Action corresponds to category and negative impact is specific to SmartCity',
      'max_score': 1,
      'score': 0.5,
      'reason': "The answer discusses disagreement over automated temperature/ventilation settings, which relates to 'ideas' (conflicting values or beliefs). However, it does not clearly describe a bad actor's action (e.g., someone manipulating settings to push a particular ideology or agenda). The negative impact (unfairness, discomfort) is described but not strongly linked to a deliberate harmful action.",
      'is_ambiguous': True}],
    'final_grade': 1.5,
    'overall_reason': "The student attempted to address three different categories and provided some negative impacts, but in all cases, the harmful actions were not clearly described as deliberate actions by bad actors. The answers are vague, lack specificity, and do not fully meet the rubric's requirement for clear, scenario-adapted bad actor actions. Each response earns partial credit for category relevance and some negative impact description, but none are fully correct."},
   'claude': {'criteria_scores': [],
    'final_grade': 0,
    'overall_reason': 'Parsing failed',
    'error': 'JSON parse error: Expecting \',\' delimiter: line 51 column 6 (char 3254) | Raw: ```json\n{\n  "criteria_scores": [\n    {\n      "criterion": "Category 1 (Money): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The answer mentions high c',
    'raw_output': '```json\n{\n  "criteria_scores": [\n    {\n      "criterion": "Category 1 (Money): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The answer mentions high costs but does not clearly describe a BAD ACTOR\'s harmful action. It vaguely states \'it might encourage local authorities to spend a lot of money\' without identifying a specific malicious actor or intentional harmful behavior. This reads as a general concern rather than a bad actor scenario.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 1 (Money): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The negative impact is poorly articulated and not specific to SmartCity\'s scenario. No clear stakeholder harm is described, and it fails to explain how a bad actor would exploit the financial aspect to cause damage.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 2 (Self-interest): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.3,\n      "reason": "The answer attempts to describe misuse of the camera/traffic system but conflates \'disinformation\' with false traffic violations. Self-interest typically involves personal gain; this description is unclear about the bad actor\'s motivation or benefit. The scenario is confused and poorly articulated.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 2 (Self-interest): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.35,\n      "reason": "The example about a red light violation is confusing and poorly explained. While it attempts to show harm to innocent citizens, the mechanism is vague and doesn\'t clearly demonstrate how SmartCity\'s specific IoT system could be exploited for self-interest. The connection between the bad actor and their benefit is missing.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 3 (Ideas): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.4,\n      "reason": "The answer identifies ideological disagreement about automated temperature/ventilation control, which somewhat relates to the \'ideas\' category. However, the distinction between disagreement and a bad actor deliberately exploiting this system is not clear. This reads more as a design flaw than a bad actor\'s action.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 3 (Ideas): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.35,\n      "reason": "The negative impact (discomfort and unfairness) is mentioned but not specific to SmartCity or how a bad actor would deliberately cause harm. The answer describes a potential usability problem rather than demonstrating how someone with bad intentions could exploit the system for ideological purposes.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Action differentiation (penalty check)",\n      "max_score": 0,\n      "score": -0.5,\n      "reason": "Categories 1 and 2 are too similar—both describe general misuse/costs of the system without clearly distinct harmful actions. Both lack specificity about the bad actor\'s distinct method of harm.",\n      "is_ambiguous": false\n    }\n  ],\n  "final_grade": 1.0,\n  "overall_reason": "This answer demonstrates significant weaknesses across all three required bad actor scenarios. None of the three actions are clearly described as intentional harmful acts by bad actors with specific motivations. The Money category conflates cost concerns with bad actor behavior. The Self-interest category is confusingly written with an unclear mechanism for exploitation. The Ideas category describes disagreement rather than bad actor exploitation. Additionally, the Money and Self-interest actions are too similar in their vagueness about the harmful mechanism, triggering a -0.5 penalty. Each criterion barely achieves partial credit due to lack of specificity, scenario adaptation, and clarity. A passing response would require: (1) clearly identified bad actors with explicit motivations, (2) specific'}},
  {'openai': {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The action (competitor hacks system for financial gain) fits the 'money' category.",
      'is_ambiguous': False},
     {'criterion': 'Money - Negative impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The answer clearly describes how hacking would harm SmartCity's reputation and finances, and is specific to the scenario.",
      'is_ambiguous': False},
     {'criterion': 'Politics - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The action (political rival disrupts sensors to undermine current mayor) fits the 'politics' category.",
      'is_ambiguous': False},
     {'criterion': 'Politics - Negative impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The answer explains how disruption would lead to public dissatisfaction and is specific to SmartCity's waste-bin sensors.",
      'is_ambiguous': False},
     {'criterion': 'Ideas - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The action (privacy activists destroy/cover cameras) fits the 'ideas' category.",
      'is_ambiguous': False},
     {'criterion': 'Ideas - Negative impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.25,
      'reason': 'The answer mentions loss of traffic information and malfunctioning lights, but the negative impact on stakeholders is not fully developed (e.g., safety risks, increased congestion).',
      'is_ambiguous': False},
     {'criterion': 'Actions are sufficiently different',
      'max_score': 0,
      'score': 0,
      'reason': 'All three actions are distinct and correspond to different categories.',
      'is_ambiguous': False}],
    'final_grade': 2.75,
    'overall_reason': "The student correctly identified three distinct bad actor actions, each corresponding to a different category (money, politics, ideas), and described scenario-specific negative impacts. However, the negative impact for the 'ideas' category was not fully developed, resulting in a minor deduction."},
   'claude': {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Hacking to gain market share and financial advantage clearly fits the 'money' category.",
      'is_ambiguous': False},
     {'criterion': 'Money - Harm description is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The answer clearly describes how hacking causes reputational damage, loss of contracts, and financial loss to SmartCity. Specific to the scenario.',
      'is_ambiguous': False},
     {'criterion': 'Politics - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Disrupting sensors to manipulate elections and gain political power clearly fits the 'politics' category.",
      'is_ambiguous': False},
     {'criterion': 'Politics - Harm description is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The answer explains how sensor disruption leads to overflowing bins, citizen dissatisfaction with the current council, and electoral advantage for the competitor. Specific to SmartCity's waste management system.",
      'is_ambiguous': False},
     {'criterion': 'Ideas - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Privacy ideology-driven destruction of cameras clearly fits the 'ideas' category as it's motivated by ideological principles rather than financial or political gain.",
      'is_ambiguous': False},
     {'criterion': 'Ideas - Harm description is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The answer describes concrete harms: loss of traffic information for road users and traffic light malfunction. Properly adapted to SmartCity's traffic management system.",
      'is_ambiguous': False},
     {'criterion': 'Action differentiation - No excessive similarity',
      'max_score': 0,
      'score': 0,
      'reason': 'The three actions target different systems (centralized control system, waste sensors, traffic cameras) with different motivations (money, politics, ideas). No penalization needed.',
      'is_ambiguous': False},
     {'criterion': 'Negative impact sufficiency',
      'max_score': 0,
      'score': 0,
      'reason': 'All three negative impacts are sufficiently described with clear stakeholder effects. No penalization needed.',
      'is_ambiguous': False}],
    'final_grade': 3.0,
    'overall_reason': 'Excellent response. The student selected three distinct categories (Money, Politics, Ideas) and provided well-developed bad actor scenarios for each. All actions clearly map to their respective categories, and the harmful impacts are specific to the SmartCity scenario with concrete examples of stakeholder damage. The three actions target different system components and are sufficiently differentiated. No penalizations apply. Full marks awarded.'}}],
 [{'openai': {'criteria_scores': [{'criterion': 'Politics - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The action describes intelligence agencies using the system for surveillance, which fits the politics category.',
      'is_ambiguous': False},
     {'criterion': 'Politics - Negative impact is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The answer explains that privacy and security of countries and their populations would be compromised, which is specific to the SmartCity scenario.',
      'is_ambiguous': False},
     {'criterion': 'Money - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Describes theft of valuable IoT equipment for resale, which is a money-motivated action.',
      'is_ambiguous': False},
     {'criterion': 'Money - Negative impact is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'States that theft would result in financial loss due to the need to reinstall equipment, which is specific to the scenario.',
      'is_ambiguous': False},
     {'criterion': 'Entertainment - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Describes trolling (pranking) waste collection services, which fits the entertainment category.',
      'is_ambiguous': False},
     {'criterion': 'Entertainment - Negative impact is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Explains that manipulation would cause waste collectors to be redirected unnecessarily, which is a clear and scenario-specific negative impact.',
      'is_ambiguous': False}],
    'final_grade': 3,
    'overall_reason': 'All three actions are clearly distinct, correspond to the chosen categories, and the negative impacts are specific to the SmartCity scenario and well described. No penalizations apply.'},
   'claude': {'criteria_scores': [{'criterion': 'Politics Category - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Intelligence agencies conducting surveillance is appropriately categorized under Politics (power and control). The category match is correct.',
      'is_ambiguous': False},
     {'criterion': 'Politics Category - Harmful impact description',
      'max_score': 0.5,
      'score': 0.3,
      'reason': "The impact is vaguely stated ('no longer have privacy and security'). The answer lacks specificity about HOW SmartCity's IoT infrastructure enables this or WHICH stakeholders are affected. The connection to SmartCity's specific components (cameras, sensors, traffic monitoring) is not made explicit.",
      'is_ambiguous': False},
     {'criterion': 'Money Category - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Physical theft for financial gain is correctly categorized under Money. The category match is appropriate.',
      'is_ambiguous': False},
     {'criterion': 'Money Category - Harmful impact description',
      'max_score': 0.5,
      'score': 0.5,

In [50]:
good_runs_multi

[[{'openai': {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Deploying ransomware for financial gain is a classic 'money' bad actor motivation.",
      'is_ambiguous': False},
     {'criterion': 'Money - Negative impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The answer clearly explains how ransomware would disrupt waste collection and traffic, harming residents and city operations.',
      'is_ambiguous': False},
     {'criterion': 'Politics - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Manipulating traffic data to influence a political event is a clear example of a politically motivated attack.',
      'is_ambiguous': False},
     {'criterion': 'Politics - Negative impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The answer specifies disruption of civic activities and loss of public trust, directly tied to the SmartCity scenario.',
      'is_ambiguous': False},
     {'criterion': 'Self-Interest - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "An insider manipulating data for personal reasons fits the 'self-interest' category.",
      'is_ambiguous': False},
     {'criterion': 'Self-Interest - Negative impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The answer explains how this would waste resources and increase costs, which is specific to the SmartCity system.',
      'is_ambiguous': False}],
    'final_grade': 3.0,
    'overall_reason': 'All three actions are clearly distinct, correspond to the chosen categories, and the negative impacts are well described and specific to the SmartCity scenario. No penalizations apply.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Money) - Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Ransomware attack clearly corresponds to money/financial motivation category.',
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Money) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Clearly describes negative impact (service disruption, waste delays, traffic congestion) with specific reference to SmartCity systems.',
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics) - Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Data manipulation during political event directly corresponds to politics category.',
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Explicitly describes harm (congestion, impaired emergency services, erosion of public trust) adapted to the traffic monitoring component of SmartCity.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Self-Interest) - Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Insider actor altering data for personal benefit clearly matches self-interest category.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Self-Interest) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Well-articulated harm (resource waste, increased costs, taxpayer impact) specifically tied to weather sensor manipulation in SmartCity's ventilation/cooling systems.",
      'is_ambiguous': False},
     {'criterion': 'Action Distinctiveness',
      'max_score': 0,
      'score': 0,
      'reason': 'All three actions are sufficiently different (ransomware attack vs. data manipulation vs. sensor falsification). No penalization applied.',
      'is_ambiguous': False}],
    'final_grade': 3.0,
    'overall_reason': 'Excellent response. All three bad actor actions are properly categorized, clearly described, and specifically adapted to the SmartCity scenario. Each action distinctly targets different system components (network security, traffic data, weather sensors) with well-articulated negative impacts on stakeholders. The answer demonstrates strong understanding of the Bad Actors Modeling strategy with no deductions warranted.'}},
  {'openai': {'criteria_scores': [{'criterion': 'Ideas',
      'max_score': 1,
      'score': 1,
      'reason': "The action (hacktivists spreading misinformation via the public app) fits the 'ideas' category and is specific to the SmartCity scenario. The negative impact (panic or mistrust among citizens, disregard for real warnings) is clearly described.",
      'is_ambiguous': False},
     {'criterion': 'Money',
      'max_score': 1,
      'score': 1,
      'reason': "The action (criminals stealing and selling traffic camera footage) fits the 'money' category and is specific to SmartCity. The negative impact (privacy violation, fraudulent claims) is clearly described.",
      'is_ambiguous': False},
     {'criterion': 'Entertainment',
      'max_score': 1,
      'score': 1,
      'reason': "The action (thrill-seekers tampering with traffic lights for fun) fits the 'entertainment' category and is specific to SmartCity. The negative impact (traffic jams, increased accident risk, endangering public safety) is clearly described.",
      'is_ambiguous': False}],
    'final_grade': 3,
    'overall_reason': 'All three actions are clearly distinct, correspond to the chosen categories, and are well-adapted to the SmartCity scenario. The negative impacts are specific and sufficiently described. No penalizations apply.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Ideas): Category Alignment',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Defacing the public app and spreading misinformation clearly aligns with the 'Ideas' category, which concerns manipulation of information and narratives.",
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Ideas): Harmful Impact & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The response clearly explains how the misinformation causes panic, mistrust, and citizen confusion regarding health warnings. The example is appropriately tailored to SmartCity's public app function.",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Money): Category Alignment',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Stealing and selling footage for profit directly aligns with the 'Money' category, which focuses on financial gain through illegal means.",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Money): Harmful Impact & Specificity',
      'max_score': 0.5,
      'score': 0.25,
      'reason': 'While the action is mentioned, the harmful impact description is underdeveloped. The response lists potential harms (privacy violation, fraudulent claims) but does not sufficiently explain the mechanism or depth of negative impact on specific SmartCity stakeholders (e.g., citizens whose movements are tracked, city authorities facing liability, etc.).',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Entertainment): Category Alignment',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Tampering with traffic lights 'for fun' aligns well with the 'Entertainment' category, which covers actors seeking amusement or thrill without other primary motives.",
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Entertainment): Harmful Impact & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The response clearly describes concrete harms: traffic jams and increased accident risk. The impact is well-specified to SmartCity's traffic management system and directly affects public safety.",
      'is_ambiguous': False},
     {'criterion': 'Distinctiveness Between Actions',
      'max_score': 0,
      'score': -0.5,
      'reason': 'Actions 1 and 2 share problematic overlap: both involve digital manipulation/interference (defacing the app vs. stealing data), and both cause harm through information abuse or data compromise. While technically in different categories, the execution methods and stakeholder impacts are too similar, warranting the similarity penalty.',
      'is_ambiguous': False}],
    'final_grade': 2.25,
    'overall_reason': "The response demonstrates understanding of the Bad Actors Modeling strategy and selects three distinct categories appropriately. All three actions are scenario-specific and relate to SmartCity's IoT infrastructure. However, two issues reduce the score: (1) Action 2's harmful impact is insufficiently detailed, earning only 0.25 points instead of 0.5 for clarity and depth; (2) Actions 1 and 2 are too similar in nature (both digital interference/data abuse), triggering a 0.5-point penalty. The response achieves 2.25 out of 3 points total."}},
  {'openai': {'criteria_scores': [{'criterion': 'Entertainment',
      'max_score': 1,
      'score': 1,
      'reason': 'The action (trolls sending false alerts about overflowing bins) fits the entertainment category and is specific to the SmartCity scenario. The negative impact (unnecessary dispatches and confusion for waste management staff) is clearly described.',
      'is_ambiguous': False},
     {'criterion': 'Politics',
      'max_score': 1,
      'score': 1,
      'reason': 'The action (political activists manipulating pollution data to exaggerate air quality issues during an election) fits the politics category and is specific to the scenario. The negative impact (undermining the credibility of local authorities) is clearly described.',
      'is_ambiguous': False},
     {'criterion': 'Money',
      'max_score': 1,
      'score': 1,
      'reason': 'The action (competitors introducing malware to cause system downtime and financial losses) fits the money category and is specific to SmartCity. The negative impact (financial losses for the company and cities) is clearly described.',
      'is_ambiguous': False}],
    'final_grade': 3,
    'overall_reason': 'All three actions are clearly linked to different categories, are specific to the SmartCity scenario, and the negative impacts are well described. No actions are too similar, and all impacts are sufficiently explained.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Entertainment) - Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Entertainment category correctly identified. Trolling behavior fits the entertainment/mischief motivation in Bad Actors Modeling.',
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Entertainment) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Clear negative impact described: false alerts cause unnecessary waste collection dispatches and confusion for staff. Specific to SmartCity's waste-bin monitoring system.",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics) - Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Politics category correctly identified. Data manipulation for electoral advantage clearly falls under political motivation.',
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Harm is clearly described: exaggerated pollution data undermines authority credibility and manipulates public perception. Specific to the public app feature of SmartCity.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Money) - Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Money category correctly identified. Competitor sabotage for financial gain is a valid money-motivated bad actor scenario.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Money) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.25,
      'reason': "Harm description lacks sufficient specificity to SmartCity. 'Sabotage by introducing malware' is generic and could apply to any IoT/tech company. The answer does not clearly explain concrete impacts on specific stakeholders (e.g., citizens unable to access traffic optimization, waste collection failures affecting neighborhoods, health alerts unavailable during emergencies).",
      'is_ambiguous': False},
     {'criterion': 'Similarity Check',
      'max_score': 0,
      'score': -0.5,
      'reason': 'Actions 1 and 3 are problematically similar: both describe system disruption through unauthorized access/malware introduction to cause operational failures. Entertainment trolling (false bin alerts) and Money sabotage (malware) both result in degraded system functionality for the same stakeholder (city authorities/services). This violates the requirement for actions to be different from each other.',
      'is_ambiguous': False}],
    'final_grade': 2.25,
    'overall_reason': 'The answer demonstrates solid understanding of Bad Actors Modeling with appropriate category selection and mostly clear harm descriptions. Entertainment and Politics actions are well-articulated and sufficiently different. However, two critical issues reduce the score: (1) Action 3 lacks scenario-specific detail about how malware sabotage harms SmartCity stakeholders, describing harm too generically; (2) Actions 1 and 3 are too similar in their operational impact (system disruption through unauthorized access), warranting the -0.5 similarity penalty. Score: 3.0 (full points) - 0.5 (similarity penalty) - 0.25 (insufficient specificity on Action 3) = 2.25/3.0'}},
  {'openai': {'criteria_scores': [{'criterion': 'Self-Interest',
      'max_score': 1,
      'score': 1,
      'reason': 'The action (employee tracking an individual via dashboard) fits the self-interest category and is specific to the SmartCity scenario. The negative impact (privacy violation, potential stalking) is clearly described.',
      'is_ambiguous': False},
     {'criterion': 'Money',
      'max_score': 1,
      'score': 1,
      'reason': "The action (cybercriminals selling real-time data) fits the money category and is relevant to the scenario. The negative impact (data breach, risk to citizens' information) is sufficiently described.",
      'is_ambiguous': False},
     {'criterion': 'Ideas',
      'max_score': 1,
      'score': 1,
      'reason': 'The action (injecting false alerts to spread propaganda) fits the ideas category and is specific to the SmartCity public app. The negative impact (confusion and fear among residents) is clearly explained.',
      'is_ambiguous': False}],
    'final_grade': 3,
    'overall_reason': 'All three actions are clearly linked to different Bad Actors Modeling categories, are distinct from each other, and the negative impacts are specific and well described in the context of the SmartCity scenario.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Self-Interest) - Category Correspondence',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Self-interest as a category involves personal gain, advantage, or benefit at others' expense. An employee exploiting system access for personal surveillance clearly falls under self-interested motives.",
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Self-Interest) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The response clearly describes how the harmful action (tracking individuals via traffic cameras) negatively impacts stakeholders (privacy violation, stalking risk) and is appropriately specific to SmartCity's camera infrastructure.",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Money) - Category Correspondence',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Money as a category concerns financial gain and economic exploitation. Selling data for profit directly corresponds to monetary motivations.',
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Money) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The response adequately describes the harmful outcome (data breach, unauthorized access, privacy risks) and ties it to SmartCity's specific data collection systems (weather and traffic data).",
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Ideas) - Category Correspondence',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Ideas as a category involves ideological manipulation and influence. Using the system to spread propaganda clearly aligns with manipulating information and pushing ideological agendas.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Ideas) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.25,
      'reason': "While the response identifies a harmful action (false alerts via public app), the harm description is somewhat generic. The impact 'causing confusion and fear' lacks specificity about how this damages stakeholders or infrastructure in the SmartCity context. More concrete consequences would strengthen this (e.g., causing public panic affecting emergency response systems, undermining trust in official health alerts).",
      'is_ambiguous': False},
     {'criterion': 'Penalization - Action Similarity',
      'max_score': 0,
      'score': -0.5,
      'reason': 'Actions 1 and 2 share a concerning similarity: both involve unauthorized access to system data (employee accessing dashboard for tracking; cybercriminals intercepting data). They represent variations of the same core malicious behavior pattern (data exploitation through system compromise), triggering the -0.5 penalization.',
      'is_ambiguous': False}],
    'final_grade': 2.25,
    'overall_reason': "The response demonstrates good understanding of the Bad Actors Modeling strategy with appropriate category selection. All three actions correspond correctly to their assigned categories, and Actions 1 and 2 have strong, specific harm descriptions tied to SmartCity's infrastructure. However, Action 3's harm description lacks sufficient detail and specificity, losing 0.25 points. The critical issue is that Actions 1 and 2 are too similar—both essentially describe unauthorized data access and exploitation through system compromise—triggering a -0.5 penalization. The candidate should have selected more distinct categories or developed fundamentally different attack vectors to fully maximize the score."}}],
 [{'openai': {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Deploying ransomware for financial gain is a clear 'money' motivation.",
      'is_ambiguous': False},
     {'criterion': 'Money - Harmful impact is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The answer clearly describes disruption to waste collection and traffic, with negative effects on residents and city operations.',
      'is_ambiguous': False},
     {'criterion': 'Politics - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Manipulating traffic data to influence a political event is a clear 'politics' motivation.",
      'is_ambiguous': False},
     {'criterion': 'Politics - Harmful impact is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The answer specifies disruption of civic activities and loss of public trust, which are relevant and specific to the scenario.',
      'is_ambiguous': False},
     {'criterion': 'Self-Interest - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "An insider acting for personal benefit (e.g., to avoid work or benefit from increased contracts) fits 'self-interest.'",
      'is_ambiguous': False},

In [51]:
bad_runs_multi

[[{'openai': {'criteria_scores': [{'criterion': 'Money',
      'max_score': 1,
      'score': 0.5,
      'reason': "The answer identifies hacking for money, which fits the 'money' category, but the harmful impact is vague ('bad for the city') and not specific to the SmartCity scenario.",
      'is_ambiguous': False},
     {'criterion': 'Politics',
      'max_score': 1,
      'score': 0.5,
      'reason': "The answer mentions using the system for political reasons, which fits the 'politics' category, but the negative impact is not described in a specific or detailed way ('could hurt people') and is not clearly linked to the SmartCity context.",
      'is_ambiguous': False},
     {'criterion': 'Entertainment',
      'max_score': 1,
      'score': 0.5,
      'reason': "The answer identifies playing a prank, which fits the 'entertainment' category, but the negative impact is only described as 'annoying' and lacks detail or specificity to the SmartCity scenario.",
      'is_ambiguous': False}],
    'final_grade': 1.5,
    'overall_reason': 'All three actions correspond to the correct categories, but in each case the negative impact is not sufficiently described or specific to the SmartCity scenario. The answers are too vague and do not demonstrate a clear understanding of how these actions would harm stakeholders in this context.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Money) - Category Correspondence',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Hacking for financial gain is a valid money-motivated bad actor action.',
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Money) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.1,
      'reason': "The description is extremely vague ('would be bad for the city'). It fails to specify HOW the hacking causes harm, WHICH stakeholders are affected, or what the CONCRETE negative impacts are in the SmartCity context (e.g., ransom demands, data theft, infrastructure disruption, financial losses to waste collection or traffic systems).",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics) - Category Correspondence',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Political manipulation is a valid politics-motivated bad actor action.',
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.1,
      'reason': "The description is severely lacking in specificity. 'Use the system for political reasons' and 'could hurt people' provides no concrete example. Missing: What specific political abuse? How would they manipulate traffic lights, health warnings, or waste data? Which stakeholders suffer? (e.g., suppress air pollution warnings in opposition districts, manipulate health data, bias traffic systems).",
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Entertainment) - Category Correspondence',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'A prank fits the entertainment category as a motivation for mischievous behavior.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Entertainment) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.15,
      'reason': "Description is insufficient and downplays severity. 'Could be annoying' trivializes the impact. No specific SmartCity context provided (e.g., tampering with traffic light timing could cause accidents/injuries, false health warnings create panic, disrupting waste collection causes sanitation problems). Lacks detail on stakeholder harm.",
      'is_ambiguous': False},
     {'criterion': 'Similarity Penalty',
      'max_score': 0,
      'score': -0.5,
      'reason': 'Actions 1 and 2 are too similar—both describe system manipulation/hacking without distinguishing the specific mechanism or harm. The answer lacks differentiation in the types of attacks or impacts.',
      'is_ambiguous': False}],
    'final_grade': 1.25,
    'overall_reason': "This response demonstrates critical weaknesses across all three bad actor actions. While the categories are correctly identified (0.5 points earned per category), the descriptions of harmful impacts are dangerously vague, non-specific to the SmartCity scenario, and fail to articulate concrete stakeholder harms as required by the rubric. The answer lacks technical detail (how are systems compromised?), scenario adaptation (what SmartCity components are targeted?), and stakeholder impact analysis (who suffers and why?). Additionally, actions 1 and 2 lack sufficient differentiation, triggering a -0.5 penalty. The entertainment example is particularly weak, minimizing potential harm as merely 'annoying.' A strict grader will penalize the absence of scenario-specific, detailed, and well-differentiated harmful actions."}},
  {'openai': {'criteria_scores': [{'criterion': 'Ideas',
      'max_score': 1,
      'score': 0.5,
      'reason': "The answer identifies that hackers could use the system to spread their ideas, which fits the category. However, the harmful impact is vague ('might cause trouble') and not specific to the SmartCity scenario.",
      'is_ambiguous': True},
     {'criterion': 'Money',
      'max_score': 1,
      'score': 0.5,
      'reason': 'The answer states that a bad actor could steal money from the system, which fits the category. However, it does not specify how this would occur in the context of SmartCity or how stakeholders are negatively impacted.',
      'is_ambiguous': True},
     {'criterion': 'Self-Interest',
      'max_score': 1,
      'score': 0.5,
      'reason': 'The answer says someone could use the system for their own benefit, which fits the category. However, it is not specific about what action is taken or how it harms stakeholders in the SmartCity context.',
      'is_ambiguous': True}],
    'final_grade': 1.5,
    'overall_reason': 'All three actions are too vague and lack specific adaptation to the SmartCity scenario. The negative impacts are not sufficiently described, resulting in a loss of 0.25 points per answer. The actions are not too similar, so no penalty there. Each answer earns 0.5/1.'},
   'claude': {'criteria_scores': [],
    'final_grade': 0,
    'overall_reason': 'Parsing failed',
    'error': 'JSON parse error: Expecting \',\' delimiter: line 58 column 6 (char 3148) | Raw: ```json\n{\n  "criteria_scores": [\n    {\n      "criterion": "Action 1 (Ideas): Category correspondence",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The answer vaguely mentions \'hacker',
    'raw_output': '```json\n{\n  "criteria_scores": [\n    {\n      "criterion": "Action 1 (Ideas): Category correspondence",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The answer vaguely mentions \'hackers spreading ideas\' but does not clearly explain how this corresponds to the \'Ideas\' category in Bad Actors Modeling. The connection is weak and underdeveloped.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Action 1 (Ideas): Harm description and specificity",\n      "max_score": 0.5,\n      "score": 0.1,\n      "reason": "The harm is stated as \'might cause trouble\' - this is extremely vague and not specific to the SmartCity scenario. No concrete negative impact on stakeholders is described. The answer fails to explain how spreading ideas through the IoT system would harm city authorities, residents, or other stakeholders.",\n      "is_ambiguous": false\n    },\n    {\n      "criterion": "Action 2 (Money): Category correspondence",\n      "max_score": 0.5,\n      "score": 0.5,\n      "reason": "The Money category is correctly identified. Financial theft/fraud is appropriate for this category.",\n      "is_ambiguous": false\n    },\n    {\n      "criterion": "Action 2 (Money): Harm description and specificity",\n      "max_score": 0.5,\n      "score": 0.1,\n      "reason": "The harm is stated as \'stealing money from the system, which is harmful\' - this is circular reasoning and completely lacks specificity to the SmartCity scenario. No explanation of what \'stealing money\' means in context (billing fraud? contract manipulation?) or how it affects stakeholders (city budget, residents\' utility costs, service quality).",\n      "is_ambiguous": false\n    },\n    {\n      "criterion": "Action 3 (Self-Interest): Category correspondence",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "Self-interest is mentioned but the action itself (\'using the system for their own benefit\') is too generic and could apply to almost any bad actor category. The specificity to this category is weak.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Action 3 (Self-Interest): Harm description and specificity",\n      "max_score": 0.5,\n      "score": 0.1,\n      "reason": "The harm is stated as \'which is unfair\' - this is non-specific and does not adequately describe how stakeholders are negatively impacted. No concrete example is provided (e.g., manipulating traffic lights, prioritizing certain areas, selling personal data).",\n      "is_ambiguous": false\n    },\n    {\n      "criterion": "Action similarity penalization",\n      "max_score": 0,\n      "score": -0.5,\n      "reason": "Actions 1, 2, and 3 are all extremely vague and generic. They could apply to nearly any IoT system without scenario-specific adaptation, making them functionally similar in their lack of substantive differentiation.",\n      "is_ambiguous": false\n    },\n    {\n      "criterion": "Overall description quality",\n      "max_score": 0,\n      "score": -0.25,\n      "reason": "Multiple negative impacts lack sufficient description. Each action needs more detailed explanation of harm mechanisms and stakeholder impact.",\n      "is_ambiguous": false\n    }\n  ],\n  "final_grade": 0.35,\n  "overall_reason": "This answer demonstrates fundamental misunderstanding of the Bad Actors Modeling exercise. All three actions are vague, generic, and lack scenario-specific adaptation to the SmartCity IoT system described. The negative impacts are stated superficially without concrete explanation of how stakeholders (city authorities, residents, waste services, traffic users, etc.) would be harmed. The actions fail to show creativity or critical thinking about actual vulnerabilities in the described system (traffic light manipulation, sensor tampering, data interception, etc.). The answer reads like placeholder responses rather than substantive analysis. Multiple penalizations apply for insufficient harm description and'}},
  {'openai': {'criteria_scores': [{'criterion': 'Entertainment',
      'max_score': 1,
      'score': 0,
      'reason': 'The action is too vague and not specific to the SmartCity scenario. It does not clearly describe a harmful action or its negative impact on stakeholders.',
      'is_ambiguous': True},
     {'criterion': 'Politics',
      'max_score': 1,
      'score': 0.25,
      'reason': 'The answer mentions changing something for political reasons, which loosely fits the category, but it is not specific to the SmartCity system and does not clearly describe the negative impact. The description is too generic.',
      'is_ambiguous': True},
     {'criterion': 'Money',
      'max_score': 1,
      'score': 0.25,
      'reason': 'The answer mentions trying to get money from the city, which fits the category, but it is not specific about how this would be done using SmartCity, nor does it clearly describe the negative impact on stakeholders.',
      'is_ambiguous': True}],
    'final_grade': 0.5,
    'overall_reason': 'The answers are vague, lack specificity to the SmartCity scenario, and do not clearly describe distinct harmful actions or their negative impacts. None of the actions are well-adapted to the scenario, and the negative impacts are not sufficiently described.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Entertainment): Category alignment',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Entertainment is a valid category from the Bad Actors Modeling strategy.',
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Entertainment): Harm description and specificity',
      'max_score': 0.5,
      'score': 0,
      'reason': "The answer 'A bad actor could use SmartCity to have fun. This could be bad for the city' is extremely vague and fails to describe any concrete harmful action specific to the SmartCity scenario. No specific mechanism, device, or data is identified. The negative impact is not explained.",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics): Category alignment',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Politics is a valid category from the Bad Actors Modeling strategy.',
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics): Harm description and specificity',
      'max_score': 0.5,
      'score': 0,
      'reason': "The answer 'Someone could change something for political reasons. This might cause issues' completely lacks specificity. No concrete harmful action is described, no stakeholders are identified, and no connection to SmartCity systems is made. The description is too abstract to demonstrate understanding of the scenario.",
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Money): Category alignment',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Money is a valid category from the Bad Actors Modeling strategy.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Money): Harm description and specificity',
      'max_score': 0.5,
      'score': 0,
      'reason': "The answer 'A person could try to get money from the city using the system' is entirely non-specific. No mechanism is described, no SmartCity component is identified, and no concrete harm to stakeholders is articulated. This reads as a generic placeholder rather than a thoughtful analysis.",
      'is_ambiguous': False},
     {'criterion': 'Similarity penalty',
      'max_score': 0,
      'score': 0,
      'reason': 'No penalization applied; while the answers are vague, they address different categories as required.',
      'is_ambiguous': False}],
    'final_grade': 1.5,
    'overall_reason': 'The response demonstrates a critical failure in execution. While the student correctly identified three valid categories from the Bad Actors Modeling strategy (earning 1.5 points on category alignment), the harm descriptions are severely deficient. All three actions lack concrete specificity, fail to connect to the SmartCity scenario details (IoT devices, sensors, cameras, ML models, dashboards, weather data, traffic systems, etc.), and do not clearly articulate negative impacts on specific stakeholders. The answers read as placeholder statements rather than thoughtful analysis. A strict grader would expect detailed, scenario-specific examples such as: a bad actor manipulating traffic light algorithms to disrupt specific neighborhoods, bribing city staff to modify waste collection routes for personal gain, or selling sensitive location/traffic data illegally. The response earns no points for harm description across all three actions (-1.5 points) due to insufficient specificity and detail.'}},
  {'openai': {'criteria_scores': [{'criterion': 'Self-Interest',
      'max_score': 1,
      'score': 0.5,
      'reason': "The action is vaguely described ('use the system for themselves') and does not specify what the employee does or how it harms stakeholders. The negative impact is not sufficiently described or specific to SmartCity.",
      'is_ambiguous': True},
     {'criterion': 'Ideas',
      'max_score': 1,
      'score': 0.5,
      'reason': "The action ('spread ideas using SmartCity') is too vague and does not specify what kind of ideas or how this would be done using the system. The negative impact is not sufficiently described or specific to the scenario.",
      'is_ambiguous': True},
     {'criterion': 'Entertainment',
      'max_score': 1,
      'score': 0,
      'reason': "The action ('use the system to entertain themselves') is not clearly related to the Entertainment category as defined in the Bad Actors Modeling strategy (which typically involves causing disruption for fun or attention). The negative impact is not described at all.",
      'is_ambiguous': True}],
    'final_grade': 1,
    'overall_reason': 'The answers are vague, lack specificity, and do not clearly describe distinct, harmful actions or their negative impacts in the context of SmartCity. Only the first two partially correspond to the categories, but both lack sufficient detail and adaptation to the scenario. The third does not meet the requirements for the Entertainment category.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Self-Interest): Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Self-interest is correctly identified as a valid Bad Actors Modeling category.',
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Self-Interest): Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.1,
      'reason': "The description 'An employee could use the system for themselves' is vague and non-specific. It lacks concrete detail about what action the employee would take (e.g., accessing traffic data for personal route optimization, selling sensor data, manipulating waste collection routes for personal benefit). The harm to stakeholders is not clearly articulated. Minimal adaptation to the SmartCity scenario.",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Ideas): Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Ideas is correctly identified as a valid Bad Actors Modeling category.',
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Ideas): Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.0,
      'reason': "The description 'Someone could spread ideas using SmartCity. This could be harmful' is extremely vague and generic. It does not explain what harmful ideas could be spread, through which specific SmartCity component (camera feeds, public app, dashboard?), or how stakeholders would be negatively impacted. No concrete example tied to the scenario. Does not meet minimum requirements.",
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Entertainment): Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Entertainment is correctly identified as a valid Bad Actors Modeling category.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Entertainment): Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.1,
      'reason': "The description 'A person could use the system to entertain themselves' is vague and lacks specificity. No concrete example of how the system could be misused for entertainment (e.g., watching camera feeds for voyeurism, manipulating traffic lights as a game). Harm to stakeholders is not described. Minimal connection to SmartCity scenario.",
      'is_ambiguous': False},
     {'criterion': 'Similarity Penalization',
      'max_score': 0,
      'score': -0.5,
      'reason': 'Actions 1 and 3 are too similar—both describe general personal misuse of the system without specific harmful behaviors. Both lack concrete examples and have similarly vague descriptions.',
      'is_ambiguous': False}],
    'final_grade': 1.2,

In [52]:
edge_runs_multi

[[{'openai': {'criteria_scores': [{'criterion': 'Money',
      'max_score': 1,
      'score': 0.5,
      'reason': "The action (competitor accessing data) fits the 'money' category, but the method is vague and the negative impact on stakeholders (beyond SmartCity losing business) is not clearly described or specific to the scenario.",
      'is_ambiguous': True},
     {'criterion': 'Politics',
      'max_score': 1,
      'score': 0.5,
      'reason': "The action (influencing elections via the public app) fits the 'politics' category, but the method is not specified and the negative impact on stakeholders is not described in detail or adapted to the SmartCity context.",
      'is_ambiguous': True},
     {'criterion': 'Entertainment',
      'max_score': 1,
      'score': 0.5,
      'reason': "The action (messing with traffic lights for fun) fits the 'entertainment' category, but the impact on stakeholders is not fully explained or specific (e.g., how it could cause accidents or traffic jams).",
      'is_ambiguous': True}],
    'final_grade': 1.5,
    'overall_reason': 'All three actions correspond to the chosen categories, but each lacks a sufficiently detailed or scenario-specific description of the negative impact on stakeholders. The answers are vague and do not fully meet the rubric requirements for specificity and clarity.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Money): Corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Data theft/corporate espionage is a valid money-motivated bad actor action.',
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Money): Harm description is specific and clear',
      'max_score': 0.5,
      'score': 0.25,
      'reason': "Harm is generic (business loss). The answer fails to explain HOW accessing data causes harm and doesn't specify WHICH data or WHICH stakeholders are impacted (e.g., citizens' privacy, city authorities' competitive advantage, etc.). The scenario-specific context is missing.",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics): Corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Election manipulation is a valid politics-motivated bad actor action.',
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics): Harm description is specific and clear',
      'max_score': 0.5,
      'score': 0,
      'reason': "CRITICAL FLAW: The description explicitly states 'the exact method is not specified,' which violates the requirement. The answer provides no concrete mechanism of harm and no specific stakeholder impact. This is insufficient and shows the student did not adequately develop the action.",
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Entertainment): Corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Vandalism/sabotage for entertainment purposes is a valid entertainment-motivated bad actor action.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Entertainment): Harm description is specific and clear',
      'max_score': 0.5,
      'score': 0.125,
      'reason': "CRITICAL FLAW: The answer explicitly admits 'impact on stakeholders is not fully explained.' Traffic light manipulation would cause serious harms (accidents, injuries, deaths, traffic congestion, emergency response delays), but none are articulated. The answer fails both specificity and clarity requirements.",
      'is_ambiguous': False},
     {'criterion': 'Action distinctiveness (Penalization check)',
      'max_score': 0,
      'score': 0,
      'reason': 'The three actions (data theft, election manipulation, traffic sabotage) are sufficiently distinct. No penalization applied.',
      'is_ambiguous': False}],
    'final_grade': 1.375,
    'overall_reason': "POOR PERFORMANCE: The answer demonstrates significant deficiencies. While all three categories are appropriate and one action (Money) has adequate category alignment, two of three actions (Politics and Entertainment) are explicitly admitted by the student to lack clear specification and harm description. The answer shows incomplete analysis and fails to meet the rubric requirement that 'the description makes clear how the action is harmful/negatively impacts stakeholders and is specific to SmartCity.' The student needed to provide concrete, detailed mechanisms of harm with explicit stakeholder impacts tied to the IoT infrastructure scenario. Score breakdown: Action 1 = 0.75/1; Action 2 = 0.5/1; Action 3 = 0.625/1. Total: 1.375/3."}},
  {'openai': {'criteria_scores': [{'criterion': 'Self-Interest',
      'max_score': 1,
      'score': 0.5,
      'reason': 'The action (insider tracking a person) fits the self-interest category, but the negative impact is vague and not sufficiently described or specific to the SmartCity scenario.',
      'is_ambiguous': False},
     {'criterion': 'Ideas',
      'max_score': 1,
      'score': 0.75,
      'reason': "The action (posting false pollution messages) fits the ideas category and is specific to the public app in SmartCity. However, the negative impact is only described as 'some confusion,' which is not sufficiently detailed.",
      'is_ambiguous': False},
     {'criterion': 'Money',
      'max_score': 1,
      'score': 0.5,
      'reason': 'The action (hackers trying to make money) fits the money category, but the method and impact are not described, so it is not specific or clear how stakeholders are harmed.',
      'is_ambiguous': False}],
    'final_grade': 1.75,
    'overall_reason': 'The answers generally match the chosen categories, but all three lack sufficient detail about the negative impact on stakeholders and are not specific enough to the SmartCity scenario. The money and self-interest examples are especially vague, and the ideas example does not fully explain the harm caused.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Self-Interest): Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Self-interest is correctly identified as a category and tracking a person for personal motives fits this category.',
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Self-Interest): Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.2,
      'reason': "The harm is vaguely stated ('harmful if discovered'). The answer lacks specificity about consequences: who is impacted (the tracked person), how severely (privacy violation, potential stalking), and concrete details tied to SmartCity's infrastructure. The description is too generic.",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Ideas): Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Ideas category is correctly chosen. Spreading false information about pollution fits the 'ideas' category (misinformation as a bad actor weapon).",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Ideas): Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.15,
      'reason': "Critical deficiency: the harm is drastically underplayed as merely 'causing some confusion among users.' This fails to capture serious impacts like public panic, unnecessary health interventions, loss of trust in the system, or misallocation of resources. The description is superficial and does not adequately demonstrate negative stakeholder impact.",
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Money): Category Match',
      'max_score': 0.5,
      'score': 0.3,
      'reason': "Money category is identified, but the action itself is poorly defined. 'Hackers trying to make money from the system' is vague—it does not specify a concrete harmful action (ransomware, data theft, extortion, sabotage for profit, etc.).",
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Money): Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.1,
      'reason': "Severely lacking. The answer explicitly states 'it's not clear what method they would use or who would be affected'—meaning the answer itself acknowledges insufficient specificity. No concrete stakeholder impacts are described. This fails both the harm clarity and specificity-to-scenario requirements.",
      'is_ambiguous': False},
     {'criterion': 'Similarity Penalization',
      'max_score': 0,
      'score': -0.5,
      'reason': 'Actions 1 and 3 are problematically similar: both involve system misuse by insiders/attackers for personal gain without sufficient differentiation. The lack of distinct harm mechanisms warrants the -0.5 penalization.',
      'is_ambiguous': False}],
    'final_grade': 1.25,
    'overall_reason': "This answer demonstrates critical deficiencies across all three required actions. While category selection is partially correct, the execution is severely flawed: (1) Self-interest action lacks detailed impact description; (2) Ideas action trivializes the harm as mere 'confusion' when misinformation could cause panic and public health consequences; (3) Money action is vague and the student admits uncertainty about method and impact. Actions 1 and 3 lack sufficient differentiation. The response shows incomplete analysis, insufficient consideration of stakeholder consequences, and poor adaptation to the SmartCity scenario specifics. Under strict grading standards, this warrants approximately 1.25/3 points."}},
  {'openai': {'criteria_scores': [{'criterion': 'Politics',
      'max_score': 1,
      'score': 0.5,
      'reason': 'The action (using SmartCity data to embarrass local authorities) fits the politics category, but the negative impact is not sufficiently described or specific to the scenario.',
      'is_ambiguous': False},
     {'criterion': 'Entertainment',
      'max_score': 1,
      'score': 1,
      'reason': 'Triggering false waste-bin alerts for entertainment is a valid entertainment-motivated action, and the negative impact (wasting resources) is clearly described and specific to SmartCity.',
      'is_ambiguous': False},
     {'criterion': 'Ideas',
      'max_score': 1,
      'score': 0.5,
      'reason': 'Activists using the app to promote their cause fits the ideas category, but the negative impact on stakeholders is vague and not sufficiently described.',
      'is_ambiguous': False}],
    'final_grade': 2,
    'overall_reason': 'The answer provides three actions from three different categories, but for Politics and Ideas, the negative impacts are not sufficiently described or specific to the SmartCity scenario. The Entertainment example is clear and well-adapted. Total score: 2/3.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Politics): Correspondence to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Foreign group using data to embarrass authorities clearly fits the politics category.',
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Politics): Harm description and specificity',
      'max_score': 0.5,
      'score': 0.1,
      'reason': "The answer states harm 'isn't described' - this is a critical failure. No concrete negative impact on stakeholders is explained. How does embarrassment harm whom? What are the consequences? Not adapted to SmartCity specifics.",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Entertainment): Correspondence to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Triggering false alerts for curiosity/amusement fits the entertainment category.',
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Entertainment): Harm description and specificity',
      'max_score': 0.5,
      'score': 0.3,
      'reason': "Vaguely mentions 'wasting resources' but lacks specificity. Which resources? What is the actual impact on stakeholders? How does this specifically harm waste collection services or city authorities? Insufficiently developed.",
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Ideas): Correspondence to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Using the app to promote activist causes through ideas fits the ideas category.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Ideas): Harm description and specificity',
      'max_score': 0.5,
      'score': 0.1,
      'reason': "Answer explicitly states the negative impact is 'vague.' No concrete harm mechanism is provided. How does promoting a cause damage the SmartCity system or harm stakeholders? This is a fundamental requirement that is completely unmet.",
      'is_ambiguous': False},
     {'criterion': 'Similarity penalty check',
      'max_score': 0,
      'score': -0.5,
      'reason': "Actions 1 and 3 are too similar: both involve using SmartCity's data/platform to advance external agendas (politics/ideas) against city authorities. Both lack concrete harm descriptions. Penalization applied.",
      'is_ambiguous': False}],
    'final_grade': 1.4,
    'overall_reason': "This answer demonstrates significant deficiencies. While all three categories are correctly identified, the response fundamentally fails the harm description requirement for all three actions. The candidate acknowledges this failure explicitly (stating harm 'isn't described' and 'is vague'), which indicates awareness of inadequacy but no remediation. Actions 1 and 3 are too conceptually similar (both about external groups using platform/data against authorities). Only basic category matching is achieved; the critical requirement to explain specific, concrete negative impacts on SmartCity stakeholders is largely unmet. The answer reads as incomplete rough notes rather than a finished analysis."}}],
 [{'openai': {'criteria_scores': [{'criterion': 'Money',
      'max_score': 1,
      'score': 0.5,
      'reason': "The action (competitor accessing data) fits the 'money' category, but the method is vague and the negative impact on stakeholders (beyond SmartCity losing business) is not clearly described or specific to the scenario.",
      'is_ambiguous': True},
     {'criterion': 'Politics',
      'max_score': 1,
      'score': 0.5,
      'reason': "The action (influencing elections via the public app) fits the 'politics' category, but the method is not specified and the negative impact on stakeholders is not described in detail or adapted to the SmartCity context.",
      'is_ambiguous': True},
     {'criterion': 'Entertainment',
      'max_score': 1,
      'score': 0.5,
      'reason': "The action (messing with traffic lights for fun) fits the 'entertainment' category, but the impact on stakeholders is not fully explained or specific to the scenario.",
      'is_ambiguous': True}],
    'final_grade': 1.5,
    'overall_reason': 'All three actions correspond to the chosen categories, but each lacks sufficient detail about the method and/or the specific negative impact on stakeholders in the SmartCity scenario. The answers are vague and not fully adapted to the scenario, resulting in partial credit for each.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Money): Corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Data theft/corporate espionage clearly relates to the Money category.',
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Money): Harmful impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.2,
      'reason': "Impact is vague ('lose business'). The answer fails to explain HOW a competitor would access the data or WHICH stakeholders are harmed. No specificity to SmartCity's IoT infrastructure, data flows, or vulnerable endpoints.",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics): Corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Influencing elections through platform manipulation clearly relates to Politics category.',
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics): Harmful impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.1,
      'reason': "Critical failure: The method is explicitly stated as 'not specified.' The answer provides no concrete mechanism, no stakeholder harm explanation, and no adaptation to SmartCity's specific technology (a public health/infrastructure app, not a social media platform). Insufficient detail to meet rubric requirements.",
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Entertainment): Corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Vandalism/sabotage for amusement aligns with Entertainment category.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Entertainment): Harmful impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.15,
      'reason': "Impact is acknowledged as 'not fully explained.' The answer lacks specificity: no mention of traffic accidents, injuries, emergency response delays, or economic costs to the city. While traffic light manipulation is scenario-appropriate, the stakeholder harm is insufficiently detailed.",
      'is_ambiguous': False},
     {'criterion': 'Similarity penalty',
      'max_score': 0,
      'score': 0,
      'reason': 'The three actions are sufficiently distinct (data theft, election manipulation, physical sabotage). No penalty applied.',
      'is_ambiguous': False}],
    'final_grade': 1.45,
    'overall_reason': 'The answer demonstrates understanding of the Bad Actors framework by selecting three appropriate categories and providing scenario-relevant bad actor scenarios. However, execution is severely deficient. All three actions lack concrete, specific descriptions of how stakeholders would be harmed. The Politics action explicitly admits method is unspecified, and the Money and Entertainment actions provide only vague, generic impact descriptions. The answer fails to leverage SmartCity-specific vulnerabilities (IoT network security, ML model poisoning, sensor manipulation, dashboard access controls, etc.). To achieve full marks, each action requires: (1) a specific, detailed harmful method adapted to the scenario and (2) clear explanation of concrete negative impacts on named stakeholders (citizens, city authorities, SmartCity company, emergency services, etc.).'}},
  {'openai': {'criteria_scores': [{'criterion': 'Self-Interest',
      'max_score': 1,
      'score': 0.5,
      'reason': 'The action (insider tracking a person) fits the self-interest category, but the negative impact is vague and not sufficiently described or specific to the SmartCity scenario.',
      'is_ambiguous': False},
     {'criterion': 'Ideas',
      'max_score': 1,
      'score': 0.75,
      'reason': "The action (posting false pollution messages) fits the ideas category and is specific to the public app in SmartCity. However, the negative impact is only partially described ('causing some confusion'), lacking detail on stakeholder harm.",
      'is_ambiguous': False},
     {'criterion': 'Money',
      'max_score': 1,
      'score': 0.5,
      'reason': 'The action (hackers trying to make money) fits the money category, but the method and impact are not described, so the harm to stakeholders is unclear.',
      'is_ambiguous': False}],
    'final_grade': 1.75,
    'overall_reason': "The answers identify plausible bad actor actions for each category, but most lack sufficient detail about the negative impact on stakeholders and are not fully adapted to the SmartCity scenario. The 'money' and 'self-interest' answers are especially vague, while the 'ideas' answer is somewhat better but still lacks depth."},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Self-Interest) - Category Alignment',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Self-interest is correctly identified as a category from the Bad Actors Modeling strategy.',
      'is_ambiguous': False},

In [53]:
openai_runs = [[r["openai"] for r in run] for run in grading_runs_multi]

In [133]:
all_raters = build_rater_runs(grading_runs_multi)

In [134]:
all_raters

[[{'criteria_scores': [{'criterion': 'Politics',
     'max_score': 1,
     'score': 1,
     'reason': "The action (intelligence agencies using the system to gather information) fits the 'politics' category and the negative impact (loss of privacy and security for countries and their populations) is clearly described and specific to the SmartCity scenario.",
     'is_ambiguous': False},
    {'criterion': 'Money',
     'max_score': 1,
     'score': 1,
     'reason': "The action (robbers stealing valuable installed materials) fits the 'money' category and the negative impact (financial cost to reinstall materials) is clearly described and specific to the scenario.",
     'is_ambiguous': False},
    {'criterion': 'Entertainment',
     'max_score': 1,
     'score': 1,
     'reason': "The action (trolling waste collection services by manipulating sensors) fits the 'entertainment' category and the negative impact (waste collection services being misdirected repeatedly) is clearly described and specific to the SmartCity scenario.",
     'is_ambiguous': False}],
   'final_grade': 3,
   'overall_reason': 'All three actions are clearly linked to different categories, are distinct from each other, and the negative impacts are sufficiently described and specific to the SmartCity scenario. No penalizations apply.'},
  {'criteria_scores': [{'criterion': 'Money - Action corresponds to category and negative impact is specific to SmartCity',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses high costs and local authorities spending a lot of money, which fits the 'money' category. However, it does not clearly describe a bad actor's harmful action (e.g., price gouging, bribery, or financial fraud) but rather a general risk or consequence. The negative impact is somewhat described but lacks specificity about a bad actor's role.",
     'is_ambiguous': True},
    {'criterion': 'Self-interest - Action corresponds to category and negative impact is specific to SmartCity',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer mentions disinformation and people being harmed by false information, which fits 'self-interest' if the bad actor is manipulating data for personal gain. However, the example is vague and not clearly tied to a specific bad actor's action (e.g., a city employee falsifying data to avoid blame). The negative impact is described but not very specific to the SmartCity context.",
     'is_ambiguous': True},
    {'criterion': 'Ideas - Action corresponds to category and negative impact is specific to SmartCity',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses disagreement over automated temperature/ventilation settings, which relates to 'ideas' (conflicting values or beliefs). However, it does not clearly describe a bad actor's action (e.g., someone manipulating settings to push a particular ideology or agenda). The negative impact (unfairness, discomfort) is described but not strongly linked to a deliberate harmful action.",
     'is_ambiguous': True}],
   'final_grade': 1.5,
   'overall_reason': "The student attempted to address three different categories and provided some negative impacts, but in all cases, the harmful actions were not clearly described as deliberate actions by bad actors. The answers are vague, lack specificity, and do not fully meet the rubric's requirement for clear, scenario-adapted bad actor actions. Each response earns partial credit for category relevance and some negative impact description, but none are fully correct."},
  {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (competitor hacks system for financial gain) fits the 'money' category.",
     'is_ambiguous': False},
    {'criterion': 'Money - Negative impact described and scenario-specific',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer clearly describes how hacking would harm SmartCity's reputation and finances, and is specific to the scenario.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (political rival disrupts sensors to undermine current mayor) fits the 'politics' category.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Negative impact described and scenario-specific',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer explains how disruption would lead to public dissatisfaction and is specific to SmartCity's waste-bin sensors.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (privacy activists destroy/cover cameras) fits the 'ideas' category.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Negative impact described and scenario-specific',
     'max_score': 0.5,
     'score': 0.25,
     'reason': 'The answer mentions loss of traffic information and malfunctioning lights, but the negative impact on stakeholders is not fully developed (e.g., safety risks, increased congestion).',
     'is_ambiguous': False},
    {'criterion': 'Actions are sufficiently different',
     'max_score': 0,
     'score': 0,
     'reason': 'All three actions are distinct and correspond to different categories.',
     'is_ambiguous': False}],
   'final_grade': 2.75,
   'overall_reason': "The student correctly identified three distinct bad actor actions, each corresponding to a different category (money, politics, ideas), and described scenario-specific negative impacts. However, the negative impact for the 'ideas' category was not fully developed, resulting in a minor deduction."}],
 [{'criteria_scores': [{'criterion': 'Politics Category - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Intelligence agencies using surveillance tools for information gathering is a valid political bad actor scenario.',
     'is_ambiguous': False},
    {'criterion': 'Politics Category - Harmful impact description',
     'max_score': 0.5,
     'score': 0.25,
     'reason': "The answer states privacy and security loss but lacks specificity to SmartCity's infrastructure. Does not clearly explain HOW the IoT network (waste bins, cameras, weather sensors) enables this surveillance or which specific stakeholders are impacted.",
     'is_ambiguous': False},
    {'criterion': 'Money Category - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Physical theft of valuable hardware for financial gain is a valid money-motivated bad actor scenario.',
     'is_ambiguous': False},
    {'criterion': 'Money Category - Harmful impact description',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "Clearly explains the harmful impact: reinstallation costs to city authorities and service disruption. Specific to SmartCity's connected devices.",
     'is_ambiguous': False},
    {'criterion': 'Entertainment Category - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Trolling and malicious manipulation for amusement is a valid entertainment/self-amusement motivated bad actor scenario.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment Category - Harmful impact description',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Clearly describes the negative impact: waste collection services are redirected inefficiently, wasting time, fuel, and resources. Specific to the waste-bin sensor component.',
     'is_ambiguous': False},
    {'criterion': 'Action Distinctiveness',
     'max_score': 0,
     'score': -0.5,
     'reason': 'Politics and Money actions are too similar: both involve exploitation of the SmartCity infrastructure by bad actors for resource extraction (information vs. physical materials). Both describe theft/unauthorized access of system assets.',
     'is_ambiguous': False},
    {'criterion': 'Overall Specificity to Scenario',
     'max_score': 0,
     'score': 0,
     'reason': 'Politics action lacks detailed explanation of how IoT devices specifically enable surveillance or how the multi-country rollout amplifies this risk.',
     'is_ambiguous': False}],
   'final_grade': 2.25,
   'overall_reason': "Student correctly identified 3 categories with valid bad actor scenarios. Money and Entertainment categories are well-described with clear, specific harmful impacts (1 point each). Politics category shows conceptual understanding but lacks specificity to SmartCity's infrastructure (0.75 points). A 0.5-point penalty applied for similarity between Politics and Money actions—both frame bad actors exploiting SmartCity assets for personal gain without sufficient differentiation. The Politics action also needed clearer explanation of HOW the connected devices enable surveillance and which stakeholders are affected."},
  {'criteria_scores': [],
   'final_grade': 0,
   'overall_reason': 'Parsing failed',
   'error': 'JSON parse error: Expecting \',\' delimiter: line 51 column 6 (char 3254) | Raw: ```json\n{\n  "criteria_scores": [\n    {\n      "criterion": "Category 1 (Money): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The answer mentions high c',
   'raw_output': '```json\n{\n  "criteria_scores": [\n    {\n      "criterion": "Category 1 (Money): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The answer mentions high costs but does not clearly describe a BAD ACTOR\'s harmful action. It vaguely states \'it might encourage local authorities to spend a lot of money\' without identifying a specific malicious actor or intentional harmful behavior. This reads as a general concern rather than a bad actor scenario.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 1 (Money): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The negative impact is poorly articulated and not specific to SmartCity\'s scenario. No clear stakeholder harm is described, and it fails to explain how a bad actor would exploit the financial aspect to cause damage.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 2 (Self-interest): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.3,\n      "reason": "The answer attempts to describe misuse of the camera/traffic system but conflates \'disinformation\' with false traffic violations. Self-interest typically involves personal gain; this description is unclear about the bad actor\'s motivation or benefit. The scenario is confused and poorly articulated.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 2 (Self-interest): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.35,\n      "reason": "The example about a red light violation is confusing and poorly explained. While it attempts to show harm to innocent citizens, the mechanism is vague and doesn\'t clearly demonstrate how SmartCity\'s specific IoT system could be exploited for self-interest. The connection between the bad actor and their benefit is missing.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 3 (Ideas): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.4,\n      "reason": "The answer identifies ideological disagreement about automated temperature/ventilation control, which somewhat relates to the \'ideas\' category. However, the distinction between disagreement and a bad actor deliberately exploiting this system is not clear. This reads more as a design flaw than a bad actor\'s action.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 3 (Ideas): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.35,\n      "reason": "The negative impact (discomfort and unfairness) is mentioned but not specific to SmartCity or how a bad actor would deliberately cause harm. The answer describes a potential usability problem rather than demonstrating how someone with bad intentions could exploit the system for ideological purposes.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Action differentiation (penalty check)",\n      "max_score": 0,\n      "score": -0.5,\n      "reason": "Categories 1 and 2 are too similar—both describe general misuse/costs of the system without clearly distinct harmful actions. Both lack specificity about the bad actor\'s distinct method of harm.",\n      "is_ambiguous": false\n    }\n  ],\n  "final_grade": 1.0,\n  "overall_reason": "This answer demonstrates significant weaknesses across all three required bad actor scenarios. None of the three actions are clearly described as intentional harmful acts by bad actors with specific motivations. The Money category conflates cost concerns with bad actor behavior. The Self-interest category is confusingly written with an unclear mechanism for exploitation. The Ideas category describes disagreement rather than bad actor exploitation. Additionally, the Money and Self-interest actions are too similar in their vagueness about the harmful mechanism, triggering a -0.5 penalty. Each criterion barely achieves partial credit due to lack of specificity, scenario adaptation, and clarity. A passing response would require: (1) clearly identified bad actors with explicit motivations, (2) specific'},
  {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "Hacking to gain market share and financial advantage clearly fits the 'money' category.",
     'is_ambiguous': False},
    {'criterion': 'Money - Harm description is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The answer clearly describes how hacking causes reputational damage, loss of contracts, and financial loss to SmartCity. Specific to the scenario.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "Disrupting sensors to manipulate elections and gain political power clearly fits the 'politics' category.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Harm description is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer explains how sensor disruption leads to overflowing bins, citizen dissatisfaction with the current council, and electoral advantage for the competitor. Specific to SmartCity's waste management system.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "Privacy ideology-driven destruction of cameras clearly fits the 'ideas' category as it's motivated by ideological principles rather than financial or political gain.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Harm description is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer describes concrete harms: loss of traffic information for road users and traffic light malfunction. Properly adapted to SmartCity's traffic management system.",
     'is_ambiguous': False},
    {'criterion': 'Action differentiation - No excessive similarity',
     'max_score': 0,
     'score': 0,
     'reason': 'The three actions target different systems (centralized control system, waste sensors, traffic cameras) with different motivations (money, politics, ideas). No penalization needed.',
     'is_ambiguous': False},
    {'criterion': 'Negative impact sufficiency',
     'max_score': 0,
     'score': 0,
     'reason': 'All three negative impacts are sufficiently described with clear stakeholder effects. No penalization needed.',
     'is_ambiguous': False}],
   'final_grade': 3.0,
   'overall_reason': 'Excellent response. The student selected three distinct categories (Money, Politics, Ideas) and provided well-developed bad actor scenarios for each. All actions clearly map to their respective categories, and the harmful impacts are specific to the SmartCity scenario with concrete examples of stakeholder damage. The three actions target different system components and are sufficiently differentiated. No penalizations apply. Full marks awarded.'}],
 [{'criteria_scores': [{'criterion': 'Politics - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The action describes intelligence agencies using the system for surveillance, which fits the politics category.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Negative impact is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The answer explains that privacy and security of countries and their populations would be compromised, which is specific to the SmartCity scenario.',
     'is_ambiguous': False},
    {'criterion': 'Money - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Describes theft of valuable IoT equipment for resale, which is a money-motivated action.',
     'is_ambiguous': False},
    {'criterion': 'Money - Negative impact is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'States that theft would result in financial loss due to the need to reinstall equipment, which is specific to the scenario.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Describes trolling (pranking) waste collection services, which fits the entertainment category.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Negative impact is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Explains that manipulation would cause waste collectors to be redirected unnecessarily, which is a clear and scenario-specific negative impact.',
     'is_ambiguous': False}],
   'final_grade': 3,
   'overall_reason': 'All three actions are clearly distinct, correspond to the chosen categories, and the negative impacts are specific to the SmartCity scenario and well described. No penalizations apply.'},
  {'criteria_scores': [{'criterion': 'Money - Action corresponds to category and negative impact is specific',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses high costs and potential overspending by authorities, which fits the 'money' category. However, it does not describe a harmful action by a bad actor (e.g., a vendor overcharging, or a corrupt official embezzling funds). The negative impact is only vaguely described as 'spending a lot of money' and is not clearly tied to a malicious action.",
     'is_ambiguous': False},
    {'criterion': 'Self-interest - Action corresponds to category and negative impact is specific',
     'max_score': 1,
     'score': 0.75,
     'reason': "The answer describes someone using the system for disinformation, which fits 'self-interest.' The example is somewhat unclear, but it suggests a person manipulating data to get others in trouble. The negative impact is described (innocent people getting in trouble), but the scenario is vague and not clearly tied to a specific SmartCity feature.",
     'is_ambiguous': True},
    {'criterion': 'Ideas - Action corresponds to category and negative impact is specific',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses disagreement over automated temperature/ventilation settings, which fits 'ideas' (conflicting beliefs/preferences). However, it does not describe a harmful action by a bad actor, but rather a general dissatisfaction. The negative impact (unfairness/discomfort) is described, but not as a result of a malicious action.",

 ### AGGREGATION

In [54]:
import numpy as np

def aggregate(grading_runs):
    result = []

    for i in range(len(grading_runs[0])):
        scores = [run[i]["final_grade"] for run in grading_runs]

        result.append({
            "mean": float(np.mean(scores)),
            "std": float(np.std(scores)),
            "min": float(np.min(scores)),
            "max": float(np.max(scores))
        })

    return result

def summarize_runs(aggregated):
    return [
        f"Student {i+1}: mean={a['mean']:.1f}, std={a['std']:.1f}"
        for i, a in enumerate(aggregated)
    ]

In [151]:
def aggregate_multi(grading_runs_multi):
    result = []

    num_students = len(grading_runs_multi[0])

    for i in range(num_students):
        scores = []

        for run in grading_runs_multi:
            scores.append(run[i]["openai"].get("final_grade", 0))
            scores.append(run[i]["claude"].get("final_grade", 0))

        result.append({
            "mean": float(np.mean(scores)),
            "std": float(np.std(scores)),
            "min": float(np.min(scores)),
            "max": float(np.max(scores))
        })

    return result

In [ ]:

aggregated_openai = aggregate(openai_runs)
aggregated_summary_openai = summarize_runs(aggregated_openai)

In [ ]:
aggregated_openai

[{'mean': 3.0, 'std': 0.0, 'min': 3.0, 'max': 3.0},
 {'mean': 1.5833333333333333,
  'std': 0.11785113019775792,
  'min': 1.5,
  'max': 1.75},
 {'mean': 2.8333333333333335,
  'std': 0.11785113019775792,
  'min': 2.75,
  'max': 3.0}]

In [ ]:
aggregated_summary_openai

['Student 1: mean=3.0, std=0.0',
 'Student 2: mean=1.6, std=0.1',
 'Student 3: mean=2.8, std=0.1']

In [152]:
aggregated = aggregate_multi(grading_runs_multi)

In [153]:
aggregated

[{'mean': 2.6750000000000003,
  'std': 0.3338537604001689,
  'min': 2.25,
  'max': 3.0},
 {'mean': 1.25, 'std': 0.5816642788871715, 'min': 0.0, 'max': 1.75},
 {'mean': 2.8333333333333335,
  'std': 0.18633899812498247,
  'min': 2.5,
  'max': 3.0}]

In [154]:
aggregated_summary = summarize_runs(aggregated)

In [155]:
aggregated_summary

['Student 1: mean=2.7, std=0.3',
 'Student 2: mean=1.2, std=0.6',
 'Student 3: mean=2.8, std=0.2']

## Test Evaluation

### Metrics

In [61]:
!pip install pandas scipy pingouin

Requirement already satisfied: pandas in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (3.0.2)
Collecting scipy
  Downloading scipy-1.17.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting pingouin
  Downloading pingouin-0.6.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting matplotlib (from pingouin)
  Downloading matplotlib-3.10.8-cp312-cp312-macosx_11_0_arm64.whl.metadata (52 kB)
Collecting pandas_flavor (from pingouin)
  Downloading pandas_flavor-0.8.1-py3-none-any.whl.metadata (6.6 kB)
Collecting scikit-learn>=1.2.2 (from pingouin)
  Downloading scikit_learn-1.8.0-cp312-cp312-macosx_12_0_arm64.whl.metadata (11 kB)
Collecting seaborn (from pingouin)
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting statsmodels>=0.14.1 (from pingouin)
  Downloading statsmodels-0.14.6-cp312-cp312-macosx_11_0_arm64.whl.metadata (9.5 kB)
Collecting tabulate (from pingouin)
  Using cached tabulate-0.10.0-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: six>=1.5 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting joblib>=1.3.0 (from scikit-learn>=1.2.2->pingouin)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn>=1.2.2->pingouin)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting patsy>=0.5.6 (from statsmodels>=0.14.1->pingouin)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: packaging>=21.3 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from statsmodels>=0.14.1->pingouin) (26.1)
Collecting contourpy>=1.0.1 (from matplotlib->pingouin)
  Using cached contourpy-1.3.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib->pingouin)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->pingouin)
  Downloading fonttools-4.62.1-cp312-cp312-macosx_10_13_universal2.whl.metadata (117 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->pingouin)
  Downloading kiwisolver-1.5.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (5.1 kB)
Requirement already satisfied: pillow>=8 in /Users/tuba/Desktop/demos/epfl/rubric_evaluator/rubric_evaluator_github/.venv/lib/python3.12/site-packages (from matplotlib->pingouin) (12.2.0)
Collecting pyparsing>=3 (from matplotlib->pingouin)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting xarray (from pandas_flavor->pingouin)
  Downloading xarray-2026.4.0-py3-none-any.whl.metadata (12 kB)
Downloading scipy-1.17.1-cp312-cp312-macosx_14_0_arm64.whl (20.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 34.9 MB/s  0:00:00m0:00:0100:01
Downloading pingouin-0.6.1-py3-none-any.whl (203 kB)
Downloading scikit_learn-1.8.0-cp312-cp312-macosx_12_0_arm64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 31.7 MB/s  0:00:00 eta 0:00:01
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading statsmodels-0.14.6-cp312-cp312-macosx_11_0_arm64.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 25.5 MB/s  0:00:00eta 0:00:01
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading matplotlib-3.10.8-cp312-cp312-macosx_11_0_arm64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 48.6 MB/s  0:00:00
Using cached contourpy-1.3.3-cp312-cp312-macosx_11_0_arm64.whl (273 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp312-cp312-macosx_10_13_universal2.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 38.6 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp312-cp312-macosx_11_0_arm64.whl (64 kB)
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading pandas_flavor-0.8.1-py3-none-any.whl (8.5 kB)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached tabulate-0.10.0-py3-none-any.whl (39 kB)
Downloading xarray-2026.4.0-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 21.0 MB/s  0:00:00
Installing collected packages: threadpoolctl, tabulate, scipy, pyparsing, patsy, kiwisolver, joblib, fonttools, cycler, contourpy, scikit-learn, matplotlib, xarray, statsmodels, seaborn, pandas_flavor, pingouin
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17/17 [pingouin]/17 [seaborn]els]]
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 joblib-1.5.3 kiwisolver-1.5.0 matplotlib-3.10.8 pandas_flavor-0.8.1 patsy-1.0.2 pingouin-0.6.1 pyparsing-3.3.2 scikit-learn-1.8.0 scipy-1.17.1 seaborn-0.13.2 statsmodels-0.14.6 tabulate-0.10.0 threadpoolctl-3.6.0 xarray-2026.4.0

In [99]:
import numpy as np
import pandas as pd
from scipy.stats import spearmanr
import pingouin as pg


# ----------------------------
# 1. AMBIGUITY → ICC
# ----------------------------
def ambiguity_score_icc(grading_runs):
    """
    Measures inter-rater reliability using ICC.
    High ICC → low ambiguity.

    Uses:
    - ICC(A,1) → agreement between individual raters (preferred)
    - fallback: ICC(A,k)

    Returns score in [0,100]
    """

    data = []

    for r_idx, run in enumerate(grading_runs):
        for s_idx, g in enumerate(run):
            data.append({
                "student": s_idx,
                "rater": r_idx,
                "score": g.get("final_grade", 0)
            })

    df = pd.DataFrame(data)

    # Edge case: no variance → perfect agreement
    if df["score"].nunique() <= 1:
        return 100.0

    icc = pg.intraclass_corr(
        data=df,
        targets="student",
        raters="rater",
        ratings="score"
    )


    row = icc[icc["Type"].isin(["ICC(A,1)", "ICC(A,k)"])]

    if row.empty:
        return 0.0

    value = row["ICC"].iloc[0]

    # Clamp to valid ICC range
    value = max(-1.0, min(1.0, float(value)))

    # Map [-1,1] → [0,100]
    score = (value + 1) / 2 * 100
    return score


# ----------------------------
# 2. DISCRIMINATION → SPEARMAN
# ----------------------------
def discrimination_score_spearman(good, edge, bad):
    """
    Measures whether ranking is preserved:
    good > edge > bad using Spearman correlation.
    """

    scores = good + edge + bad

    # labels: good=2, edge=1, bad=0
    labels = (
        [2] * len(good) +
        [1] * len(edge) +
        [0] * len(bad)
    )

    if len(scores) < 2:
        return 0.0

    corr, _ = spearmanr(scores, labels)

    if np.isnan(corr):
        return 0.0

    # map [-1,1] → [0,100]
    return float((corr + 1) / 2 * 100)


# ----------------------------
# 3. APPLICABILITY → EDGE VARIANCE
# ----------------------------
def applicability_score(edge_scores, grading_runs):
    """
    Measures how rubric handles edge cases.
    Uses standard deviation:
    - too low → rigid
    - too high → unstable
    Ideal → moderate variance
    """

    if not edge_scores:
        return 0.0

    std = np.std(edge_scores)

    overall_std = np.std([
        g["final_grade"]
        for run in grading_runs
        for g in run
    ]) + 1e-6

    stability = 1 - (std / overall_std)

    return float(np.clip(stability, 0, 1) * 100)


# ----------------------------
# 4. CONSISTENCY → STD ACROSS RUNS
# ----------------------------
def consistency_score(grading_runs):
    """
    Measures within-model consistency (across runs).
    """

    stds = []

    for i in range(len(grading_runs[0])):
        vals = [r[i]["final_grade"] for r in grading_runs]
        stds.append(np.std(vals))

    mean_std = np.mean(stds)

    overall_std = np.std([
        g["final_grade"]
        for run in grading_runs
        for g in run
    ]) + 1e-6

    return float(np.clip(1 - mean_std / overall_std, 0, 1) * 100)


# ----------------------------
# 5. CROSS-MODEL CONSISTENCY
# ----------------------------
def cross_model_consistency(results):
    """
    Measures agreement between OpenAI and Claude.
    """

    diffs = []

    for r in results:
        o = r["openai"].get("final_grade", 0)
        c = r["claude"].get("final_grade", 0)
        diffs.append(abs(o - c))

    if not diffs:
        return 100.0

    max_diff = max(diffs) + 1e-6
    mean_diff = np.mean(diffs)

    return float(np.clip(1 - mean_diff / max_diff, 0, 1) * 100)

In [63]:
# 7. CONSISTENCY
consistency = consistency_score(openai_runs)

In [64]:
consistency

87.71411687524876

In [65]:
# 8. CROSS MODEL
flat_multi = [r for run in grading_runs_multi for r in run]
cross_model_score = cross_model_consistency(flat_multi)

In [66]:
cross_model_score

63.33335777776148

In [211]:
def extract_scores(runs, mode="all"):
    scores = []

    for run in runs:
        for r in run:
            if mode == "all":
                for model in r:
                    scores.append(r[model]["final_grade"])
            else:
                scores.append(r[mode]["final_grade"])

    return scores

In [210]:
good_runs_multi

[[{'openai': {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Deploying ransomware for financial gain is a classic 'money' bad actor motivation.",
      'is_ambiguous': False},
     {'criterion': 'Money - Negative impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The answer clearly explains how ransomware would disrupt waste collection and traffic, harming residents and city operations.',
      'is_ambiguous': False},
     {'criterion': 'Politics - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Manipulating traffic data to influence a political event is a clear example of a politically motivated attack.',
      'is_ambiguous': False},
     {'criterion': 'Politics - Negative impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The answer specifies disruption of civic activities and loss of public trust, directly tied to the SmartCity scenario.',
      'is_ambiguous': False},
     {'criterion': 'Self-Interest - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "An insider manipulating data for personal reasons fits the 'self-interest' category.",
      'is_ambiguous': False},
     {'criterion': 'Self-Interest - Negative impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The answer explains how this would waste resources and increase costs, which is specific to the SmartCity system.',
      'is_ambiguous': False}],
    'final_grade': 3.0,
    'overall_reason': 'All three actions are clearly distinct, correspond to the chosen categories, and the negative impacts are well described and specific to the SmartCity scenario. No penalizations apply.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Money) - Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Ransomware attack clearly corresponds to money/financial motivation category.',
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Money) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Clearly describes negative impact (service disruption, waste delays, traffic congestion) with specific reference to SmartCity systems.',
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics) - Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Data manipulation during political event directly corresponds to politics category.',
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Explicitly describes harm (congestion, impaired emergency services, erosion of public trust) adapted to the traffic monitoring component of SmartCity.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Self-Interest) - Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Insider actor altering data for personal benefit clearly matches self-interest category.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Self-Interest) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Well-articulated harm (resource waste, increased costs, taxpayer impact) specifically tied to weather sensor manipulation in SmartCity's ventilation/cooling systems.",
      'is_ambiguous': False},
     {'criterion': 'Action Distinctiveness',
      'max_score': 0,
      'score': 0,
      'reason': 'All three actions are sufficiently different (ransomware attack vs. data manipulation vs. sensor falsification). No penalization applied.',
      'is_ambiguous': False}],
    'final_grade': 3.0,
    'overall_reason': 'Excellent response. All three bad actor actions are properly categorized, clearly described, and specifically adapted to the SmartCity scenario. Each action distinctly targets different system components (network security, traffic data, weather sensors) with well-articulated negative impacts on stakeholders. The answer demonstrates strong understanding of the Bad Actors Modeling strategy with no deductions warranted.'}},
  {'openai': {'criteria_scores': [{'criterion': 'Ideas',
      'max_score': 1,
      'score': 1,
      'reason': "The action (hacktivists spreading misinformation via the public app) fits the 'ideas' category and is specific to the SmartCity scenario. The negative impact (panic or mistrust among citizens, disregard for real warnings) is clearly described.",
      'is_ambiguous': False},
     {'criterion': 'Money',
      'max_score': 1,
      'score': 1,
      'reason': "The action (criminals stealing and selling traffic camera footage) fits the 'money' category and is specific to SmartCity. The negative impact (privacy violation, fraudulent claims) is clearly described.",
      'is_ambiguous': False},
     {'criterion': 'Entertainment',
      'max_score': 1,
      'score': 1,
      'reason': "The action (thrill-seekers tampering with traffic lights for fun) fits the 'entertainment' category and is specific to SmartCity. The negative impact (traffic jams, increased accident risk, endangering public safety) is clearly described.",
      'is_ambiguous': False}],
    'final_grade': 3,
    'overall_reason': 'All three actions are clearly distinct, correspond to the chosen categories, and are well-adapted to the SmartCity scenario. The negative impacts are specific and sufficiently described. No penalizations apply.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Ideas): Category Alignment',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Defacing the public app and spreading misinformation clearly aligns with the 'Ideas' category, which concerns manipulation of information and narratives.",
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Ideas): Harmful Impact & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The response clearly explains how the misinformation causes panic, mistrust, and citizen confusion regarding health warnings. The example is appropriately tailored to SmartCity's public app function.",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Money): Category Alignment',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Stealing and selling footage for profit directly aligns with the 'Money' category, which focuses on financial gain through illegal means.",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Money): Harmful Impact & Specificity',
      'max_score': 0.5,
      'score': 0.25,
      'reason': 'While the action is mentioned, the harmful impact description is underdeveloped. The response lists potential harms (privacy violation, fraudulent claims) but does not sufficiently explain the mechanism or depth of negative impact on specific SmartCity stakeholders (e.g., citizens whose movements are tracked, city authorities facing liability, etc.).',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Entertainment): Category Alignment',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Tampering with traffic lights 'for fun' aligns well with the 'Entertainment' category, which covers actors seeking amusement or thrill without other primary motives.",
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Entertainment): Harmful Impact & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The response clearly describes concrete harms: traffic jams and increased accident risk. The impact is well-specified to SmartCity's traffic management system and directly affects public safety.",
      'is_ambiguous': False},
     {'criterion': 'Distinctiveness Between Actions',
      'max_score': 0,
      'score': -0.5,
      'reason': 'Actions 1 and 2 share problematic overlap: both involve digital manipulation/interference (defacing the app vs. stealing data), and both cause harm through information abuse or data compromise. While technically in different categories, the execution methods and stakeholder impacts are too similar, warranting the similarity penalty.',
      'is_ambiguous': False}],
    'final_grade': 2.25,
    'overall_reason': "The response demonstrates understanding of the Bad Actors Modeling strategy and selects three distinct categories appropriately. All three actions are scenario-specific and relate to SmartCity's IoT infrastructure. However, two issues reduce the score: (1) Action 2's harmful impact is insufficiently detailed, earning only 0.25 points instead of 0.5 for clarity and depth; (2) Actions 1 and 2 are too similar in nature (both digital interference/data abuse), triggering a 0.5-point penalty. The response achieves 2.25 out of 3 points total."}},
  {'openai': {'criteria_scores': [{'criterion': 'Entertainment',
      'max_score': 1,
      'score': 1,
      'reason': 'The action (trolls sending false alerts about overflowing bins) fits the entertainment category and is specific to the SmartCity scenario. The negative impact (unnecessary dispatches and confusion for waste management staff) is clearly described.',
      'is_ambiguous': False},
     {'criterion': 'Politics',
      'max_score': 1,
      'score': 1,
      'reason': 'The action (political activists manipulating pollution data to exaggerate air quality issues during an election) fits the politics category and is specific to the scenario. The negative impact (undermining the credibility of local authorities) is clearly described.',
      'is_ambiguous': False},
     {'criterion': 'Money',
      'max_score': 1,
      'score': 1,
      'reason': 'The action (competitors introducing malware to cause system downtime and financial losses) fits the money category and is specific to SmartCity. The negative impact (financial losses for the company and cities) is clearly described.',
      'is_ambiguous': False}],
    'final_grade': 3,
    'overall_reason': 'All three actions are clearly linked to different categories, are specific to the SmartCity scenario, and the negative impacts are well described. No actions are too similar, and all impacts are sufficiently explained.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Entertainment) - Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Entertainment category correctly identified. Trolling behavior fits the entertainment/mischief motivation in Bad Actors Modeling.',
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Entertainment) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Clear negative impact described: false alerts cause unnecessary waste collection dispatches and confusion for staff. Specific to SmartCity's waste-bin monitoring system.",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics) - Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Politics category correctly identified. Data manipulation for electoral advantage clearly falls under political motivation.',
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Politics) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Harm is clearly described: exaggerated pollution data undermines authority credibility and manipulates public perception. Specific to the public app feature of SmartCity.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Money) - Category Match',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Money category correctly identified. Competitor sabotage for financial gain is a valid money-motivated bad actor scenario.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Money) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.25,
      'reason': "Harm description lacks sufficient specificity to SmartCity. 'Sabotage by introducing malware' is generic and could apply to any IoT/tech company. The answer does not clearly explain concrete impacts on specific stakeholders (e.g., citizens unable to access traffic optimization, waste collection failures affecting neighborhoods, health alerts unavailable during emergencies).",
      'is_ambiguous': False},
     {'criterion': 'Similarity Check',
      'max_score': 0,
      'score': -0.5,
      'reason': 'Actions 1 and 3 are problematically similar: both describe system disruption through unauthorized access/malware introduction to cause operational failures. Entertainment trolling (false bin alerts) and Money sabotage (malware) both result in degraded system functionality for the same stakeholder (city authorities/services). This violates the requirement for actions to be different from each other.',
      'is_ambiguous': False}],
    'final_grade': 2.25,
    'overall_reason': 'The answer demonstrates solid understanding of Bad Actors Modeling with appropriate category selection and mostly clear harm descriptions. Entertainment and Politics actions are well-articulated and sufficiently different. However, two critical issues reduce the score: (1) Action 3 lacks scenario-specific detail about how malware sabotage harms SmartCity stakeholders, describing harm too generically; (2) Actions 1 and 3 are too similar in their operational impact (system disruption through unauthorized access), warranting the -0.5 similarity penalty. Score: 3.0 (full points) - 0.5 (similarity penalty) - 0.25 (insufficient specificity on Action 3) = 2.25/3.0'}},
  {'openai': {'criteria_scores': [{'criterion': 'Self-Interest',
      'max_score': 1,
      'score': 1,
      'reason': 'The action (employee tracking an individual via dashboard) fits the self-interest category and is specific to the SmartCity scenario. The negative impact (privacy violation, potential stalking) is clearly described.',
      'is_ambiguous': False},
     {'criterion': 'Money',
      'max_score': 1,
      'score': 1,
      'reason': "The action (cybercriminals selling real-time data) fits the money category and is relevant to the scenario. The negative impact (data breach, risk to citizens' information) is sufficiently described.",
      'is_ambiguous': False},
     {'criterion': 'Ideas',
      'max_score': 1,
      'score': 1,
      'reason': 'The action (injecting false alerts to spread propaganda) fits the ideas category and is specific to the SmartCity public app. The negative impact (confusion and fear among residents) is clearly explained.',
      'is_ambiguous': False}],
    'final_grade': 3,
    'overall_reason': 'All three actions are clearly linked to different Bad Actors Modeling categories, are distinct from each other, and the negative impacts are specific and well described in the context of the SmartCity scenario.'},
   'claude': {'criteria_scores': [{'criterion': 'Action 1 (Self-Interest) - Category Correspondence',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Self-interest as a category involves personal gain, advantage, or benefit at others' expense. An employee exploiting system access for personal surveillance clearly falls under self-interested motives.",
      'is_ambiguous': False},
     {'criterion': 'Action 1 (Self-Interest) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The response clearly describes how the harmful action (tracking individuals via traffic cameras) negatively impacts stakeholders (privacy violation, stalking risk) and is appropriately specific to SmartCity's camera infrastructure.",
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Money) - Category Correspondence',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Money as a category concerns financial gain and economic exploitation. Selling data for profit directly corresponds to monetary motivations.',
      'is_ambiguous': False},
     {'criterion': 'Action 2 (Money) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The response adequately describes the harmful outcome (data breach, unauthorized access, privacy risks) and ties it to SmartCity's specific data collection systems (weather and traffic data).",
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Ideas) - Category Correspondence',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Ideas as a category involves ideological manipulation and influence. Using the system to spread propaganda clearly aligns with manipulating information and pushing ideological agendas.',
      'is_ambiguous': False},
     {'criterion': 'Action 3 (Ideas) - Harm Description & Specificity',
      'max_score': 0.5,
      'score': 0.25,
      'reason': "While the response identifies a harmful action (false alerts via public app), the harm description is somewhat generic. The impact 'causing confusion and fear' lacks specificity about how this damages stakeholders or infrastructure in the SmartCity context. More concrete consequences would strengthen this (e.g., causing public panic affecting emergency response systems, undermining trust in official health alerts).",
      'is_ambiguous': False},
     {'criterion': 'Penalization - Action Similarity',
      'max_score': 0,
      'score': -0.5,
      'reason': 'Actions 1 and 2 share a concerning similarity: both involve unauthorized access to system data (employee accessing dashboard for tracking; cybercriminals intercepting data). They represent variations of the same core malicious behavior pattern (data exploitation through system compromise), triggering the -0.5 penalization.',
      'is_ambiguous': False}],
    'final_grade': 2.25,
    'overall_reason': "The response demonstrates good understanding of the Bad Actors Modeling strategy with appropriate category selection. All three actions correspond correctly to their assigned categories, and Actions 1 and 2 have strong, specific harm descriptions tied to SmartCity's infrastructure. However, Action 3's harm description lacks sufficient detail and specificity, losing 0.25 points. The critical issue is that Actions 1 and 2 are too similar—both essentially describe unauthorized data access and exploitation through system compromise—triggering a -0.5 penalization. The candidate should have selected more distinct categories or developed fundamentally different attack vectors to fully maximize the score."}}],
 [{'openai': {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Deploying ransomware for financial gain is a clear 'money' motivation.",
      'is_ambiguous': False},
     {'criterion': 'Money - Harmful impact is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The answer clearly describes disruption to waste collection and traffic, with negative effects on residents and city operations.',
      'is_ambiguous': False},
     {'criterion': 'Politics - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Manipulating traffic data to influence a political event is a clear 'politics' motivation.",
      'is_ambiguous': False},
     {'criterion': 'Politics - Harmful impact is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The answer specifies disruption of civic activities and loss of public trust, which are relevant and specific to the scenario.',
      'is_ambiguous': False},
     {'criterion': 'Self-Interest - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "An insider acting for personal benefit (e.g., to avoid work or benefit from increased contracts) fits 'self-interest.'",
      'is_ambiguous': False},

In [ ]:
 # 9. EXTRACT SCORES
good_scores_openai = extract_scores(good_runs_multi, "openai")
bad_scores_openai  = extract_scores(bad_runs_multi, "openai")
edge_scores_openai = extract_scores(edge_runs_multi, "openai")

In [ ]:
good_scores_openai

[3.0, 3, 3, 3, 3.0, 3, 3, 3, 3.0, 3, 3, 3]

In [ ]:
bad_scores_openai

[1.5, 1.5, 0.5, 1, 1.5, 1.5, 0, 1.5, 1.5, 1.5, 0, 1]

In [ ]:
edge_scores_openai

[1.5, 1.75, 2, 1.5, 1.75, 2, 1.5, 1.75, 2]

In [93]:
openai_runs

[[{'criteria_scores': [{'criterion': 'Politics',
     'max_score': 1,
     'score': 1,
     'reason': "The action (intelligence agencies using the system to gather information) fits the 'politics' category and the negative impact (loss of privacy and security for countries and their populations) is clearly described and specific to the SmartCity scenario.",
     'is_ambiguous': False},
    {'criterion': 'Money',
     'max_score': 1,
     'score': 1,
     'reason': "The action (robbers stealing valuable installed materials) fits the 'money' category and the negative impact (financial cost to reinstall materials) is clearly described and specific to the scenario.",
     'is_ambiguous': False},
    {'criterion': 'Entertainment',
     'max_score': 1,
     'score': 1,
     'reason': "The action (trolling waste collection services by manipulating sensors) fits the 'entertainment' category and the negative impact (waste collection services being misdirected repeatedly) is clearly described and specific to the SmartCity scenario.",
     'is_ambiguous': False}],
   'final_grade': 3,
   'overall_reason': 'All three actions are clearly linked to different categories, are distinct from each other, and the negative impacts are sufficiently described and specific to the SmartCity scenario. No penalizations apply.'},
  {'criteria_scores': [{'criterion': 'Money - Action corresponds to category and negative impact is specific to SmartCity',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses high costs and local authorities spending a lot of money, which fits the 'money' category. However, it does not clearly describe a bad actor's harmful action (e.g., price gouging, bribery, or financial fraud) but rather a general risk or consequence. The negative impact is somewhat described but lacks specificity about a bad actor's role.",
     'is_ambiguous': True},
    {'criterion': 'Self-interest - Action corresponds to category and negative impact is specific to SmartCity',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer mentions disinformation and people being harmed by false information, which fits 'self-interest' if the bad actor is manipulating data for personal gain. However, the example is vague and not clearly tied to a specific bad actor's action (e.g., a city employee falsifying data to avoid blame). The negative impact is described but not very specific to the SmartCity context.",
     'is_ambiguous': True},
    {'criterion': 'Ideas - Action corresponds to category and negative impact is specific to SmartCity',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses disagreement over automated temperature/ventilation settings, which relates to 'ideas' (conflicting values or beliefs). However, it does not clearly describe a bad actor's action (e.g., someone manipulating settings to push a particular ideology or agenda). The negative impact (unfairness, discomfort) is described but not strongly linked to a deliberate harmful action.",
     'is_ambiguous': True}],
   'final_grade': 1.5,
   'overall_reason': "The student attempted to address three different categories and provided some negative impacts, but in all cases, the harmful actions were not clearly described as deliberate actions by bad actors. The answers are vague, lack specificity, and do not fully meet the rubric's requirement for clear, scenario-adapted bad actor actions. Each response earns partial credit for category relevance and some negative impact description, but none are fully correct."},
  {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (competitor hacks system for financial gain) fits the 'money' category.",
     'is_ambiguous': False},
    {'criterion': 'Money - Negative impact described and scenario-specific',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer clearly describes how hacking would harm SmartCity's reputation and finances, and is specific to the scenario.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (political rival disrupts sensors to undermine current mayor) fits the 'politics' category.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Negative impact described and scenario-specific',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer explains how disruption would lead to public dissatisfaction and is specific to SmartCity's waste-bin sensors.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (privacy activists destroy/cover cameras) fits the 'ideas' category.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Negative impact described and scenario-specific',
     'max_score': 0.5,
     'score': 0.25,
     'reason': 'The answer mentions loss of traffic information and malfunctioning lights, but the negative impact on stakeholders is not fully developed (e.g., safety risks, increased congestion).',
     'is_ambiguous': False},
    {'criterion': 'Actions are sufficiently different',
     'max_score': 0,
     'score': 0,
     'reason': 'All three actions are distinct and correspond to different categories.',
     'is_ambiguous': False}],
   'final_grade': 2.75,
   'overall_reason': "The student correctly identified three distinct bad actor actions, each corresponding to a different category (money, politics, ideas), and described scenario-specific negative impacts. However, the negative impact for the 'ideas' category was not fully developed, resulting in a minor deduction."}],
 [{'criteria_scores': [{'criterion': 'Politics - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The action describes intelligence agencies using the system for surveillance, which fits the politics category.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Negative impact is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The answer explains that privacy and security of countries and their populations would be compromised, which is specific to the SmartCity scenario.',
     'is_ambiguous': False},
    {'criterion': 'Money - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Describes theft of valuable IoT equipment for resale, which is a money-motivated action.',
     'is_ambiguous': False},
    {'criterion': 'Money - Negative impact is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'States that theft would result in financial loss due to the need to reinstall equipment, which is specific to the scenario.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Describes trolling (pranking) waste collection services, which fits the entertainment category.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Negative impact is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Explains that manipulation would cause waste collectors to be redirected unnecessarily, which is a clear and scenario-specific negative impact.',
     'is_ambiguous': False}],
   'final_grade': 3,
   'overall_reason': 'All three actions are clearly distinct, correspond to the chosen categories, and the negative impacts are specific to the SmartCity scenario and well described. No penalizations apply.'},
  {'criteria_scores': [{'criterion': 'Money - Action corresponds to category and negative impact is specific',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses high costs and potential overspending by authorities, which fits the 'money' category. However, it does not describe a harmful action by a bad actor (e.g., a vendor overcharging, or a corrupt official embezzling funds). The negative impact is only vaguely described as 'spending a lot of money' and is not clearly tied to a malicious action.",
     'is_ambiguous': False},
    {'criterion': 'Self-interest - Action corresponds to category and negative impact is specific',
     'max_score': 1,
     'score': 0.75,
     'reason': "The answer describes someone using the system for disinformation, which fits 'self-interest.' The example is somewhat unclear, but it suggests a person manipulating data to get others in trouble. The negative impact is described (innocent people getting in trouble), but the scenario is vague and not clearly tied to a specific SmartCity feature.",
     'is_ambiguous': True},
    {'criterion': 'Ideas - Action corresponds to category and negative impact is specific',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses disagreement over automated temperature/ventilation settings, which fits 'ideas' (conflicting beliefs/preferences). However, it does not describe a harmful action by a bad actor, but rather a general dissatisfaction. The negative impact (unfairness/discomfort) is described, but not as a result of a malicious action.",
     'is_ambiguous': False}],
   'final_grade': 1.75,
   'overall_reason': "The answers generally identify relevant categories and some negative impacts, but mostly fail to describe specific harmful actions by bad actors as required by the rubric. The 'money' and 'ideas' answers are too general and lack a clear malicious action. The 'self-interest' answer is closer but still vague. More specificity and clear bad actor actions are needed for full marks."},
  {'criteria_scores': [{'criterion': 'Money - Action corresponds to category and is specific to SmartCity',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (competitor hacks system for financial gain) fits the 'money' category and is specific to SmartCity's centralized system.",
     'is_ambiguous': False},
    {'criterion': 'Money - Negative impact is clear and specific',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The negative impact (reputation loss, financial loss, operational disruption) is clearly described and specific to SmartCity.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Action corresponds to category and is specific to SmartCity',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (political rival disrupts waste-bin sensors to undermine current mayor) fits the 'politics' category and is specific to SmartCity's waste-bin sensors.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Negative impact is clear and specific',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The negative impact (citizen dissatisfaction, political consequences) is clearly described and specific to the scenario.',
     'is_ambiguous': False},
    {'criterion': 'Ideas - Action corresponds to category and is specific to SmartCity',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (privacy activists destroy/cover cameras) fits the 'ideas' category and is specific to SmartCity's traffic cameras.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Negative impact is clear and specific',
     'max_score': 0.5,
     'score': 0.25,
     'reason': 'The negative impact (loss of traffic information, malfunctioning traffic lights) is described, but the explanation is somewhat vague and could be more specific about how stakeholders are harmed.',
     'is_ambiguous': False}],
   'final_grade': 2.75,
   'overall_reason': "All three actions are distinct, correspond to the correct categories, and are adapted to the SmartCity scenario. The negative impacts are generally clear and specific, but the 'ideas' category impact is not fully developed, resulting in a minor deduction."}],
 [{'criteria_scores': [{'criterion': 'Politics',
     'max_score': 1,
     'score': 1,
     'reason': "The action (intelligence agencies using the system to gather information) fits the 'politics' category and the negative impact (loss of privacy and security for countries and their populations) is clearly described and specific to the SmartCity scenario.",
     'is_ambiguous': False},
    {'criterion': 'Money',
     'max_score': 1,
     'score': 1,
     'reason': "The action (robbers stealing valuable installed materials) fits the 'money' category and the negative impact (financial cost to reinstall materials) is clearly described and specific to the scenario.",
     'is_ambiguous': False},
    {'criterion': 'Entertainment',
     'max_score': 1,
     'score': 1,
     'reason': "The action (trolling waste collection services by manipulating sensors) fits the 'entertainment' category and the negative impact (waste collection services being misdirected) is clearly described and specific to the SmartCity scenario.",
     'is_ambiguous': False}],
   'final_grade': 3,
   'overall_reason': 'All three actions are clearly linked to different categories, are distinct from each other, and the negative impacts are sufficiently described and specific to the SmartCity scenario. No penalizations apply.'},
  {'criteria_scores': [{'criterion': 'Money - Action corresponds to category and negative impact is specific',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses high costs and potential overspending by local authorities, which fits the 'money' category. However, the negative impact is vague and not clearly tied to a harmful action by a bad actor (e.g., corruption, fraud, or price gouging). The answer does not specify a malicious action, just a general risk.",
     'is_ambiguous': False},
    {'criterion': 'Self-interest - Action corresponds to category and negative impact is specific',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer mentions disinformation and people getting in trouble due to misuse, which fits 'self-interest.' However, the description is unclear and lacks specificity about the bad actor's action (e.g., a city employee manipulating data for personal gain). The negative impact is somewhat described but not clearly linked to a concrete action.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Action corresponds to category and negative impact is specific',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses disagreement over automated temperature/ventilation settings, which fits 'ideas.' However, it does not describe a harmful action by a bad actor, just a general consequence of the system. The negative impact (unfairness/discomfort) is mentioned but not clearly tied to a malicious act.",
     'is_ambiguous': False}],
   'final_grade': 1.5,
   'overall_reason': 'Each answer identifies a relevant category and a potential negative impact, but none clearly describe a specific harmful action by a bad actor as required by the rubric. The answers are vague, lack concrete examples of malicious actions, and do not fully explain how stakeholders are harmed by those actions. Each response earns partial credit for category relevance and some mention of negative impact, but not full points.'},
  {'criteria_scores': [{'criterion': 'Money - Action corresponds to category and is specific to SmartCity',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (competitor hacks system for financial gain) fits the 'money' category and is specific to SmartCity's centralized system.",
     'is_ambiguous': False},
    {'criterion': 'Money - Negative impact is clear and specific',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The negative impact (reputation damage, financial loss, loss of contracts) is clearly described and specific to SmartCity.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Action corresponds to category and is specific to SmartCity',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (political rival disrupts waste-bin sensors to undermine current mayor) fits the 'politics' category and is specific to SmartCity's waste-bin sensors.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Negative impact is clear and specific',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The negative impact (citizen dissatisfaction, political consequences) is clearly described and specific to the scenario.',
     'is_ambiguous': False},
    {'criterion': 'Ideas - Action corresponds to category and is specific to SmartCity',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (pro-privacy group destroys/covers cameras due to ideological opposition) fits the 'ideas' category and is specific to SmartCity's traffic cameras.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Negative impact is clear and specific',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The negative impact (loss of traffic information, malfunctioning traffic lights, inconvenience to road users) is clearly described and specific to the scenario.',
     'is_ambiguous': False}],
   'final_grade': 3,
   'overall_reason': 'All three actions are clearly linked to different categories from the Bad Actors Modeling strategy, are specific to the SmartCity scenario, and the negative impacts are well described. No actions are too similar, and all impacts are sufficiently detailed.'}]]

In [135]:
all_raters

[[{'criteria_scores': [{'criterion': 'Politics',
     'max_score': 1,
     'score': 1,
     'reason': "The action (intelligence agencies using the system to gather information) fits the 'politics' category and the negative impact (loss of privacy and security for countries and their populations) is clearly described and specific to the SmartCity scenario.",
     'is_ambiguous': False},
    {'criterion': 'Money',
     'max_score': 1,
     'score': 1,
     'reason': "The action (robbers stealing valuable installed materials) fits the 'money' category and the negative impact (financial cost to reinstall materials) is clearly described and specific to the scenario.",
     'is_ambiguous': False},
    {'criterion': 'Entertainment',
     'max_score': 1,
     'score': 1,
     'reason': "The action (trolling waste collection services by manipulating sensors) fits the 'entertainment' category and the negative impact (waste collection services being misdirected repeatedly) is clearly described and specific to the SmartCity scenario.",
     'is_ambiguous': False}],
   'final_grade': 3,
   'overall_reason': 'All three actions are clearly linked to different categories, are distinct from each other, and the negative impacts are sufficiently described and specific to the SmartCity scenario. No penalizations apply.'},
  {'criteria_scores': [{'criterion': 'Money - Action corresponds to category and negative impact is specific to SmartCity',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses high costs and local authorities spending a lot of money, which fits the 'money' category. However, it does not clearly describe a bad actor's harmful action (e.g., price gouging, bribery, or financial fraud) but rather a general risk or consequence. The negative impact is somewhat described but lacks specificity about a bad actor's role.",
     'is_ambiguous': True},
    {'criterion': 'Self-interest - Action corresponds to category and negative impact is specific to SmartCity',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer mentions disinformation and people being harmed by false information, which fits 'self-interest' if the bad actor is manipulating data for personal gain. However, the example is vague and not clearly tied to a specific bad actor's action (e.g., a city employee falsifying data to avoid blame). The negative impact is described but not very specific to the SmartCity context.",
     'is_ambiguous': True},
    {'criterion': 'Ideas - Action corresponds to category and negative impact is specific to SmartCity',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses disagreement over automated temperature/ventilation settings, which relates to 'ideas' (conflicting values or beliefs). However, it does not clearly describe a bad actor's action (e.g., someone manipulating settings to push a particular ideology or agenda). The negative impact (unfairness, discomfort) is described but not strongly linked to a deliberate harmful action.",
     'is_ambiguous': True}],
   'final_grade': 1.5,
   'overall_reason': "The student attempted to address three different categories and provided some negative impacts, but in all cases, the harmful actions were not clearly described as deliberate actions by bad actors. The answers are vague, lack specificity, and do not fully meet the rubric's requirement for clear, scenario-adapted bad actor actions. Each response earns partial credit for category relevance and some negative impact description, but none are fully correct."},
  {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (competitor hacks system for financial gain) fits the 'money' category.",
     'is_ambiguous': False},
    {'criterion': 'Money - Negative impact described and scenario-specific',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer clearly describes how hacking would harm SmartCity's reputation and finances, and is specific to the scenario.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (political rival disrupts sensors to undermine current mayor) fits the 'politics' category.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Negative impact described and scenario-specific',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer explains how disruption would lead to public dissatisfaction and is specific to SmartCity's waste-bin sensors.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (privacy activists destroy/cover cameras) fits the 'ideas' category.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Negative impact described and scenario-specific',
     'max_score': 0.5,
     'score': 0.25,
     'reason': 'The answer mentions loss of traffic information and malfunctioning lights, but the negative impact on stakeholders is not fully developed (e.g., safety risks, increased congestion).',
     'is_ambiguous': False},
    {'criterion': 'Actions are sufficiently different',
     'max_score': 0,
     'score': 0,
     'reason': 'All three actions are distinct and correspond to different categories.',
     'is_ambiguous': False}],
   'final_grade': 2.75,
   'overall_reason': "The student correctly identified three distinct bad actor actions, each corresponding to a different category (money, politics, ideas), and described scenario-specific negative impacts. However, the negative impact for the 'ideas' category was not fully developed, resulting in a minor deduction."}],
 [{'criteria_scores': [{'criterion': 'Politics Category - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Intelligence agencies using surveillance tools for information gathering is a valid political bad actor scenario.',
     'is_ambiguous': False},
    {'criterion': 'Politics Category - Harmful impact description',
     'max_score': 0.5,
     'score': 0.25,
     'reason': "The answer states privacy and security loss but lacks specificity to SmartCity's infrastructure. Does not clearly explain HOW the IoT network (waste bins, cameras, weather sensors) enables this surveillance or which specific stakeholders are impacted.",
     'is_ambiguous': False},
    {'criterion': 'Money Category - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Physical theft of valuable hardware for financial gain is a valid money-motivated bad actor scenario.',
     'is_ambiguous': False},
    {'criterion': 'Money Category - Harmful impact description',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "Clearly explains the harmful impact: reinstallation costs to city authorities and service disruption. Specific to SmartCity's connected devices.",
     'is_ambiguous': False},
    {'criterion': 'Entertainment Category - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Trolling and malicious manipulation for amusement is a valid entertainment/self-amusement motivated bad actor scenario.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment Category - Harmful impact description',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Clearly describes the negative impact: waste collection services are redirected inefficiently, wasting time, fuel, and resources. Specific to the waste-bin sensor component.',
     'is_ambiguous': False},
    {'criterion': 'Action Distinctiveness',
     'max_score': 0,
     'score': -0.5,
     'reason': 'Politics and Money actions are too similar: both involve exploitation of the SmartCity infrastructure by bad actors for resource extraction (information vs. physical materials). Both describe theft/unauthorized access of system assets.',
     'is_ambiguous': False},
    {'criterion': 'Overall Specificity to Scenario',
     'max_score': 0,
     'score': 0,
     'reason': 'Politics action lacks detailed explanation of how IoT devices specifically enable surveillance or how the multi-country rollout amplifies this risk.',
     'is_ambiguous': False}],
   'final_grade': 2.25,
   'overall_reason': "Student correctly identified 3 categories with valid bad actor scenarios. Money and Entertainment categories are well-described with clear, specific harmful impacts (1 point each). Politics category shows conceptual understanding but lacks specificity to SmartCity's infrastructure (0.75 points). A 0.5-point penalty applied for similarity between Politics and Money actions—both frame bad actors exploiting SmartCity assets for personal gain without sufficient differentiation. The Politics action also needed clearer explanation of HOW the connected devices enable surveillance and which stakeholders are affected."},
  {'criteria_scores': [],
   'final_grade': 0,
   'overall_reason': 'Parsing failed',
   'error': 'JSON parse error: Expecting \',\' delimiter: line 51 column 6 (char 3254) | Raw: ```json\n{\n  "criteria_scores": [\n    {\n      "criterion": "Category 1 (Money): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The answer mentions high c',
   'raw_output': '```json\n{\n  "criteria_scores": [\n    {\n      "criterion": "Category 1 (Money): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The answer mentions high costs but does not clearly describe a BAD ACTOR\'s harmful action. It vaguely states \'it might encourage local authorities to spend a lot of money\' without identifying a specific malicious actor or intentional harmful behavior. This reads as a general concern rather than a bad actor scenario.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 1 (Money): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The negative impact is poorly articulated and not specific to SmartCity\'s scenario. No clear stakeholder harm is described, and it fails to explain how a bad actor would exploit the financial aspect to cause damage.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 2 (Self-interest): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.3,\n      "reason": "The answer attempts to describe misuse of the camera/traffic system but conflates \'disinformation\' with false traffic violations. Self-interest typically involves personal gain; this description is unclear about the bad actor\'s motivation or benefit. The scenario is confused and poorly articulated.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 2 (Self-interest): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.35,\n      "reason": "The example about a red light violation is confusing and poorly explained. While it attempts to show harm to innocent citizens, the mechanism is vague and doesn\'t clearly demonstrate how SmartCity\'s specific IoT system could be exploited for self-interest. The connection between the bad actor and their benefit is missing.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 3 (Ideas): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.4,\n      "reason": "The answer identifies ideological disagreement about automated temperature/ventilation control, which somewhat relates to the \'ideas\' category. However, the distinction between disagreement and a bad actor deliberately exploiting this system is not clear. This reads more as a design flaw than a bad actor\'s action.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 3 (Ideas): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.35,\n      "reason": "The negative impact (discomfort and unfairness) is mentioned but not specific to SmartCity or how a bad actor would deliberately cause harm. The answer describes a potential usability problem rather than demonstrating how someone with bad intentions could exploit the system for ideological purposes.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Action differentiation (penalty check)",\n      "max_score": 0,\n      "score": -0.5,\n      "reason": "Categories 1 and 2 are too similar—both describe general misuse/costs of the system without clearly distinct harmful actions. Both lack specificity about the bad actor\'s distinct method of harm.",\n      "is_ambiguous": false\n    }\n  ],\n  "final_grade": 1.0,\n  "overall_reason": "This answer demonstrates significant weaknesses across all three required bad actor scenarios. None of the three actions are clearly described as intentional harmful acts by bad actors with specific motivations. The Money category conflates cost concerns with bad actor behavior. The Self-interest category is confusingly written with an unclear mechanism for exploitation. The Ideas category describes disagreement rather than bad actor exploitation. Additionally, the Money and Self-interest actions are too similar in their vagueness about the harmful mechanism, triggering a -0.5 penalty. Each criterion barely achieves partial credit due to lack of specificity, scenario adaptation, and clarity. A passing response would require: (1) clearly identified bad actors with explicit motivations, (2) specific'},
  {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "Hacking to gain market share and financial advantage clearly fits the 'money' category.",
     'is_ambiguous': False},
    {'criterion': 'Money - Harm description is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The answer clearly describes how hacking causes reputational damage, loss of contracts, and financial loss to SmartCity. Specific to the scenario.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "Disrupting sensors to manipulate elections and gain political power clearly fits the 'politics' category.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Harm description is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer explains how sensor disruption leads to overflowing bins, citizen dissatisfaction with the current council, and electoral advantage for the competitor. Specific to SmartCity's waste management system.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "Privacy ideology-driven destruction of cameras clearly fits the 'ideas' category as it's motivated by ideological principles rather than financial or political gain.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Harm description is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer describes concrete harms: loss of traffic information for road users and traffic light malfunction. Properly adapted to SmartCity's traffic management system.",
     'is_ambiguous': False},
    {'criterion': 'Action differentiation - No excessive similarity',
     'max_score': 0,
     'score': 0,
     'reason': 'The three actions target different systems (centralized control system, waste sensors, traffic cameras) with different motivations (money, politics, ideas). No penalization needed.',
     'is_ambiguous': False},
    {'criterion': 'Negative impact sufficiency',
     'max_score': 0,
     'score': 0,
     'reason': 'All three negative impacts are sufficiently described with clear stakeholder effects. No penalization needed.',
     'is_ambiguous': False}],
   'final_grade': 3.0,
   'overall_reason': 'Excellent response. The student selected three distinct categories (Money, Politics, Ideas) and provided well-developed bad actor scenarios for each. All actions clearly map to their respective categories, and the harmful impacts are specific to the SmartCity scenario with concrete examples of stakeholder damage. The three actions target different system components and are sufficiently differentiated. No penalizations apply. Full marks awarded.'}],
 [{'criteria_scores': [{'criterion': 'Politics - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The action describes intelligence agencies using the system for surveillance, which fits the politics category.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Negative impact is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The answer explains that privacy and security of countries and their populations would be compromised, which is specific to the SmartCity scenario.',
     'is_ambiguous': False},
    {'criterion': 'Money - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Describes theft of valuable IoT equipment for resale, which is a money-motivated action.',
     'is_ambiguous': False},
    {'criterion': 'Money - Negative impact is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'States that theft would result in financial loss due to the need to reinstall equipment, which is specific to the scenario.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Describes trolling (pranking) waste collection services, which fits the entertainment category.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Negative impact is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Explains that manipulation would cause waste collectors to be redirected unnecessarily, which is a clear and scenario-specific negative impact.',
     'is_ambiguous': False}],
   'final_grade': 3,
   'overall_reason': 'All three actions are clearly distinct, correspond to the chosen categories, and the negative impacts are specific to the SmartCity scenario and well described. No penalizations apply.'},
  {'criteria_scores': [{'criterion': 'Money - Action corresponds to category and negative impact is specific',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses high costs and potential overspending by authorities, which fits the 'money' category. However, it does not describe a harmful action by a bad actor (e.g., a vendor overcharging, or a corrupt official embezzling funds). The negative impact is only vaguely described as 'spending a lot of money' and is not clearly tied to a malicious action.",
     'is_ambiguous': False},
    {'criterion': 'Self-interest - Action corresponds to category and negative impact is specific',
     'max_score': 1,
     'score': 0.75,
     'reason': "The answer describes someone using the system for disinformation, which fits 'self-interest.' The example is somewhat unclear, but it suggests a person manipulating data to get others in trouble. The negative impact is described (innocent people getting in trouble), but the scenario is vague and not clearly tied to a specific SmartCity feature.",
     'is_ambiguous': True},
    {'criterion': 'Ideas - Action corresponds to category and negative impact is specific',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses disagreement over automated temperature/ventilation settings, which fits 'ideas' (conflicting beliefs/preferences). However, it does not describe a harmful action by a bad actor, but rather a general dissatisfaction. The negative impact (unfairness/discomfort) is described, but not as a result of a malicious action.",

## TEST SCORES

## Only Openai Runs

### Ambiguity (Inter-rater reliability)
### Intraclass Correlation (ICC)

In [94]:
data = []

for r_idx, run in enumerate(openai_runs):
    for s_idx, g in enumerate(run):
        data.append({
            "student": s_idx,
            "rater": r_idx,
            "score": g.get("final_grade", 0)
        })

df = pd.DataFrame(data)

In [95]:
df

   student  rater  score
0        0      0   3.00
1        1      0   1.50
2        2      0   2.75
3        0      1   3.00
4        1      1   1.75
5        2      1   2.75
6        0      2   3.00
7        1      2   1.50
8        2      2   3.00

In [96]:
df["score"].nunique()

4

In [97]:
icc = pg.intraclass_corr(
        data=df,
        targets="student",
        raters="rater",
        ratings="score"
    )

In [98]:
icc

       Type       ICC      F  df1  df2      pval         CI95
0  ICC(1,1)  0.977186  129.5    2    6  0.000012  [0.85, 1.0]
1  ICC(A,1)  0.977143  103.6    2    4  0.000359  [0.83, 1.0]
2  ICC(C,1)  0.971591  103.6    2    4  0.000359  [0.74, 1.0]
3  ICC(1,k)  0.992278  129.5    2    6  0.000012  [0.94, 1.0]
4  ICC(A,k)  0.992263  103.6    2    4  0.000359  [0.94, 1.0]
5  ICC(C,k)  0.990347  103.6    2    4  0.000359   [0.9, 1.0]

In [104]:
row = icc[icc["Type"].isin(["ICC(A,1)", "ICC(A,k)"])]

In [105]:
row

       Type       ICC      F  df1  df2      pval         CI95
1  ICC(A,1)  0.977143  103.6    2    4  0.000359  [0.83, 1.0]
4  ICC(A,k)  0.992263  103.6    2    4  0.000359  [0.94, 1.0]

In [106]:
value = row["ICC"].iloc[0]
value

np.float64(0.9771428571428573)

In [107]:
value = max(-1.0, min(1.0, float(value)))

In [108]:
value

0.9771428571428573

### DISCRIMINATION → SPEARMAN

In [110]:
scores = good_scores + edge_scores + bad_scores
scores

[3.0,
 3,
 3,
 3,
 3.0,
 3,
 3,
 3,
 3.0,
 3,
 3,
 3,
 1.5,
 1.75,
 2,
 1.5,
 1.75,
 2,
 1.5,
 1.75,
 2,
 1.5,
 1.5,
 0.5,
 1,
 1.5,
 1.5,
 0,
 1.5,
 1.5,
 1.5,
 0,
 1]

In [112]:
# labels: good=2, edge=1, bad=0
labels = (
        [2] * len(good_scores) +
        [1] * len(edge_scores) +
        [0] * len(bad_scores)
    )
labels

[2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [113]:
corr, _ = spearmanr(scores, labels)
corr

np.float64(0.938078085394056)

In [114]:
float((corr + 1) / 2 * 100)

96.9039042697028

### Applicability (EDGE VARIANCE)

In [115]:
std = np.std(edge_scores)
std

np.float64(0.2041241452319315)

In [117]:
overall_std = np.std([
        g["final_grade"]
        for run in openai_runs
        for g in run
    ]) + 1e-6

overall_std

np.float64(0.6394934685122966)

In [118]:
stability = 1 - (std / overall_std)
stability

np.float64(0.6808033931811667)

In [119]:
float(np.clip(stability, 0, 1) * 100)

68.08033931811667

### CONSISTENCY → STD ACROSS RUNS

In [120]:
stds = []

for i in range(len(openai_runs[0])):
    vals = [r[i]["final_grade"] for r in openai_runs]
    stds.append(np.std(vals))

stds

[np.float64(0.0),
 np.float64(0.11785113019775792),
 np.float64(0.11785113019775792)]

In [121]:
mean_std = np.mean(stds)
mean_std

np.float64(0.07856742013183861)

In [122]:
overall_std = np.std([
        g["final_grade"]
        for run in openai_runs
        for g in run
    ]) + 1e-6

overall_std

np.float64(0.6394934685122966)

In [123]:
stability = 1 - (mean_std / overall_std)
stability

np.float64(0.8771411687524876)

In [124]:
float(np.clip(stability, 0, 1) * 100)

87.71411687524876

## ALL RATERS ( OPENAI + CLAUDE)

In [212]:
 # 9. EXTRACT SCORES
good_scores = extract_scores(good_runs_multi)
bad_scores  = extract_scores(bad_runs_multi)
edge_scores = extract_scores(edge_runs_multi)

In [213]:
good_scores

[3.0,
 3.0,
 3,
 2.25,
 3,
 2.25,
 3,
 2.25,
 3.0,
 3.0,
 3,
 2.25,
 3,
 2.25,
 3,
 2.5,
 3.0,
 3.0,
 3,
 2.25,
 3,
 2.75,
 3,
 3.0]

In [214]:
bad_scores

[1.5,
 1.25,
 1.5,
 0,
 0.5,
 1.5,
 1,
 1.2,
 1.5,
 0.95,
 1.5,
 0.45,
 0,
 0.25,
 1.5,
 0,
 1.5,
 0.75,
 1.5,
 0,
 0,
 0.25,
 1,
 0.5]

In [216]:
edge_scores

[1.5,
 1.375,
 1.75,
 1.25,
 2,
 1.4,
 1.5,
 1.45,
 1.75,
 1.25,
 2,
 1.2,
 1.5,
 0,
 1.75,
 0.95,
 2,
 0]

### Ambiguity (Inter-rater reliability)
### Intraclass Correlation (ICC)

In [136]:
data = []

for r_idx, run in enumerate(all_raters):
    for s_idx, g in enumerate(run):
        data.append({
            "student": s_idx,
            "rater": r_idx,
            "score": g.get("final_grade", 0)
        })

df = pd.DataFrame(data)

In [137]:
df

    student  rater  score
0         0      0   3.00
1         1      0   1.50
2         2      0   2.75
3         0      1   2.25
4         1      1   0.00
5         2      1   3.00
6         0      2   3.00
7         1      2   1.75
8         2      2   2.75
9         0      3   2.30
10        1      3   1.55
11        2      3   3.00
12        0      4   3.00
13        1      4   1.50
14        2      4   3.00
15        0      5   2.50
16        1      5   1.20
17        2      5   2.50

In [138]:
df["score"].nunique()

10

In [139]:
icc = pg.intraclass_corr(
        data=df,
        targets="student",
        raters="rater",
        ratings="score"
    )

In [140]:
icc

       Type       ICC          F  df1  df2      pval          CI95
0  ICC(1,1)  0.789786  23.542353    2   15  0.000024   [0.4, 0.99]
1  ICC(A,1)  0.791083  28.610869    2   10  0.000073   [0.4, 0.99]
2  ICC(C,1)  0.821486  28.610869    2   10  0.000073  [0.41, 0.99]
3  ICC(1,k)  0.957523  23.542353    2   15  0.000024    [0.8, 1.0]
4  ICC(A,k)  0.957841  28.610869    2   10  0.000073    [0.8, 1.0]
5  ICC(C,k)  0.965048  28.610869    2   10  0.000073   [0.81, 1.0]

In [141]:
row = icc[icc["Type"].isin(["ICC(A,1)", "ICC(A,k)"])]

In [142]:
row

       Type       ICC          F  df1  df2      pval         CI95
1  ICC(A,1)  0.791083  28.610869    2   10  0.000073  [0.4, 0.99]
4  ICC(A,k)  0.957841  28.610869    2   10  0.000073   [0.8, 1.0]

In [143]:
value = row["ICC"].iloc[0]
value

np.float64(0.7910827644029228)

In [144]:
value = max(-1.0, min(1.0, float(value)))

In [145]:
value

0.7910827644029228

### DISCRIMINATION → SPEARMAN

In [217]:
scores = good_scores + edge_scores + bad_scores
scores

[3.0,
 3.0,
 3,
 2.25,
 3,
 2.25,
 3,
 2.25,
 3.0,
 3.0,
 3,
 2.25,
 3,
 2.25,
 3,
 2.5,
 3.0,
 3.0,
 3,
 2.25,
 3,
 2.75,
 3,
 3.0,
 1.5,
 1.375,
 1.75,
 1.25,
 2,
 1.4,
 1.5,
 1.45,
 1.75,
 1.25,
 2,
 1.2,
 1.5,
 0,
 1.75,
 0.95,
 2,
 0,
 1.5,
 1.25,
 1.5,
 0,
 0.5,
 1.5,
 1,
 1.2,
 1.5,
 0.95,
 1.5,
 0.45,
 0,
 0.25,
 1.5,
 0,
 1.5,
 0.75,
 1.5,
 0,
 0,
 0.25,
 1,
 0.5]

In [218]:
# labels: good=2, edge=1, bad=0
labels = (
        [2] * len(good_scores) +
        [1] * len(edge_scores) +
        [0] * len(bad_scores)
    )
labels

[2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [219]:
corr, _ = spearmanr(scores, labels)
corr

np.float64(0.8389032074818091)

In [221]:
float((corr + 1) / 2 * 100)

91.94516037409046

### Applicability (EDGE VARIANCE)

In [226]:
std = np.std(edge_scores)
std

np.float64(0.5612365783816842)

In [227]:
overall_std = np.std([
        g["final_grade"]
        for run in all_raters
        for g in run
    ]) + 1e-6

overall_std

np.float64(0.8175977870367639)

In [228]:
stability = 1 - (std / overall_std)
stability

np.float64(0.31355418607994867)

In [229]:
float(np.clip(stability, 0, 1) * 100)

31.355418607994867

### CONSISTENCY → STD ACROSS RUNS

In [169]:
stds = []

for i in range(len(openai_runs[0])):
    vals = [r[i]["final_grade"] for r in openai_runs]
    stds.append(np.std(vals))

stds

[np.float64(0.0),
 np.float64(0.11785113019775792),
 np.float64(0.11785113019775792)]

In [170]:
mean_std = np.mean(stds)
mean_std

np.float64(0.07856742013183861)

In [171]:
overall_std = np.std([
        g["final_grade"]
        for run in openai_runs
        for g in run
    ]) + 1e-6

overall_std

np.float64(0.6394934685122966)

In [172]:
stability = 1 - (mean_std / overall_std)
stability

np.float64(0.8771411687524876)

In [173]:
float(np.clip(stability, 0, 1) * 100)

87.71411687524876

###  CROSS-MODEL CONSISTENCY

In [125]:
flat_multi = [r for run in grading_runs_multi for r in run]
flat_multi

[{'openai': {'criteria_scores': [{'criterion': 'Politics',
     'max_score': 1,
     'score': 1,
     'reason': "The action (intelligence agencies using the system to gather information) fits the 'politics' category and the negative impact (loss of privacy and security for countries and their populations) is clearly described and specific to the SmartCity scenario.",
     'is_ambiguous': False},
    {'criterion': 'Money',
     'max_score': 1,
     'score': 1,
     'reason': "The action (robbers stealing valuable installed materials) fits the 'money' category and the negative impact (financial cost to reinstall materials) is clearly described and specific to the scenario.",
     'is_ambiguous': False},
    {'criterion': 'Entertainment',
     'max_score': 1,
     'score': 1,
     'reason': "The action (trolling waste collection services by manipulating sensors) fits the 'entertainment' category and the negative impact (waste collection services being misdirected repeatedly) is clearly described and specific to the SmartCity scenario.",
     'is_ambiguous': False}],
   'final_grade': 3,
   'overall_reason': 'All three actions are clearly linked to different categories, are distinct from each other, and the negative impacts are sufficiently described and specific to the SmartCity scenario. No penalizations apply.'},
  'claude': {'criteria_scores': [{'criterion': 'Politics Category - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Intelligence agencies using surveillance tools for information gathering is a valid political bad actor scenario.',
     'is_ambiguous': False},
    {'criterion': 'Politics Category - Harmful impact description',
     'max_score': 0.5,
     'score': 0.25,
     'reason': "The answer states privacy and security loss but lacks specificity to SmartCity's infrastructure. Does not clearly explain HOW the IoT network (waste bins, cameras, weather sensors) enables this surveillance or which specific stakeholders are impacted.",
     'is_ambiguous': False},
    {'criterion': 'Money Category - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Physical theft of valuable hardware for financial gain is a valid money-motivated bad actor scenario.',
     'is_ambiguous': False},
    {'criterion': 'Money Category - Harmful impact description',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "Clearly explains the harmful impact: reinstallation costs to city authorities and service disruption. Specific to SmartCity's connected devices.",
     'is_ambiguous': False},
    {'criterion': 'Entertainment Category - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Trolling and malicious manipulation for amusement is a valid entertainment/self-amusement motivated bad actor scenario.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment Category - Harmful impact description',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Clearly describes the negative impact: waste collection services are redirected inefficiently, wasting time, fuel, and resources. Specific to the waste-bin sensor component.',
     'is_ambiguous': False},
    {'criterion': 'Action Distinctiveness',
     'max_score': 0,
     'score': -0.5,
     'reason': 'Politics and Money actions are too similar: both involve exploitation of the SmartCity infrastructure by bad actors for resource extraction (information vs. physical materials). Both describe theft/unauthorized access of system assets.',
     'is_ambiguous': False},
    {'criterion': 'Overall Specificity to Scenario',
     'max_score': 0,
     'score': 0,
     'reason': 'Politics action lacks detailed explanation of how IoT devices specifically enable surveillance or how the multi-country rollout amplifies this risk.',
     'is_ambiguous': False}],
   'final_grade': 2.25,
   'overall_reason': "Student correctly identified 3 categories with valid bad actor scenarios. Money and Entertainment categories are well-described with clear, specific harmful impacts (1 point each). Politics category shows conceptual understanding but lacks specificity to SmartCity's infrastructure (0.75 points). A 0.5-point penalty applied for similarity between Politics and Money actions—both frame bad actors exploiting SmartCity assets for personal gain without sufficient differentiation. The Politics action also needed clearer explanation of HOW the connected devices enable surveillance and which stakeholders are affected."}},
 {'openai': {'criteria_scores': [{'criterion': 'Money - Action corresponds to category and negative impact is specific to SmartCity',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses high costs and local authorities spending a lot of money, which fits the 'money' category. However, it does not clearly describe a bad actor's harmful action (e.g., price gouging, bribery, or financial fraud) but rather a general risk or consequence. The negative impact is somewhat described but lacks specificity about a bad actor's role.",
     'is_ambiguous': True},
    {'criterion': 'Self-interest - Action corresponds to category and negative impact is specific to SmartCity',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer mentions disinformation and people being harmed by false information, which fits 'self-interest' if the bad actor is manipulating data for personal gain. However, the example is vague and not clearly tied to a specific bad actor's action (e.g., a city employee falsifying data to avoid blame). The negative impact is described but not very specific to the SmartCity context.",
     'is_ambiguous': True},
    {'criterion': 'Ideas - Action corresponds to category and negative impact is specific to SmartCity',
     'max_score': 1,
     'score': 0.5,
     'reason': "The answer discusses disagreement over automated temperature/ventilation settings, which relates to 'ideas' (conflicting values or beliefs). However, it does not clearly describe a bad actor's action (e.g., someone manipulating settings to push a particular ideology or agenda). The negative impact (unfairness, discomfort) is described but not strongly linked to a deliberate harmful action.",
     'is_ambiguous': True}],
   'final_grade': 1.5,
   'overall_reason': "The student attempted to address three different categories and provided some negative impacts, but in all cases, the harmful actions were not clearly described as deliberate actions by bad actors. The answers are vague, lack specificity, and do not fully meet the rubric's requirement for clear, scenario-adapted bad actor actions. Each response earns partial credit for category relevance and some negative impact description, but none are fully correct."},
  'claude': {'criteria_scores': [],
   'final_grade': 0,
   'overall_reason': 'Parsing failed',
   'error': 'JSON parse error: Expecting \',\' delimiter: line 51 column 6 (char 3254) | Raw: ```json\n{\n  "criteria_scores": [\n    {\n      "criterion": "Category 1 (Money): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The answer mentions high c',
   'raw_output': '```json\n{\n  "criteria_scores": [\n    {\n      "criterion": "Category 1 (Money): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The answer mentions high costs but does not clearly describe a BAD ACTOR\'s harmful action. It vaguely states \'it might encourage local authorities to spend a lot of money\' without identifying a specific malicious actor or intentional harmful behavior. This reads as a general concern rather than a bad actor scenario.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 1 (Money): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The negative impact is poorly articulated and not specific to SmartCity\'s scenario. No clear stakeholder harm is described, and it fails to explain how a bad actor would exploit the financial aspect to cause damage.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 2 (Self-interest): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.3,\n      "reason": "The answer attempts to describe misuse of the camera/traffic system but conflates \'disinformation\' with false traffic violations. Self-interest typically involves personal gain; this description is unclear about the bad actor\'s motivation or benefit. The scenario is confused and poorly articulated.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 2 (Self-interest): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.35,\n      "reason": "The example about a red light violation is confusing and poorly explained. While it attempts to show harm to innocent citizens, the mechanism is vague and doesn\'t clearly demonstrate how SmartCity\'s specific IoT system could be exploited for self-interest. The connection between the bad actor and their benefit is missing.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 3 (Ideas): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.4,\n      "reason": "The answer identifies ideological disagreement about automated temperature/ventilation control, which somewhat relates to the \'ideas\' category. However, the distinction between disagreement and a bad actor deliberately exploiting this system is not clear. This reads more as a design flaw than a bad actor\'s action.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 3 (Ideas): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.35,\n      "reason": "The negative impact (discomfort and unfairness) is mentioned but not specific to SmartCity or how a bad actor would deliberately cause harm. The answer describes a potential usability problem rather than demonstrating how someone with bad intentions could exploit the system for ideological purposes.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Action differentiation (penalty check)",\n      "max_score": 0,\n      "score": -0.5,\n      "reason": "Categories 1 and 2 are too similar—both describe general misuse/costs of the system without clearly distinct harmful actions. Both lack specificity about the bad actor\'s distinct method of harm.",\n      "is_ambiguous": false\n    }\n  ],\n  "final_grade": 1.0,\n  "overall_reason": "This answer demonstrates significant weaknesses across all three required bad actor scenarios. None of the three actions are clearly described as intentional harmful acts by bad actors with specific motivations. The Money category conflates cost concerns with bad actor behavior. The Self-interest category is confusingly written with an unclear mechanism for exploitation. The Ideas category describes disagreement rather than bad actor exploitation. Additionally, the Money and Self-interest actions are too similar in their vagueness about the harmful mechanism, triggering a -0.5 penalty. Each criterion barely achieves partial credit due to lack of specificity, scenario adaptation, and clarity. A passing response would require: (1) clearly identified bad actors with explicit motivations, (2) specific'}},
 {'openai': {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (competitor hacks system for financial gain) fits the 'money' category.",
     'is_ambiguous': False},
    {'criterion': 'Money - Negative impact described and scenario-specific',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer clearly describes how hacking would harm SmartCity's reputation and finances, and is specific to the scenario.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (political rival disrupts sensors to undermine current mayor) fits the 'politics' category.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Negative impact described and scenario-specific',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer explains how disruption would lead to public dissatisfaction and is specific to SmartCity's waste-bin sensors.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The action (privacy activists destroy/cover cameras) fits the 'ideas' category.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Negative impact described and scenario-specific',
     'max_score': 0.5,
     'score': 0.25,
     'reason': 'The answer mentions loss of traffic information and malfunctioning lights, but the negative impact on stakeholders is not fully developed (e.g., safety risks, increased congestion).',
     'is_ambiguous': False},
    {'criterion': 'Actions are sufficiently different',
     'max_score': 0,
     'score': 0,
     'reason': 'All three actions are distinct and correspond to different categories.',
     'is_ambiguous': False}],
   'final_grade': 2.75,
   'overall_reason': "The student correctly identified three distinct bad actor actions, each corresponding to a different category (money, politics, ideas), and described scenario-specific negative impacts. However, the negative impact for the 'ideas' category was not fully developed, resulting in a minor deduction."},
  'claude': {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "Hacking to gain market share and financial advantage clearly fits the 'money' category.",
     'is_ambiguous': False},
    {'criterion': 'Money - Harm description is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The answer clearly describes how hacking causes reputational damage, loss of contracts, and financial loss to SmartCity. Specific to the scenario.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "Disrupting sensors to manipulate elections and gain political power clearly fits the 'politics' category.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Harm description is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer explains how sensor disruption leads to overflowing bins, citizen dissatisfaction with the current council, and electoral advantage for the competitor. Specific to SmartCity's waste management system.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "Privacy ideology-driven destruction of cameras clearly fits the 'ideas' category as it's motivated by ideological principles rather than financial or political gain.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Harm description is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer describes concrete harms: loss of traffic information for road users and traffic light malfunction. Properly adapted to SmartCity's traffic management system.",
     'is_ambiguous': False},
    {'criterion': 'Action differentiation - No excessive similarity',
     'max_score': 0,
     'score': 0,
     'reason': 'The three actions target different systems (centralized control system, waste sensors, traffic cameras) with different motivations (money, politics, ideas). No penalization needed.',
     'is_ambiguous': False},
    {'criterion': 'Negative impact sufficiency',
     'max_score': 0,
     'score': 0,
     'reason': 'All three negative impacts are sufficiently described with clear stakeholder effects. No penalization needed.',
     'is_ambiguous': False}],
   'final_grade': 3.0,
   'overall_reason': 'Excellent response. The student selected three distinct categories (Money, Politics, Ideas) and provided well-developed bad actor scenarios for each. All actions clearly map to their respective categories, and the harmful impacts are specific to the SmartCity scenario with concrete examples of stakeholder damage. The three actions target different system components and are sufficiently differentiated. No penalizations apply. Full marks awarded.'}},
 {'openai': {'criteria_scores': [{'criterion': 'Politics - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The action describes intelligence agencies using the system for surveillance, which fits the politics category.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Negative impact is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'The answer explains that privacy and security of countries and their populations would be compromised, which is specific to the SmartCity scenario.',
     'is_ambiguous': False},
    {'criterion': 'Money - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Describes theft of valuable IoT equipment for resale, which is a money-motivated action.',
     'is_ambiguous': False},
    {'criterion': 'Money - Negative impact is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'States that theft would result in financial loss due to the need to reinstall equipment, which is specific to the scenario.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Describes trolling (pranking) waste collection services, which fits the entertainment category.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Negative impact is specific and clear',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Explains that manipulation would cause waste collectors to be redirected unnecessarily, which is a clear and scenario-specific negative impact.',
     'is_ambiguous': False}],
   'final_grade': 3,
   'overall_reason': 'All three actions are clearly distinct, correspond to the chosen categories, and the negative impacts are specific to the SmartCity scenario and well described. No penalizations apply.'},
  'claude': {'criteria_scores': [{'criterion': 'Politics Category - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Intelligence agencies conducting surveillance is appropriately categorized under Politics (power and control). The category match is correct.',
     'is_ambiguous': False},
    {'criterion': 'Politics Category - Harmful impact description',
     'max_score': 0.5,
     'score': 0.3,
     'reason': "The impact is vaguely stated ('no longer have privacy and security'). The answer lacks specificity about HOW SmartCity's IoT infrastructure enables this or WHICH stakeholders are affected. The connection to SmartCity's specific components (cameras, sensors, traffic monitoring) is not made explicit.",
     'is_ambiguous': False},
    {'criterion': 'Money Category - Action corresponds to category',
     'max_score': 0.5,
     'score': 0.5,
     'reason': 'Physical theft for financial gain is correctly categorized under Money. The category match is appropriate.',
     'is_ambiguous': False},
    {'criterion': 'Money Category - Harmful impact description',
     'max_score': 0.5,
     'score': 0.5,
     'reason': "The answer clearly describes the harmful impact: thieves steal sensors/cameras/routers and resell them, causing financial damage through reinstallation costs. This is specific to SmartCity's hardware infrastructure.",
     'is_ambiguous': False},
    {'criterion': 'Entertainment Category - Action corresponds to category',

In [126]:
diffs = []

for r in flat_multi:
    o = r["openai"].get("final_grade", 0)
    c = r["claude"].get("final_grade", 0)
    diffs.append(abs(o - c))

In [127]:
diffs

[0.75,
 1.5,
 0.25,
 0.7000000000000002,
 0.19999999999999996,
 0.25,
 0.5,
 0.30000000000000004,
 0.5]

In [128]:
max_diff = max(diffs) + 1e-6
mean_diff = np.mean(diffs)
max_diff, mean_diff

(1.500001, np.float64(0.55))

In [130]:
np.clip(1 - mean_diff / max_diff, 0, 1)

np.float64(0.6333335777776148)

In [131]:
float(np.clip(1 - mean_diff / max_diff, 0, 1) * 100)

63.33335777776148

In [175]:

def detect_rubric_failures(grading_runs, good_scores, edge_scores, bad_scores, cross_model_score):

    ambiguity = ambiguity_score_icc(grading_runs)
    discrimination = discrimination_score_spearman(good_scores, edge_scores, bad_scores)
    applicability = applicability_score(edge_scores, grading_runs)

    failures = []
    warnings = []
    insights = []

    # ----------------------------
    # 🚨 HARD FAILURES (rubric is broken)
    # ----------------------------

    if ambiguity < 75:
        failures.append({
            "type": "ambiguity",
            "message": "Low inter-rater agreement (ICC).",
            "score": ambiguity
        })

    if discrimination < 70:
        failures.append({
            "type": "discrimination",
            "message": "Rubric cannot distinguish good vs bad answers.",
            "score": discrimination
        })

    if applicability < 60:
        failures.append({
            "type": "applicability",
            "message": "Rubric fails on edge cases (too rigid or incomplete).",
            "score": applicability
        })

    if cross_model_score < 50:
        failures.append({
            "type": "cross_model",
            "message": "Severe disagreement between models → rubric highly ambiguous.",
            "score": cross_model_score
        })

    # ----------------------------
    # ⚠️ WARNINGS (subtle weaknesses)
    # ----------------------------

    # 1. Score saturation (important!)
    if ambiguity > 90 and np.std(good_scores) < 0.1:
        warnings.append({
            "type": "saturation",
            "message": "Top scores have near-zero variance → rubric too coarse or dataset too easy."
        })

    # 2. Cross-model disagreement (key signal)
    if 50 <= cross_model_score < 70:
        warnings.append({
            "type": "cross_model",
            "message": "Moderate disagreement between models → rubric wording ambigous."
        })

    # 3. Weak edge handling
    if 50 <= applicability < 70:
        warnings.append({
            "type": "edge_cases",
            "message": "Edge cases inconsistently graded → rubric lacks precision."
        })

    # 4. Overfitting to clear cases
    if discrimination > 90 and applicability < 70:
        warnings.append({
            "type": "overfit",
            "message": "Rubric works well for clear cases but struggles on borderline answers."
        })

    # 5. Hidden Ambiguity
    if ambiguity > 90 and cross_model_score < 70:
        warnings.append({
        "type": "hidden_ambiguity",
        "message": "High agreement within runs but disagreement across models → rubric wording unclear."
    })

     # ----------------------------
    # 🧠 INTERPRETABILITY INSIGHTS
    # ----------------------------

    if ambiguity > 90 and cross_model_score < 70:
        insights.append(
            "High agreement within model but disagreement across models → hidden ambiguity in wording."
        )

    if discrimination > 90 and np.std(good_scores) < 0.1:
        insights.append(
            "High discrimination but saturated top scores → rubric lacks granularity at high end."
        )

    if applicability < 70:
        insights.append(
            "Edge cases reveal missing rules or unclear boundaries in rubric."
        )


    return {
        "scores": {
            "ambiguity": round(ambiguity, 2),
            "discrimination": round(discrimination, 2),
            "applicability": round(applicability, 2),
            "cross_model": round(cross_model_score, 2)
        },
        "failures": failures, 
        "warnings" : warnings,
        "insights": insights
    }

In [230]:
# 10. EVALUATION
evaluation = detect_rubric_failures(
        openai_runs,
        good_scores,
        edge_scores,
        bad_scores,
        cross_model_score
    )

In [231]:
evaluation

{'scores': {'ambiguity': 98.86,
  'discrimination': 91.95,
  'applicability': 12.24,
  'cross_model': 63.33},
 'failures': [{'type': 'applicability',
   'message': 'Rubric fails on edge cases (too rigid or incomplete).',
   'score': 12.237324379976467}],
 'warnings': [{'type': 'cross_model',
   'message': 'Moderate disagreement between models → rubric wording ambigous.'},
  {'type': 'overfit',
   'message': 'Rubric works well for clear cases but struggles on borderline answers.'},
  {'type': 'hidden_ambiguity',
   'message': 'High agreement within runs but disagreement across models → rubric wording unclear.'}],
 'insights': ['High agreement within model but disagreement across models → hidden ambiguity in wording.',
  'Edge cases reveal missing rules or unclear boundaries in rubric.']}

In [177]:
evaluation

{'scores': {'ambiguity': 98.86,
  'discrimination': 96.9,
  'applicability': 68.08,
  'cross_model': 63.33},
 'failures': [],
 'warnings': [{'type': 'saturation',
   'message': 'Top scores have near-zero variance → rubric too coarse or dataset too easy.'},
  {'type': 'cross_model',
   'message': 'Moderate disagreement between models → rubric wording ambigous.'},
  {'type': 'edge_cases',
   'message': 'Edge cases inconsistently graded → rubric lacks precision.'},
  {'type': 'overfit',
   'message': 'Rubric works well for clear cases but struggles on borderline answers.'},
  {'type': 'hidden_ambiguity',
   'message': 'High agreement within runs but disagreement across models → rubric wording unclear.'}],
 'insights': ['High agreement within model but disagreement across models → hidden ambiguity in wording.',
  'High discrimination but saturated top scores → rubric lacks granularity at high end.',
  'Edge cases reveal missing rules or unclear boundaries in rubric.']}

## Build Prompt for Rubric Improvement

In [187]:
def build_prompt(rubric, rubric_structured, teaching, students, aggregated_summary, consistency, cross_model_score, evaluation, rubric_analysis):

    student_block = "\n\n".join(
        [f"Student {i+1}:\n{s}" for i, s in enumerate(students)]
    )

    return f"""
You are an expert exam designer.

TASK:
Improve the grading rubric using MULTIPLE sources of evidence based on the following goals.

--- INPUTS ---

RUBRIC:
{rubric}

STRUCTURED RUBRIC
{rubric_structured}

RUBRIC ANALYSIS:
{rubric_analysis}

TEACHING MATERIAL:
{teaching}

STUDENT ANSWERS:
{student_block}

AGGREGATED SUMMARY
{aggregated_summary}

CONSISTENCY SCORE
{consistency}

CROSS-MODEL-CONSISTENCY
{cross_model_score}

EVALUATION:
{evaluation}

FAILURES DETECTED:
{evaluation["failures"]}

WARNINGS:
{evaluation["warnings"]}

INSIGHTS:
{evaluation["insights"]}


--- TASK ---

Improve the rubric by:
- Reducing ambiguity (make criteria precise)
- Increasing applicability (cover more answer types)
- Improving discrimination (differentiate quality levels)

Goals:
1. Ambiguity → All the graders reach the same interpretation independently.
2. Applicability → No valid answer type is left unaddressed by the rubric.
3. Discrimination → High-quality answers score significantly better than weak ones.

INTERPRETATION GUIDELINES:

- If ambiguity is high but cross-model consistency is low:
  → criteria wording is ambiguous, not precise enough

- If applicability is low:
  → rubric is missing rules for borderline answers

- If discrimination is high but top scores have low variance:
  → rubric lacks granularity at high performance levels

- If edge cases show inconsistent scores:
  → scoring boundaries are not clearly defined

Use these signals to:
- rewrite vague criteria into measurable rules
- define clear scoring boundaries
- add examples for borderline cases

Use these signals to identify concrete weaknesses in rubric design.

OUTPUT STRICT JSON:
{{
  "improved_rubric": "...",
  "explanation": {{
    "ambiguity": "...",
    "applicability": "...",
    "discrimination": "..."
  }}
}}
"""

In [232]:
# 11. PROMPT
prompt = build_prompt(
        rubric,
        rubric_structured,
        teaching,
        students,
        aggregated_summary,   
        consistency,
        cross_model_score,
        evaluation,
        rubric_analysis
    )

In [233]:


def improve_rubric(prompt):
    out = call_llm(prompt, MODEL_GRADING, temperature= 0.4)
    return extract_json(out)

In [234]:
improved = improve_rubric(prompt)

In [235]:
improved

{'improved_rubric': {'task': {'name': 'Case study',
   'total_points': 3,
   'instructions': ['Apply the Bad Actors Modeling strategy to the SmartCity scenario.',
    'Choose 3 different categories among the five in the Bad Actors Modeling strategy (money, politics, entertainment, ideas, self-interest).',
    'For each chosen category: (a) Identify one plausible harmful action a bad actor could take (1 sentence), and (b) Explain specifically how this action could negatively impact stakeholders in the SmartCity scenario (1-2 sentences). Actions must be distinct in both actor motivation and system impact.'],
   'scenario': 'SmartCity solution as described above.'},
  'scoring': {'per_action': [{'name': 'category_match',
     'weight': 0.5,
     'rule': "The action is clearly and plausibly motivated by the chosen category, as defined in the Bad Actors Modeling teaching material. The motivation must be explicit and align with the category's definition and examples (see provided cheatsheet)."},
    {'name': 'harm_description',
     'weight': 0.5,
     'rule': 'The negative impact is specifically described, naming at least one affected stakeholder group (e.g., city residents, local authorities, company, service users) and directly referencing a SmartCity system feature. The harm must be concrete (not generic) and plausible within the scenario.'}],
   'quality_levels': [{'level': 'Excellent (1.0)',
     'criteria': ['Action is a textbook example of the category (matches definition and examples in teaching material).',
      'Negative impact is specific, detailed, and clearly linked to a SmartCity feature and stakeholder.',
      'Explanation shows clear understanding of both motivation and consequence.'],
     'example': "Money: A criminal group hacks into SmartCity's waste-bin sensors to demand ransom for restored service. This disrupts waste collection, causing health hazards for residents and extra costs for the city."},
    {'level': 'Good (0.75)',
     'criteria': ['Action fits the category but is less precise or could plausibly fit another category.',
      'Negative impact is specific to SmartCity but lacks detail (e.g., only names the system, not the stakeholder).'],
     'example': 'Politics: A political group manipulates traffic data to cause congestion during an election. This makes the city council look ineffective.'},
    {'level': 'Adequate (0.5)',
     'criteria': ['Action is plausible but only loosely fits the category, or the motivation is not clearly stated.',
      'Negative impact is generic or only partially tied to SmartCity.'],
     'example': 'Entertainment: Someone tampers with sensors for fun, causing some disruption.'},
    {'level': 'Weak (0.25)',
     'criteria': ['Action is vague or does not clearly fit the category.',
      'Negative impact is minimal, generic, or not described.'],
     'example': 'Money: Someone damages equipment. This is bad.'},
    {'level': 'Incorrect (0)',
     'criteria': ['Action does not fit the category at all, or is missing.',
      'No negative impact described.']}],
   'penalties': [{'name': 'similar_actions',
     'value': -0.5,
     'rule': 'Deduct 0.5 if two or more actions are substantially similar in both the type of action and the impact described (e.g., both are about hacking sensors to disrupt waste collection).'},
    {'name': 'missing_categories',
     'value': '-0.5 per missing or duplicate category',
     'rule': "Deduct 0.5 for each missing or duplicate category (e.g., using 'money' twice)."}],
   'coverage_rules': [{'name': 'partial_answers',
     'rule': 'If a student provides fewer than three actions, score only the actions provided using the above scale and deduct 0.5 for each missing action.'},
    {'name': 'overlap',
     'rule': 'If an action plausibly fits multiple categories, award full points if the student justifies the chosen category based on the motivation as described in the teaching material.'}],
   'borderline_guidance': ["If unsure whether an action fits a category, refer to the teaching material's definitions and examples.",
    'If the negative impact is not clearly tied to a SmartCity system feature or stakeholder, award no more than 0.5 for that action.']}},
 'explanation': {'ambiguity': 'Ambiguity is reduced by providing explicit definitions, requiring clear links to both category motivation and scenario features, and by including quality levels with examples. The rubric now specifies what constitutes a good match to a category and a sufficiently detailed harm description. Borderline guidance and explicit reference to the cheatsheet/teaching material further reduce grader subjectivity.',
  'applicability': 'Applicability is increased by adding rules for partial answers, duplicate/missing categories, and overlapping motivations. The rubric now covers cases where students provide fewer than three actions, use the same category twice, or choose ambiguous actions. Coverage rules ensure all plausible answer types are addressed.',
  'discrimination': 'Discrimination is improved by introducing a 5-level quality scale (Excellent, Good, Adequate, Weak, Incorrect) for each action, with clear criteria and examples. This allows graders to differentiate between minimal, adequate, and high-quality answers, rewarding depth, specificity, and insight. Weak or generic answers are now penalized, while excellent answers are recognized.'}}

In [236]:
print(improved["improved_rubric"])

{'task': {'name': 'Case study', 'total_points': 3, 'instructions': ['Apply the Bad Actors Modeling strategy to the SmartCity scenario.', 'Choose 3 different categories among the five in the Bad Actors Modeling strategy (money, politics, entertainment, ideas, self-interest).', 'For each chosen category: (a) Identify one plausible harmful action a bad actor could take (1 sentence), and (b) Explain specifically how this action could negatively impact stakeholders in the SmartCity scenario (1-2 sentences). Actions must be distinct in both actor motivation and system impact.'], 'scenario': 'SmartCity solution as described above.'}, 'scoring': {'per_action': [{'name': 'category_match', 'weight': 0.5, 'rule': "The action is clearly and plausibly motivated by the chosen category, as defined in the Bad Actors Modeling teaching material. The motivation must be explicit and align with the category's definition and examples (see provided cheatsheet)."}, {'name': 'harm_description', 'weight': 0.5, 'rule': 'The negative impact is specifically described, naming at least one affected stakeholder group (e.g., city residents, local authorities, company, service users) and directly referencing a SmartCity system feature. The harm must be concrete (not generic) and plausible within the scenario.'}], 'quality_levels': [{'level': 'Excellent (1.0)', 'criteria': ['Action is a textbook example of the category (matches definition and examples in teaching material).', 'Negative impact is specific, detailed, and clearly linked to a SmartCity feature and stakeholder.', 'Explanation shows clear understanding of both motivation and consequence.'], 'example': "Money: A criminal group hacks into SmartCity's waste-bin sensors to demand ransom for restored service. This disrupts waste collection, causing health hazards for residents and extra costs for the city."}, {'level': 'Good (0.75)', 'criteria': ['Action fits the category but is less precise or could plausibly fit another category.', 'Negative impact is specific to SmartCity but lacks detail (e.g., only names the system, not the stakeholder).'], 'example': 'Politics: A political group manipulates traffic data to cause congestion during an election. This makes the city council look ineffective.'}, {'level': 'Adequate (0.5)', 'criteria': ['Action is plausible but only loosely fits the category, or the motivation is not clearly stated.', 'Negative impact is generic or only partially tied to SmartCity.'], 'example': 'Entertainment: Someone tampers with sensors for fun, causing some disruption.'}, {'level': 'Weak (0.25)', 'criteria': ['Action is vague or does not clearly fit the category.', 'Negative impact is minimal, generic, or not described.'], 'example': 'Money: Someone damages equipment. This is bad.'}, {'level': 'Incorrect (0)', 'criteria': ['Action does not fit the category at all, or is missing.', 'No negative impact described.']}], 'penalties': [{'name': 'similar_actions', 'value': -0.5, 'rule': 'Deduct 0.5 if two or more actions are substantially similar in both the type of action and the impact described (e.g., both are about hacking sensors to disrupt waste collection).'}, {'name': 'missing_categories', 'value': '-0.5 per missing or duplicate category', 'rule': "Deduct 0.5 for each missing or duplicate category (e.g., using 'money' twice)."}], 'coverage_rules': [{'name': 'partial_answers', 'rule': 'If a student provides fewer than three actions, score only the actions provided using the above scale and deduct 0.5 for each missing action.'}, {'name': 'overlap', 'rule': 'If an action plausibly fits multiple categories, award full points if the student justifies the chosen category based on the motivation as described in the teaching material.'}], 'borderline_guidance': ["If unsure whether an action fits a category, refer to the teaching material's definitions and examples.", 'If the negative impact is not clearly tied to a SmartCity system feature or stakeholder, award no more than 0.5 for that action.']}}

In [237]:
improved["explanation"]

{'ambiguity': 'Ambiguity is reduced by providing explicit definitions, requiring clear links to both category motivation and scenario features, and by including quality levels with examples. The rubric now specifies what constitutes a good match to a category and a sufficiently detailed harm description. Borderline guidance and explicit reference to the cheatsheet/teaching material further reduce grader subjectivity.',
 'applicability': 'Applicability is increased by adding rules for partial answers, duplicate/missing categories, and overlapping motivations. The rubric now covers cases where students provide fewer than three actions, use the same category twice, or choose ambiguous actions. Coverage rules ensure all plausible answer types are addressed.',
 'discrimination': 'Discrimination is improved by introducing a 5-level quality scale (Excellent, Good, Adequate, Weak, Incorrect) for each action, with clear criteria and examples. This allows graders to differentiate between minimal, adequate, and high-quality answers, rewarding depth, specificity, and insight. Weak or generic answers are now penalized, while excellent answers are recognized.'}

## Test Human Review

In [194]:
import json

def human_review(result):

    print("\n=== IMPROVED RUBRIC ===\n")
    print(result["improved_rubric"])

    print("\n=== EXPLANATION ===\n")
    print(json.dumps(result["explanation"], indent=2))

    choice = input("\nApprove? (y/n): ")

    if choice.lower() == "y":
        result["human_verified"] = True
        return result

    print("\nEdit rubric:")
    result["improved_rubric"] = input("> ")

    print("\nEdit explanation JSON:")
    try:
        result["explanation"] = json.loads(input("> "))
    except:
        pass

    result["human_verified"] = True
    return result

In [204]:
human_review(improved)

=== IMPROVED RUBRIC ===

{'task': {'name': 'Case study', 'total_points': 3, 'instructions': ['Apply the Bad Actors Modeling strategy to the SmartCity scenario.', 'Select 3 different categories from: Money, Politics, Entertainment, Ideas, Self-Interest.', 'For each selected category: (a) Identify a plausible harmful action a bad actor could take, and (b) clearly explain how this action negatively impacts specific stakeholders in the SmartCity scenario (1-2 sentences per action).', 'Each action must be distinct in both method and impact.'], 'scenario': 'SmartCity solution as described above.'}, 'scoring': {'per_action': [{'name': 'category_match', 'weight': 0.5, 'rule': "The action clearly fits the chosen motivation category, as defined below. Use the category definitions and examples provided. If an action plausibly fits more than one category, the explanation must justify the chosen category based on the actor's primary motivation."}, {'name': 'harm_description', 'weight': 0.5, 'rule': 'The negative impact is described in detail, naming at least one specific stakeholder (e.g., city residents, local authorities, SmartCity company, service workers). The explanation must be directly tied to the SmartCity scenario (not generic or hypothetical) and describe a concrete consequence (e.g., loss of privacy, financial loss, service disruption, safety risk, reputational damage).'}], 'quality_levels': [{'level': 'Excellent (1.0)', 'criteria': ['Action is highly plausible, clearly fits the motivation category, and is adapted to the SmartCity context.', 'Negative impact is specific, detailed, and names at least one stakeholder and a concrete consequence.'], 'example': 'Money: A criminal group hacks the waste-bin sensors to demand ransom from the city, threatening to disrupt waste collection unless paid. This causes financial loss and service disruption for local authorities and residents.'}, {'level': 'Good (0.75)', 'criteria': ['Action fits the category and scenario, but explanation is somewhat general or lacks detail on impact or stakeholders.'], 'example': 'Entertainment: Trolls manipulate traffic cameras to cause confusion for drivers. This disrupts traffic flow but does not specify which stakeholders are harmed.'}, {'level': 'Adequate (0.5)', 'criteria': ['Action is plausible but only loosely fits the category or is generic.', 'Negative impact is mentioned but is vague or not clearly tied to SmartCity.'], 'example': 'Politics: Someone uses the system for political gain. (No detail on how or who is harmed.)'}, {'level': 'Weak (0.25)', 'criteria': ['Action is generic, unclear, or only partially fits the category.', 'Negative impact is minimal, generic, or not described.'], 'example': 'Money: The system is expensive to build. (No bad actor or harmful action described.)'}, {'level': 'Incorrect (0)', 'criteria': ['Action does not fit the category or is missing.', 'No negative impact described.'], 'example': 'Self-Interest: People like technology. (No harmful action or impact.)'}], 'penalties': [{'name': 'similar_actions', 'value': -0.5, 'rule': 'Deduct 0.5 if two or more actions are substantially similar in both method and impact (e.g., both involve hacking traffic lights for different motivations but with the same effect). Minor overlap in motivation is acceptable if the method and impact differ.'}, {'name': 'missing_category', 'value': '-0.5 per missing/extra', 'rule': 'Deduct 0.5 for each missing or extra category (if fewer or more than 3 categories are used).'}], 'borderline_guidance': ["If an action could fit multiple categories, accept it if the student justifies their choice with reference to the actor's primary motivation.", 'If a negative impact is described but not tied to a specific stakeholder, award up to 0.5 but not more.', 'If the action is plausible but not clearly adapted to SmartCity, award up to 0.5.']}, 'category_definitions': {'Money': 'Actions motivated by financial gain, theft, extortion, sabotage for profit, or competitive advantage.', 'Politics': 'Actions motivated by political advantage, influence, espionage, or undermining rivals/governments.', 'Entertainment': 'Actions done for amusement, thrill, or mischief (e.g., trolling, pranks, random attacks).', 'Self-Interest': 'Actions for personal benefit, revenge, or insider advantage (e.g., harassment, privacy invasion, insider threats).', 'Ideas': 'Actions motivated by ideology, beliefs, activism, or to promote/discredit causes (e.g., hacktivism, protest, leaking data for a cause).'}}

=== EXPLANATION ===

{
  "ambiguity": "Ambiguity is reduced by providing explicit definitions for each motivation category, detailed criteria for scoring at each quality level, and concrete examples for each score boundary. The rubric now specifies what constitutes a 'distinct' action and clarifies how to handle answers that could fit multiple categories. Penalties and borderline cases are precisely defined.",
  "applicability": "Applicability is increased by including rules for missing or extra categories, guidance for partially correct or overlapping answers, and making clear how to score generic, vague, or scenario-mismatched responses. The rubric now covers all plausible answer types, including edge cases and justifies partial credit.",
  "discrimination": "Discrimination is improved by introducing a 5-level scoring scale per action (0, 0.25, 0.5, 0.75, 1.0), with explicit criteria and examples for each. High-quality answers are rewarded for detail, specificity, and scenario adaptation, while weak or generic answers receive proportionally less credit. This increases granularity and allows for finer distinctions among student performance."
}

{'improved_rubric': {'task': {'name': 'Case study',
   'total_points': 3,
   'instructions': ['Apply the Bad Actors Modeling strategy to the SmartCity scenario.',
    'Select 3 different categories from: Money, Politics, Entertainment, Ideas, Self-Interest.',
    'For each selected category: (a) Identify a plausible harmful action a bad actor could take, and (b) clearly explain how this action negatively impacts specific stakeholders in the SmartCity scenario (1-2 sentences per action).',
    'Each action must be distinct in both method and impact.'],
   'scenario': 'SmartCity solution as described above.'},
  'scoring': {'per_action': [{'name': 'category_match',
     'weight': 0.5,
     'rule': "The action clearly fits the chosen motivation category, as defined below. Use the category definitions and examples provided. If an action plausibly fits more than one category, the explanation must justify the chosen category based on the actor's primary motivation."},
    {'name': 'harm_description',
     'weight': 0.5,
     'rule': 'The negative impact is described in detail, naming at least one specific stakeholder (e.g., city residents, local authorities, SmartCity company, service workers). The explanation must be directly tied to the SmartCity scenario (not generic or hypothetical) and describe a concrete consequence (e.g., loss of privacy, financial loss, service disruption, safety risk, reputational damage).'}],
   'quality_levels': [{'level': 'Excellent (1.0)',
     'criteria': ['Action is highly plausible, clearly fits the motivation category, and is adapted to the SmartCity context.',
      'Negative impact is specific, detailed, and names at least one stakeholder and a concrete consequence.'],
     'example': 'Money: A criminal group hacks the waste-bin sensors to demand ransom from the city, threatening to disrupt waste collection unless paid. This causes financial loss and service disruption for local authorities and residents.'},
    {'level': 'Good (0.75)',
     'criteria': ['Action fits the category and scenario, but explanation is somewhat general or lacks detail on impact or stakeholders.'],
     'example': 'Entertainment: Trolls manipulate traffic cameras to cause confusion for drivers. This disrupts traffic flow but does not specify which stakeholders are harmed.'},
    {'level': 'Adequate (0.5)',
     'criteria': ['Action is plausible but only loosely fits the category or is generic.',
      'Negative impact is mentioned but is vague or not clearly tied to SmartCity.'],
     'example': 'Politics: Someone uses the system for political gain. (No detail on how or who is harmed.)'},
    {'level': 'Weak (0.25)',
     'criteria': ['Action is generic, unclear, or only partially fits the category.',
      'Negative impact is minimal, generic, or not described.'],
     'example': 'Money: The system is expensive to build. (No bad actor or harmful action described.)'},
    {'level': 'Incorrect (0)',
     'criteria': ['Action does not fit the category or is missing.',
      'No negative impact described.'],
     'example': 'Self-Interest: People like technology. (No harmful action or impact.)'}],
   'penalties': [{'name': 'similar_actions',
     'value': -0.5,
     'rule': 'Deduct 0.5 if two or more actions are substantially similar in both method and impact (e.g., both involve hacking traffic lights for different motivations but with the same effect). Minor overlap in motivation is acceptable if the method and impact differ.'},
    {'name': 'missing_category',
     'value': '-0.5 per missing/extra',
     'rule': 'Deduct 0.5 for each missing or extra category (if fewer or more than 3 categories are used).'}],
   'borderline_guidance': ["If an action could fit multiple categories, accept it if the student justifies their choice with reference to the actor's primary motivation.",
    'If a negative impact is described but not tied to a specific stakeholder, award up to 0.5 but not more.',
    'If the action is plausible but not clearly adapted to SmartCity, award up to 0.5.']},
  'category_definitions': {'Money': 'Actions motivated by financial gain, theft, extortion, sabotage for profit, or competitive advantage.',
   'Politics': 'Actions motivated by political advantage, influence, espionage, or undermining rivals/governments.',
   'Entertainment': 'Actions done for amusement, thrill, or mischief (e.g., trolling, pranks, random attacks).',
   'Self-Interest': 'Actions for personal benefit, revenge, or insider advantage (e.g., harassment, privacy invasion, insider threats).',
   'Ideas': 'Actions motivated by ideology, beliefs, activism, or to promote/discredit causes (e.g., hacktivism, protest, leaking data for a cause).'}},
 'explanation': {'ambiguity': "Ambiguity is reduced by providing explicit definitions for each motivation category, detailed criteria for scoring at each quality level, and concrete examples for each score boundary. The rubric now specifies what constitutes a 'distinct' action and clarifies how to handle answers that could fit multiple categories. Penalties and borderline cases are precisely defined.",
  'applicability': 'Applicability is increased by including rules for missing or extra categories, guidance for partially correct or overlapping answers, and making clear how to score generic, vague, or scenario-mismatched responses. The rubric now covers all plausible answer types, including edge cases and justifies partial credit.',
  'discrimination': 'Discrimination is improved by introducing a 5-level scoring scale per action (0, 0.25, 0.5, 0.75, 1.0), with explicit criteria and examples for each. High-quality answers are rewarded for detail, specificity, and scenario adaptation, while weak or generic answers receive proportionally less credit. This increases granularity and allows for finer distinctions among student performance.'},
 'human_verified': True}

In [205]:
human_reviewed_rubric = human_review(improved)

=== IMPROVED RUBRIC ===

{'task': {'name': 'Case study', 'total_points': 3, 'instructions': ['Apply the Bad Actors Modeling strategy to the SmartCity scenario.', 'Select 3 different categories from: Money, Politics, Entertainment, Ideas, Self-Interest.', 'For each selected category: (a) Identify a plausible harmful action a bad actor could take, and (b) clearly explain how this action negatively impacts specific stakeholders in the SmartCity scenario (1-2 sentences per action).', 'Each action must be distinct in both method and impact.'], 'scenario': 'SmartCity solution as described above.'}, 'scoring': {'per_action': [{'name': 'category_match', 'weight': 0.5, 'rule': "The action clearly fits the chosen motivation category, as defined below. Use the category definitions and examples provided. If an action plausibly fits more than one category, the explanation must justify the chosen category based on the actor's primary motivation."}, {'name': 'harm_description', 'weight': 0.5, 'rule': 'The negative impact is described in detail, naming at least one specific stakeholder (e.g., city residents, local authorities, SmartCity company, service workers). The explanation must be directly tied to the SmartCity scenario (not generic or hypothetical) and describe a concrete consequence (e.g., loss of privacy, financial loss, service disruption, safety risk, reputational damage).'}], 'quality_levels': [{'level': 'Excellent (1.0)', 'criteria': ['Action is highly plausible, clearly fits the motivation category, and is adapted to the SmartCity context.', 'Negative impact is specific, detailed, and names at least one stakeholder and a concrete consequence.'], 'example': 'Money: A criminal group hacks the waste-bin sensors to demand ransom from the city, threatening to disrupt waste collection unless paid. This causes financial loss and service disruption for local authorities and residents.'}, {'level': 'Good (0.75)', 'criteria': ['Action fits the category and scenario, but explanation is somewhat general or lacks detail on impact or stakeholders.'], 'example': 'Entertainment: Trolls manipulate traffic cameras to cause confusion for drivers. This disrupts traffic flow but does not specify which stakeholders are harmed.'}, {'level': 'Adequate (0.5)', 'criteria': ['Action is plausible but only loosely fits the category or is generic.', 'Negative impact is mentioned but is vague or not clearly tied to SmartCity.'], 'example': 'Politics: Someone uses the system for political gain. (No detail on how or who is harmed.)'}, {'level': 'Weak (0.25)', 'criteria': ['Action is generic, unclear, or only partially fits the category.', 'Negative impact is minimal, generic, or not described.'], 'example': 'Money: The system is expensive to build. (No bad actor or harmful action described.)'}, {'level': 'Incorrect (0)', 'criteria': ['Action does not fit the category or is missing.', 'No negative impact described.'], 'example': 'Self-Interest: People like technology. (No harmful action or impact.)'}], 'penalties': [{'name': 'similar_actions', 'value': -0.5, 'rule': 'Deduct 0.5 if two or more actions are substantially similar in both method and impact (e.g., both involve hacking traffic lights for different motivations but with the same effect). Minor overlap in motivation is acceptable if the method and impact differ.'}, {'name': 'missing_category', 'value': '-0.5 per missing/extra', 'rule': 'Deduct 0.5 for each missing or extra category (if fewer or more than 3 categories are used).'}], 'borderline_guidance': ["If an action could fit multiple categories, accept it if the student justifies their choice with reference to the actor's primary motivation.", 'If a negative impact is described but not tied to a specific stakeholder, award up to 0.5 but not more.', 'If the action is plausible but not clearly adapted to SmartCity, award up to 0.5.']}, 'category_definitions': {'Money': 'Actions motivated by financial gain, theft, extortion, sabotage for profit, or competitive advantage.', 'Politics': 'Actions motivated by political advantage, influence, espionage, or undermining rivals/governments.', 'Entertainment': 'Actions done for amusement, thrill, or mischief (e.g., trolling, pranks, random attacks).', 'Self-Interest': 'Actions for personal benefit, revenge, or insider advantage (e.g., harassment, privacy invasion, insider threats).', 'Ideas': 'Actions motivated by ideology, beliefs, activism, or to promote/discredit causes (e.g., hacktivism, protest, leaking data for a cause).'}}

=== EXPLANATION ===

{
  "ambiguity": "Ambiguity is reduced by providing explicit definitions for each motivation category, detailed criteria for scoring at each quality level, and concrete examples for each score boundary. The rubric now specifies what constitutes a 'distinct' action and clarifies how to handle answers that could fit multiple categories. Penalties and borderline cases are precisely defined.",
  "applicability": "Applicability is increased by including rules for missing or extra categories, guidance for partially correct or overlapping answers, and making clear how to score generic, vague, or scenario-mismatched responses. The rubric now covers all plausible answer types, including edge cases and justifies partial credit.",
  "discrimination": "Discrimination is improved by introducing a 5-level scoring scale per action (0, 0.25, 0.5, 0.75, 1.0), with explicit criteria and examples for each. High-quality answers are rewarded for detail, specificity, and scenario adaptation, while weak or generic answers receive proportionally less credit. This increases granularity and allows for finer distinctions among student performance."
}

## Test Improved Rubric

#### Evaluate new rubric

In [278]:
improved

{'improved_rubric': {'task': {'name': 'Case study',
   'total_points': 3,
   'instructions': ['Apply the Bad Actors Modeling strategy to the SmartCity scenario.',
    'Choose 3 different categories among the five in the Bad Actors Modeling strategy (money, politics, entertainment, ideas, self-interest).',
    'For each chosen category: (a) Identify one plausible harmful action a bad actor could take (1 sentence), and (b) Explain specifically how this action could negatively impact stakeholders in the SmartCity scenario (1-2 sentences). Actions must be distinct in both actor motivation and system impact.'],
   'scenario': 'SmartCity solution as described above.'},
  'scoring': {'per_action': [{'name': 'category_match',
     'weight': 0.5,
     'rule': "The action is clearly and plausibly motivated by the chosen category, as defined in the Bad Actors Modeling teaching material. The motivation must be explicit and align with the category's definition and examples (see provided cheatsheet)."},
    {'name': 'harm_description',
     'weight': 0.5,
     'rule': 'The negative impact is specifically described, naming at least one affected stakeholder group (e.g., city residents, local authorities, company, service users) and directly referencing a SmartCity system feature. The harm must be concrete (not generic) and plausible within the scenario.'}],
   'quality_levels': [{'level': 'Excellent (1.0)',
     'criteria': ['Action is a textbook example of the category (matches definition and examples in teaching material).',
      'Negative impact is specific, detailed, and clearly linked to a SmartCity feature and stakeholder.',
      'Explanation shows clear understanding of both motivation and consequence.'],
     'example': "Money: A criminal group hacks into SmartCity's waste-bin sensors to demand ransom for restored service. This disrupts waste collection, causing health hazards for residents and extra costs for the city."},
    {'level': 'Good (0.75)',
     'criteria': ['Action fits the category but is less precise or could plausibly fit another category.',
      'Negative impact is specific to SmartCity but lacks detail (e.g., only names the system, not the stakeholder).'],
     'example': 'Politics: A political group manipulates traffic data to cause congestion during an election. This makes the city council look ineffective.'},
    {'level': 'Adequate (0.5)',
     'criteria': ['Action is plausible but only loosely fits the category, or the motivation is not clearly stated.',
      'Negative impact is generic or only partially tied to SmartCity.'],
     'example': 'Entertainment: Someone tampers with sensors for fun, causing some disruption.'},
    {'level': 'Weak (0.25)',
     'criteria': ['Action is vague or does not clearly fit the category.',
      'Negative impact is minimal, generic, or not described.'],
     'example': 'Money: Someone damages equipment. This is bad.'},
    {'level': 'Incorrect (0)',
     'criteria': ['Action does not fit the category at all, or is missing.',
      'No negative impact described.']}],
   'penalties': [{'name': 'similar_actions',
     'value': -0.5,
     'rule': 'Deduct 0.5 if two or more actions are substantially similar in both the type of action and the impact described (e.g., both are about hacking sensors to disrupt waste collection).'},
    {'name': 'missing_categories',
     'value': '-0.5 per missing or duplicate category',
     'rule': "Deduct 0.5 for each missing or duplicate category (e.g., using 'money' twice)."}],
   'coverage_rules': [{'name': 'partial_answers',
     'rule': 'If a student provides fewer than three actions, score only the actions provided using the above scale and deduct 0.5 for each missing action.'},
    {'name': 'overlap',
     'rule': 'If an action plausibly fits multiple categories, award full points if the student justifies the chosen category based on the motivation as described in the teaching material.'}],
   'borderline_guidance': ["If unsure whether an action fits a category, refer to the teaching material's definitions and examples.",
    'If the negative impact is not clearly tied to a SmartCity system feature or stakeholder, award no more than 0.5 for that action.']}},
 'explanation': {'ambiguity': 'Ambiguity is reduced by providing explicit definitions, requiring clear links to both category motivation and scenario features, and by including quality levels with examples. The rubric now specifies what constitutes a good match to a category and a sufficiently detailed harm description. Borderline guidance and explicit reference to the cheatsheet/teaching material further reduce grader subjectivity.',
  'applicability': 'Applicability is increased by adding rules for partial answers, duplicate/missing categories, and overlapping motivations. The rubric now covers cases where students provide fewer than three actions, use the same category twice, or choose ambiguous actions. Coverage rules ensure all plausible answer types are addressed.',
  'discrimination': 'Discrimination is improved by introducing a 5-level quality scale (Excellent, Good, Adequate, Weak, Incorrect) for each action, with clear criteria and examples. This allows graders to differentiate between minimal, adequate, and high-quality answers, rewarding depth, specificity, and insight. Weak or generic answers are now penalized, while excellent answers are recognized.'}}

In [287]:
improved_rubric = improved["improved_rubric"]

In [288]:
print(improved_rubric)

{'task': {'name': 'Case study', 'total_points': 3, 'instructions': ['Apply the Bad Actors Modeling strategy to the SmartCity scenario.', 'Choose 3 different categories among the five in the Bad Actors Modeling strategy (money, politics, entertainment, ideas, self-interest).', 'For each chosen category: (a) Identify one plausible harmful action a bad actor could take (1 sentence), and (b) Explain specifically how this action could negatively impact stakeholders in the SmartCity scenario (1-2 sentences). Actions must be distinct in both actor motivation and system impact.'], 'scenario': 'SmartCity solution as described above.'}, 'scoring': {'per_action': [{'name': 'category_match', 'weight': 0.5, 'rule': "The action is clearly and plausibly motivated by the chosen category, as defined in the Bad Actors Modeling teaching material. The motivation must be explicit and align with the category's definition and examples (see provided cheatsheet)."}, {'name': 'harm_description', 'weight': 0.5, 'rule': 'The negative impact is specifically described, naming at least one affected stakeholder group (e.g., city residents, local authorities, company, service users) and directly referencing a SmartCity system feature. The harm must be concrete (not generic) and plausible within the scenario.'}], 'quality_levels': [{'level': 'Excellent (1.0)', 'criteria': ['Action is a textbook example of the category (matches definition and examples in teaching material).', 'Negative impact is specific, detailed, and clearly linked to a SmartCity feature and stakeholder.', 'Explanation shows clear understanding of both motivation and consequence.'], 'example': "Money: A criminal group hacks into SmartCity's waste-bin sensors to demand ransom for restored service. This disrupts waste collection, causing health hazards for residents and extra costs for the city."}, {'level': 'Good (0.75)', 'criteria': ['Action fits the category but is less precise or could plausibly fit another category.', 'Negative impact is specific to SmartCity but lacks detail (e.g., only names the system, not the stakeholder).'], 'example': 'Politics: A political group manipulates traffic data to cause congestion during an election. This makes the city council look ineffective.'}, {'level': 'Adequate (0.5)', 'criteria': ['Action is plausible but only loosely fits the category, or the motivation is not clearly stated.', 'Negative impact is generic or only partially tied to SmartCity.'], 'example': 'Entertainment: Someone tampers with sensors for fun, causing some disruption.'}, {'level': 'Weak (0.25)', 'criteria': ['Action is vague or does not clearly fit the category.', 'Negative impact is minimal, generic, or not described.'], 'example': 'Money: Someone damages equipment. This is bad.'}, {'level': 'Incorrect (0)', 'criteria': ['Action does not fit the category at all, or is missing.', 'No negative impact described.']}], 'penalties': [{'name': 'similar_actions', 'value': -0.5, 'rule': 'Deduct 0.5 if two or more actions are substantially similar in both the type of action and the impact described (e.g., both are about hacking sensors to disrupt waste collection).'}, {'name': 'missing_categories', 'value': '-0.5 per missing or duplicate category', 'rule': "Deduct 0.5 for each missing or duplicate category (e.g., using 'money' twice)."}], 'coverage_rules': [{'name': 'partial_answers', 'rule': 'If a student provides fewer than three actions, score only the actions provided using the above scale and deduct 0.5 for each missing action.'}, {'name': 'overlap', 'rule': 'If an action plausibly fits multiple categories, award full points if the student justifies the chosen category based on the motivation as described in the teaching material.'}], 'borderline_guidance': ["If unsure whether an action fits a category, refer to the teaching material's definitions and examples.", 'If the negative impact is not clearly tied to a SmartCity system feature or stakeholder, award no more than 0.5 for that action.']}}

In [267]:
def rubric_to_text(rubric):
    if isinstance(rubric, str):
        return rubric

    task = rubric.get("task", {})
    scoring = rubric.get("scoring", {})

    lines = []

    # Task
    lines.append(f"{task.get('name', 'Task')} ({task.get('total_points', 0)} points)")
    for instr in task.get("instructions", []):
        lines.append(f"- {instr}")

    # Scenario
    if task.get("scenario"):
        lines.append("\nScenario:")
        lines.append(task["scenario"])

    # Scoring
    lines.append("\nGrading rubric:")
    for rule in scoring.get("per_action", []):
        lines.append(f"- {rule.get('weight', '')}: {rule.get('rule', '')}")

    # Penalties
    if scoring.get("penalties"):
        lines.append("\nPenalties:")
        for p in scoring["penalties"]:
            lines.append(f"- {p.get('value', '')}: {p.get('rule', '')}")

    return "\n".join(lines)

In [289]:
improved_rubric_text = rubric_to_text(improved_rubric)

In [292]:
print(improved_rubric_text)

Case study (3 points)
- Apply the Bad Actors Modeling strategy to the SmartCity scenario.
- Choose 3 different categories among the five in the Bad Actors Modeling strategy (money, politics, entertainment, ideas, self-interest).
- For each chosen category: (a) Identify one plausible harmful action a bad actor could take (1 sentence), and (b) Explain specifically how this action could negatively impact stakeholders in the SmartCity scenario (1-2 sentences). Actions must be distinct in both actor motivation and system impact.

Scenario:
SmartCity solution as described above.

Grading rubric:
- 0.5: The action is clearly and plausibly motivated by the chosen category, as defined in the Bad Actors Modeling teaching material. The motivation must be explicit and align with the category's definition and examples (see provided cheatsheet).
- 0.5: The negative impact is specifically described, naming at least one affected stakeholder group (e.g., city residents, local authorities, company, service users) and directly referencing a SmartCity system feature. The harm must be concrete (not generic) and plausible within the scenario.

Penalties:
- -0.5: Deduct 0.5 if two or more actions are substantially similar in both the type of action and the impact described (e.g., both are about hacking sensors to disrupt waste collection).
- -0.5 per missing or duplicate category: Deduct 0.5 for each missing or duplicate category (e.g., using 'money' twice).

In [283]:
improved_rubric = improved_rubric_text

In [285]:
print(improved_rubric_text)

Case study (3 points)
- Apply the Bad Actors Modeling strategy to the SmartCity scenario.
- Choose 3 different categories among the five in the Bad Actors Modeling strategy (money, politics, entertainment, ideas, self-interest).
- For each chosen category: (a) Identify one plausible harmful action a bad actor could take (1 sentence), and (b) Explain specifically how this action could negatively impact stakeholders in the SmartCity scenario (1-2 sentences). Actions must be distinct in both actor motivation and system impact.

Scenario:
SmartCity solution as described above.

Grading rubric:
- 0.5: The action is clearly and plausibly motivated by the chosen category, as defined in the Bad Actors Modeling teaching material. The motivation must be explicit and align with the category's definition and examples (see provided cheatsheet).
- 0.5: The negative impact is specifically described, naming at least one affected stakeholder group (e.g., city residents, local authorities, company, service users) and directly referencing a SmartCity system feature. The harm must be concrete (not generic) and plausible within the scenario.

Penalties:
- -0.5: Deduct 0.5 if two or more actions are substantially similar in both the type of action and the impact described (e.g., both are about hacking sensors to disrupt waste collection).
- -0.5 per missing or duplicate category: Deduct 0.5 for each missing or duplicate category (e.g., using 'money' twice).

In [259]:
def build_prompt(rubric, answer):
    return f"""
Strict grader.

RUBRIC:
{rubric}

ANSWER:
{answer}

Return STRICT JSON:

{{
  "criteria_scores": [
    {{
      "criterion": "string",
      "max_score": number,
      "score": number,
      "reason": "string",
      "is_ambiguous": true
    }}
  ],
  "final_grade": number,
  "overall_reason": "string"
}}
"""

In [260]:
# 1. STRUCTURE
rubric_structured = improved_rubric

# 2. ANALYZE
rubric_analysis = analyze_rubric(improved_rubric, teaching)

# 3. SYNTHETIC
synthetic_improved = generate_synthetic_answers(teaching, improved_rubric)

# 4. RUN ALL SIMULATIONS (ASYNC)
grading_runs_improved, good_runs_improved, bad_runs_improved, edge_runs_improved = await simulate_all(improved_rubric, students, synthetic_improved)


# 5. 
openai_runs_improved = [[r["openai"] for r in run] for run in grading_runs_improved]
all_raters_improved = build_rater_runs(grading_runs_improved)

# 6. AGGREGATION
#aggregated = aggregate(openai_runs)
aggregated_improved = aggregate_multi(grading_runs_improved)
aggregated_summary_improved = summarize_runs(aggregated_improved)

# 7. CONSISTENCY
consistency = consistency_score(openai_runs_improved)

# 8. CROSS MODEL
flat_multi_improved = [r for run in grading_runs_improved for r in run]
cross_model_score_improved = cross_model_consistency(flat_multi_improved)

# 9. EXTRACT SCORES
good_scores_improved = extract_scores(good_runs_improved)
bad_scores_improved  = extract_scores(bad_runs_improved)
edge_scores_improved = extract_scores(edge_runs_improved)

# 10. EVALUATION
evaluation_improved = detect_rubric_failures(
        all_raters_improved, #openai_runs,
        good_scores_improved,
        edge_scores_improved,
        bad_scores_improved, 
        cross_model_score_improved
    )

In [261]:
evaluation_improved

{'scores': {'ambiguity': 54.15,
  'discrimination': 84.2,
  'applicability': 79.74,
  'cross_model': 22.22},
 'failures': [{'type': 'ambiguity',
   'message': 'Low inter-rater agreement (ICC).',
   'score': 54.152484683458134},
  {'type': 'cross_model',
   'message': 'Severe disagreement between models → rubric highly ambiguous.',
   'score': 22.2222481481395}],
 'warnings': [],
 'insights': []}

In [208]:
baseline_runs = grading_runs_multi

In [209]:
baseline_runs

[[{'openai': {'criteria_scores': [{'criterion': 'Politics',
      'max_score': 1,
      'score': 1,
      'reason': "The action (intelligence agencies using the system to gather information) fits the 'politics' category and the negative impact (loss of privacy and security for countries and their populations) is clearly described and specific to the SmartCity scenario.",
      'is_ambiguous': False},
     {'criterion': 'Money',
      'max_score': 1,
      'score': 1,
      'reason': "The action (robbers stealing valuable installed materials) fits the 'money' category and the negative impact (financial cost to reinstall materials) is clearly described and specific to the scenario.",
      'is_ambiguous': False},
     {'criterion': 'Entertainment',
      'max_score': 1,
      'score': 1,
      'reason': "The action (trolling waste collection services by manipulating sensors) fits the 'entertainment' category and the negative impact (waste collection services being misdirected repeatedly) is clearly described and specific to the SmartCity scenario.",
      'is_ambiguous': False}],
    'final_grade': 3,
    'overall_reason': 'All three actions are clearly linked to different categories, are distinct from each other, and the negative impacts are sufficiently described and specific to the SmartCity scenario. No penalizations apply.'},
   'claude': {'criteria_scores': [{'criterion': 'Politics Category - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Intelligence agencies using surveillance tools for information gathering is a valid political bad actor scenario.',
      'is_ambiguous': False},
     {'criterion': 'Politics Category - Harmful impact description',
      'max_score': 0.5,
      'score': 0.25,
      'reason': "The answer states privacy and security loss but lacks specificity to SmartCity's infrastructure. Does not clearly explain HOW the IoT network (waste bins, cameras, weather sensors) enables this surveillance or which specific stakeholders are impacted.",
      'is_ambiguous': False},
     {'criterion': 'Money Category - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Physical theft of valuable hardware for financial gain is a valid money-motivated bad actor scenario.',
      'is_ambiguous': False},
     {'criterion': 'Money Category - Harmful impact description',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Clearly explains the harmful impact: reinstallation costs to city authorities and service disruption. Specific to SmartCity's connected devices.",
      'is_ambiguous': False},
     {'criterion': 'Entertainment Category - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Trolling and malicious manipulation for amusement is a valid entertainment/self-amusement motivated bad actor scenario.',
      'is_ambiguous': False},
     {'criterion': 'Entertainment Category - Harmful impact description',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Clearly describes the negative impact: waste collection services are redirected inefficiently, wasting time, fuel, and resources. Specific to the waste-bin sensor component.',
      'is_ambiguous': False},
     {'criterion': 'Action Distinctiveness',
      'max_score': 0,
      'score': -0.5,
      'reason': 'Politics and Money actions are too similar: both involve exploitation of the SmartCity infrastructure by bad actors for resource extraction (information vs. physical materials). Both describe theft/unauthorized access of system assets.',
      'is_ambiguous': False},
     {'criterion': 'Overall Specificity to Scenario',
      'max_score': 0,
      'score': 0,
      'reason': 'Politics action lacks detailed explanation of how IoT devices specifically enable surveillance or how the multi-country rollout amplifies this risk.',
      'is_ambiguous': False}],
    'final_grade': 2.25,
    'overall_reason': "Student correctly identified 3 categories with valid bad actor scenarios. Money and Entertainment categories are well-described with clear, specific harmful impacts (1 point each). Politics category shows conceptual understanding but lacks specificity to SmartCity's infrastructure (0.75 points). A 0.5-point penalty applied for similarity between Politics and Money actions—both frame bad actors exploiting SmartCity assets for personal gain without sufficient differentiation. The Politics action also needed clearer explanation of HOW the connected devices enable surveillance and which stakeholders are affected."}},
  {'openai': {'criteria_scores': [{'criterion': 'Money - Action corresponds to category and negative impact is specific to SmartCity',
      'max_score': 1,
      'score': 0.5,
      'reason': "The answer discusses high costs and local authorities spending a lot of money, which fits the 'money' category. However, it does not clearly describe a bad actor's harmful action (e.g., price gouging, bribery, or financial fraud) but rather a general risk or consequence. The negative impact is somewhat described but lacks specificity about a bad actor's role.",
      'is_ambiguous': True},
     {'criterion': 'Self-interest - Action corresponds to category and negative impact is specific to SmartCity',
      'max_score': 1,
      'score': 0.5,
      'reason': "The answer mentions disinformation and people being harmed by false information, which fits 'self-interest' if the bad actor is manipulating data for personal gain. However, the example is vague and not clearly tied to a specific bad actor's action (e.g., a city employee falsifying data to avoid blame). The negative impact is described but not very specific to the SmartCity context.",
      'is_ambiguous': True},
     {'criterion': 'Ideas - Action corresponds to category and negative impact is specific to SmartCity',
      'max_score': 1,
      'score': 0.5,
      'reason': "The answer discusses disagreement over automated temperature/ventilation settings, which relates to 'ideas' (conflicting values or beliefs). However, it does not clearly describe a bad actor's action (e.g., someone manipulating settings to push a particular ideology or agenda). The negative impact (unfairness, discomfort) is described but not strongly linked to a deliberate harmful action.",
      'is_ambiguous': True}],
    'final_grade': 1.5,
    'overall_reason': "The student attempted to address three different categories and provided some negative impacts, but in all cases, the harmful actions were not clearly described as deliberate actions by bad actors. The answers are vague, lack specificity, and do not fully meet the rubric's requirement for clear, scenario-adapted bad actor actions. Each response earns partial credit for category relevance and some negative impact description, but none are fully correct."},
   'claude': {'criteria_scores': [],
    'final_grade': 0,
    'overall_reason': 'Parsing failed',
    'error': 'JSON parse error: Expecting \',\' delimiter: line 51 column 6 (char 3254) | Raw: ```json\n{\n  "criteria_scores": [\n    {\n      "criterion": "Category 1 (Money): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The answer mentions high c',
    'raw_output': '```json\n{\n  "criteria_scores": [\n    {\n      "criterion": "Category 1 (Money): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The answer mentions high costs but does not clearly describe a BAD ACTOR\'s harmful action. It vaguely states \'it might encourage local authorities to spend a lot of money\' without identifying a specific malicious actor or intentional harmful behavior. This reads as a general concern rather than a bad actor scenario.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 1 (Money): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.25,\n      "reason": "The negative impact is poorly articulated and not specific to SmartCity\'s scenario. No clear stakeholder harm is described, and it fails to explain how a bad actor would exploit the financial aspect to cause damage.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 2 (Self-interest): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.3,\n      "reason": "The answer attempts to describe misuse of the camera/traffic system but conflates \'disinformation\' with false traffic violations. Self-interest typically involves personal gain; this description is unclear about the bad actor\'s motivation or benefit. The scenario is confused and poorly articulated.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 2 (Self-interest): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.35,\n      "reason": "The example about a red light violation is confusing and poorly explained. While it attempts to show harm to innocent citizens, the mechanism is vague and doesn\'t clearly demonstrate how SmartCity\'s specific IoT system could be exploited for self-interest. The connection between the bad actor and their benefit is missing.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 3 (Ideas): Action corresponds to category",\n      "max_score": 0.5,\n      "score": 0.4,\n      "reason": "The answer identifies ideological disagreement about automated temperature/ventilation control, which somewhat relates to the \'ideas\' category. However, the distinction between disagreement and a bad actor deliberately exploiting this system is not clear. This reads more as a design flaw than a bad actor\'s action.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Category 3 (Ideas): Harmful impact specifically described",\n      "max_score": 0.5,\n      "score": 0.35,\n      "reason": "The negative impact (discomfort and unfairness) is mentioned but not specific to SmartCity or how a bad actor would deliberately cause harm. The answer describes a potential usability problem rather than demonstrating how someone with bad intentions could exploit the system for ideological purposes.",\n      "is_ambiguous": true\n    },\n    {\n      "criterion": "Action differentiation (penalty check)",\n      "max_score": 0,\n      "score": -0.5,\n      "reason": "Categories 1 and 2 are too similar—both describe general misuse/costs of the system without clearly distinct harmful actions. Both lack specificity about the bad actor\'s distinct method of harm.",\n      "is_ambiguous": false\n    }\n  ],\n  "final_grade": 1.0,\n  "overall_reason": "This answer demonstrates significant weaknesses across all three required bad actor scenarios. None of the three actions are clearly described as intentional harmful acts by bad actors with specific motivations. The Money category conflates cost concerns with bad actor behavior. The Self-interest category is confusingly written with an unclear mechanism for exploitation. The Ideas category describes disagreement rather than bad actor exploitation. Additionally, the Money and Self-interest actions are too similar in their vagueness about the harmful mechanism, triggering a -0.5 penalty. Each criterion barely achieves partial credit due to lack of specificity, scenario adaptation, and clarity. A passing response would require: (1) clearly identified bad actors with explicit motivations, (2) specific'}},
  {'openai': {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The action (competitor hacks system for financial gain) fits the 'money' category.",
      'is_ambiguous': False},
     {'criterion': 'Money - Negative impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The answer clearly describes how hacking would harm SmartCity's reputation and finances, and is specific to the scenario.",
      'is_ambiguous': False},
     {'criterion': 'Politics - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The action (political rival disrupts sensors to undermine current mayor) fits the 'politics' category.",
      'is_ambiguous': False},
     {'criterion': 'Politics - Negative impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The answer explains how disruption would lead to public dissatisfaction and is specific to SmartCity's waste-bin sensors.",
      'is_ambiguous': False},
     {'criterion': 'Ideas - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The action (privacy activists destroy/cover cameras) fits the 'ideas' category.",
      'is_ambiguous': False},
     {'criterion': 'Ideas - Negative impact described and scenario-specific',
      'max_score': 0.5,
      'score': 0.25,
      'reason': 'The answer mentions loss of traffic information and malfunctioning lights, but the negative impact on stakeholders is not fully developed (e.g., safety risks, increased congestion).',
      'is_ambiguous': False},
     {'criterion': 'Actions are sufficiently different',
      'max_score': 0,
      'score': 0,
      'reason': 'All three actions are distinct and correspond to different categories.',
      'is_ambiguous': False}],
    'final_grade': 2.75,
    'overall_reason': "The student correctly identified three distinct bad actor actions, each corresponding to a different category (money, politics, ideas), and described scenario-specific negative impacts. However, the negative impact for the 'ideas' category was not fully developed, resulting in a minor deduction."},
   'claude': {'criteria_scores': [{'criterion': 'Money - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Hacking to gain market share and financial advantage clearly fits the 'money' category.",
      'is_ambiguous': False},
     {'criterion': 'Money - Harm description is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The answer clearly describes how hacking causes reputational damage, loss of contracts, and financial loss to SmartCity. Specific to the scenario.',
      'is_ambiguous': False},
     {'criterion': 'Politics - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Disrupting sensors to manipulate elections and gain political power clearly fits the 'politics' category.",
      'is_ambiguous': False},
     {'criterion': 'Politics - Harm description is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The answer explains how sensor disruption leads to overflowing bins, citizen dissatisfaction with the current council, and electoral advantage for the competitor. Specific to SmartCity's waste management system.",
      'is_ambiguous': False},
     {'criterion': 'Ideas - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "Privacy ideology-driven destruction of cameras clearly fits the 'ideas' category as it's motivated by ideological principles rather than financial or political gain.",
      'is_ambiguous': False},
     {'criterion': 'Ideas - Harm description is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': "The answer describes concrete harms: loss of traffic information for road users and traffic light malfunction. Properly adapted to SmartCity's traffic management system.",
      'is_ambiguous': False},
     {'criterion': 'Action differentiation - No excessive similarity',
      'max_score': 0,
      'score': 0,
      'reason': 'The three actions target different systems (centralized control system, waste sensors, traffic cameras) with different motivations (money, politics, ideas). No penalization needed.',
      'is_ambiguous': False},
     {'criterion': 'Negative impact sufficiency',
      'max_score': 0,
      'score': 0,
      'reason': 'All three negative impacts are sufficiently described with clear stakeholder effects. No penalization needed.',
      'is_ambiguous': False}],
    'final_grade': 3.0,
    'overall_reason': 'Excellent response. The student selected three distinct categories (Money, Politics, Ideas) and provided well-developed bad actor scenarios for each. All actions clearly map to their respective categories, and the harmful impacts are specific to the SmartCity scenario with concrete examples of stakeholder damage. The three actions target different system components and are sufficiently differentiated. No penalizations apply. Full marks awarded.'}}],
 [{'openai': {'criteria_scores': [{'criterion': 'Politics - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The action describes intelligence agencies using the system for surveillance, which fits the politics category.',
      'is_ambiguous': False},
     {'criterion': 'Politics - Negative impact is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'The answer explains that privacy and security of countries and their populations would be compromised, which is specific to the SmartCity scenario.',
      'is_ambiguous': False},
     {'criterion': 'Money - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Describes theft of valuable IoT equipment for resale, which is a money-motivated action.',
      'is_ambiguous': False},
     {'criterion': 'Money - Negative impact is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'States that theft would result in financial loss due to the need to reinstall equipment, which is specific to the scenario.',
      'is_ambiguous': False},
     {'criterion': 'Entertainment - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Describes trolling (pranking) waste collection services, which fits the entertainment category.',
      'is_ambiguous': False},
     {'criterion': 'Entertainment - Negative impact is specific and clear',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Explains that manipulation would cause waste collectors to be redirected unnecessarily, which is a clear and scenario-specific negative impact.',
      'is_ambiguous': False}],
    'final_grade': 3,
    'overall_reason': 'All three actions are clearly distinct, correspond to the chosen categories, and the negative impacts are specific to the SmartCity scenario and well described. No penalizations apply.'},
   'claude': {'criteria_scores': [{'criterion': 'Politics Category - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Intelligence agencies conducting surveillance is appropriately categorized under Politics (power and control). The category match is correct.',
      'is_ambiguous': False},
     {'criterion': 'Politics Category - Harmful impact description',
      'max_score': 0.5,
      'score': 0.3,
      'reason': "The impact is vaguely stated ('no longer have privacy and security'). The answer lacks specificity about HOW SmartCity's IoT infrastructure enables this or WHICH stakeholders are affected. The connection to SmartCity's specific components (cameras, sensors, traffic monitoring) is not made explicit.",
      'is_ambiguous': False},
     {'criterion': 'Money Category - Action corresponds to category',
      'max_score': 0.5,
      'score': 0.5,
      'reason': 'Physical theft for financial gain is correctly categorized under Money. The category match is appropriate.',
      'is_ambiguous': False},
     {'criterion': 'Money Category - Harmful impact description',
      'max_score': 0.5,
      'score': 0.5,

In [ ]:
improved_runs = simulate_grading_async(improved_rubric,students )

In [90]:
improved_runs

[[{'criteria_scores': [{'criterion': 'Politics - Category Alignment',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The action (intelligence agents using SmartCity to gain information) is clearly motivated by political interests, as defined in the rubric.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The action is specific (intelligence agents using SmartCity installations in foreign countries for espionage) and plausible in the scenario.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The negative impact (loss of privacy and security for countries and their populations) is clearly described and specific to SmartCity stakeholders.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Depth & Insight',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'The answer identifies the bad actor and consequence, but does not discuss mitigation, category overlap, or consider both security and safety in depth.',
     'is_ambiguous': False},
    {'criterion': 'Money - Category Alignment',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The action (robbers stealing valuable SmartCity equipment for profit) is clearly motivated by money.',
     'is_ambiguous': False},
    {'criterion': 'Money - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The action is specific (theft of sensors, cameras, routers) and plausible in the SmartCity context.',
     'is_ambiguous': False},
    {'criterion': 'Money - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The negative impact (financial loss due to cost of reinstalling equipment) is clearly described and specific to SmartCity stakeholders.',
     'is_ambiguous': False},
    {'criterion': 'Money - Depth & Insight',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'The answer mentions the bad actor and consequence but does not demonstrate deeper insight, such as mitigation or broader impacts.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Category Alignment',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The action (bad actors manipulating sensors for amusement or disruption) fits the entertainment category.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The action (manipulating waste collection sensors to repeatedly redirect collectors) is specific and plausible.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The negative impact (waste collection inefficiency, wasted resources) is implied and specific to SmartCity services.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Depth & Insight',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'The answer identifies a stakeholder and consequence but does not discuss mitigation, category overlap, or broader context.',
     'is_ambiguous': False}],
   'final_grade': 2.4,
   'overall_reason': 'The student provided three distinct, plausible bad actor actions, each correctly aligned with the chosen categories. Each action and negative impact is clearly described and scenario-specific. However, the answers lack depth and insight (e.g., little discussion of mitigation, overlap, or broader consequences), resulting in a deduction of 0.15 per action for the Depth & Insight criterion. No penalties for similarity or over-categorization apply.'},
  {'criteria_scores': [{'criterion': 'Money - Category Alignment',
     'max_score': 0.25,
     'score': 0,
     'reason': "The response discusses the costliness of the software and local authorities spending money, but does not describe a malicious action by a bad actor motivated by money. There is no clear fit to the rubric's requirement for a bad actor's action.",
     'is_ambiguous': False},
    {'criterion': 'Money - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0,
     'reason': 'No specific action by a bad actor is described. The answer only mentions that the system is expensive and could encourage spending, but this is not a deliberate, malicious act.',
     'is_ambiguous': False},
    {'criterion': 'Money - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.1,
     'reason': "The negative impact (authorities spending a lot of money) is only partially described and is generic. It is not clearly linked to a bad actor's action.",
     'is_ambiguous': False},
    {'criterion': 'Money - Depth & Insight',
     'max_score': 0.25,
     'score': 0,
     'reason': 'No insight into bad actors, motivations, or consequences is provided. The answer is superficial.',
     'is_ambiguous': False},
    {'criterion': 'Self-interest - Category Alignment',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The answer describes people using the system for disinformation to harm others, which fits the self-interest category as defined in the rubric.',
     'is_ambiguous': False},
    {'criterion': 'Self-interest - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'The action (using the system for disinformation) is plausible, but the description is vague and not well adapted to SmartCity context. The example given is confusing and not clearly explained.',
     'is_ambiguous': False},
    {'criterion': 'Self-interest - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'The impact (innocent people getting in trouble due to disinformation) is partially described, but lacks clarity and specificity to SmartCity stakeholders.',
     'is_ambiguous': False},
    {'criterion': 'Self-interest - Depth & Insight',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'Some insight is shown by mentioning harm to innocent people, but the answer lacks depth and clarity about the bad actor, motivation, or broader consequences.',
     'is_ambiguous': False},
    {'criterion': 'Ideas - Category Alignment',
     'max_score': 0.25,
     'score': 0.1,
     'reason': "The answer discusses disagreement over system automation (ventilation/temperature), which is only loosely connected to the 'ideas' category. No bad actor or malicious motivation is described.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0,
     'reason': 'No specific action by a bad actor is described. The answer focuses on user discomfort and disagreement, not on a deliberate act.',
     'is_ambiguous': False},
    {'criterion': 'Ideas - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'The negative impact (unfairness and discomfort) is generic and not clearly linked to a malicious action or specific SmartCity stakeholders.',
     'is_ambiguous': False},
    {'criterion': 'Ideas - Depth & Insight',
     'max_score': 0.25,
     'score': 0,
     'reason': 'No depth or insight is shown; the answer is superficial and does not reference bad actors, motivations, or mitigation.',
     'is_ambiguous': False}],
   'final_grade': 0.75,
   'overall_reason': "The student did not consistently describe malicious actions by bad actors for each category. The 'money' and 'ideas' sections lack any clear bad actor or action, while the 'self-interest' section provides a plausible category fit but is vague and lacks clarity. Negative impacts are mostly generic or only partially described. There is little depth or insight throughout. The answer does not meet the standard for full marks per the rubric."},
  {'criteria_scores': [{'criterion': 'Money - Category Alignment',
     'max_score': 0.25,
     'score': 0.25,
     'reason': "The motivation is clearly financial: a competitor seeks to damage SmartCity's reputation to gain market share and contracts. This fits the 'money' category as defined.",
     'is_ambiguous': False},
    {'criterion': 'Money - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The action (hacking the centralized monitoring system to disrupt traffic and bins) is specific, plausible in SmartCity, and clearly a deliberate malicious act.',
     'is_ambiguous': False},
    {'criterion': 'Money - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.25,
     'reason': "Negative impact is clearly described: SmartCity's reputation is harmed, leading to financial loss and loss of contracts, affecting the company and its stakeholders.",
     'is_ambiguous': False},
    {'criterion': 'Money - Depth & Insight',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'Identifies the bad actor (competitor), motivation (money/market share), and consequences (reputation, financial loss). Shows understanding of stakeholder impact.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Category Alignment',
     'max_score': 0.25,
     'score': 0.25,
     'reason': "The motivation is political: a rival seeks to damage the current mayor's reputation to win the next election. This fits the 'politics' category.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'Action is specific (disturbing sensors on waste-bins), plausible in SmartCity, and clearly malicious.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.25,
     'reason': "Negative impact is clearly described: citizens are unhappy due to overflowing bins, harming the city council's reputation.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Depth & Insight',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'Identifies bad actor (political rival), motivation (election), and consequence (citizen dissatisfaction, political harm). Recognizes stakeholder impact.',
     'is_ambiguous': False},
    {'criterion': 'Ideas - Category Alignment',
     'max_score': 0.25,
     'score': 0.25,
     'reason': "Motivation is ideological: pro-privacy group opposes surveillance. This fits the 'ideas' category.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'Action is specific (destroying/covering traffic cameras), plausible in SmartCity, and clearly a deliberate act.',
     'is_ambiguous': False},
    {'criterion': 'Ideas - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'Negative impact is clearly described: users lose real-time traffic information, and traffic lights may malfunction, affecting road users.',
     'is_ambiguous': False},
    {'criterion': 'Ideas - Depth & Insight',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'Identifies bad actor (pro-privacy group), motivation (ideology), and consequences (loss of information, safety/security impact). Names stakeholders.',
     'is_ambiguous': False}],
   'final_grade': 3.0,
   'overall_reason': "Each action is clearly aligned with the chosen category, is specific and plausible in the SmartCity context, describes a direct negative impact on relevant stakeholders, and demonstrates insight into bad actors' motivations and consequences. No actions are repeated or overly similar. No rubric criteria are ambiguous in this context."}],
 [{'criteria_scores': [{'criterion': 'Politics - Category Alignment',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The action (intelligence agents using SmartCity installations to spy) is clearly motivated by political interests (state-level espionage).',
     'is_ambiguous': False},
    {'criterion': 'Politics - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0.1,
     'reason': "The action is somewhat vague ('use this tool'), lacking detail on how the intelligence agents would exploit SmartCity, but the intent of malicious surveillance is plausible.",
     'is_ambiguous': False},
    {'criterion': 'Politics - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'Negative impact is clear: loss of privacy and security for the country and its population, which are direct SmartCity stakeholders.',
     'is_ambiguous': False},
    {'criterion': 'Politics - Depth & Insight',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'Some insight is shown (identifies bad actor as intelligence agents, mentions consequences), but lacks depth (no mitigation, overlap, or detailed consequences).',
     'is_ambiguous': False},
    {'criterion': 'Money - Category Alignment',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The action (robbers stealing valuable SmartCity equipment for resale/use) is clearly motivated by financial gain.',
     'is_ambiguous': False},
    {'criterion': 'Money - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The action is specific (theft of sensors, cameras, routers) and plausible in a SmartCity context.',
     'is_ambiguous': False},
    {'criterion': 'Money - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'Negative impact is clear: financial loss to the city (cost to reinstall), disruption of SmartCity services.',
     'is_ambiguous': False},
    {'criterion': 'Money - Depth & Insight',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'Some insight (identifies robbers as bad actors, mentions cost), but lacks depth (no discussion of broader consequences, mitigation, or overlap).',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Category Alignment',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The action (manipulating sensors to prank waste collection) is motivated by entertainment (fooling others for fun).',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The action is specific (manipulating waste sensors to redirect collectors repeatedly) and plausible in a SmartCity context.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'Negative impact is clear: waste collection services are disrupted, affecting service providers and possibly residents.',
     'is_ambiguous': False},
    {'criterion': 'Entertainment - Depth & Insight',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'Some insight (identifies pranksters as bad actors, describes consequence), but lacks depth (no mention of mitigation, broader impacts, or overlap).',
     'is_ambiguous': False}],
   'final_grade': 2.5,
   'overall_reason': 'The student clearly identified three distinct categories and described plausible, scenario-specific malicious actions for each, with clear negative impacts on SmartCity stakeholders. However, the answers generally lack depth and detailed insight, especially regarding mitigation, broader consequences, or nuanced understanding of the categories. All actions are distinct, so no penalty for similarity.'},
  {'criteria_scores': [{'criterion': 'Money - Category Alignment',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'The student mentions high costs and authorities spending a lot of money, but does not clearly describe a bad actor motivated by money or a malicious action. The motivation is ambiguous.',
     'is_ambiguous': False},
    {'criterion': 'Money - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0.0,
     'reason': 'No specific bad actor or malicious action is described. The answer discusses general costs, not a deliberate harmful act.',
     'is_ambiguous': False},
    {'criterion': 'Money - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'Mentions local authorities spending money, but the negative impact is generic and not clearly linked to a bad actor’s action.',
     'is_ambiguous': False},
    {'criterion': 'Money - Depth & Insight',
     'max_score': 0.25,
     'score': 0.0,
     'reason': 'No insight into who the bad actor is, why they act, or consequences beyond generic cost. No mention of mitigation or stakeholder analysis.',
     'is_ambiguous': False},
    {'criterion': 'Self-interest - Category Alignment',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'Clearly aligns with self-interest: someone uses the system for personal gain (spreading disinformation).',
     'is_ambiguous': False},
    {'criterion': 'Self-interest - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'Mentions disinformation and harming innocent people, but the action is vague and not well-adapted to SmartCity specifics.',
     'is_ambiguous': False},
    {'criterion': 'Self-interest - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.1,
     'reason': "Negative impact (innocent people getting in trouble) is described, but it's somewhat generic and lacks clear linkage to SmartCity context.",
     'is_ambiguous': False},
    {'criterion': 'Self-interest - Depth & Insight',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'Some insight is shown (innocent people harmed), but lacks detail on the bad actor, their motivation, or broader consequences.',
     'is_ambiguous': False},
    {'criterion': 'Ideas - Category Alignment',
     'max_score': 0.25,
     'score': 0.1,
     'reason': "Mentions disagreement over automation, which could fit 'ideas,' but the motivation and link to a bad actor are weak and not clearly justified.",
     'is_ambiguous': False},
    {'criterion': 'Ideas - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0.0,
     'reason': 'No malicious action by a bad actor is described; only mentions discomfort and disagreement about system settings.',
     'is_ambiguous': False},
    {'criterion': 'Ideas - Scenario-Specific Negative Impact',
     'max_score': 0.25,
     'score': 0.1,
     'reason': 'Describes potential unfairness or dissatisfaction, but the impact is generic and not linked to a malicious act.',
     'is_ambiguous': False},
    {'criterion': 'Ideas - Depth & Insight',
     'max_score': 0.25,
     'score': 0.0,
     'reason': 'No depth or insight into bad actors, motivations, or consequences. No reference to security, safety, or mitigation.',
     'is_ambiguous': False}],
   'final_grade': 0.85,
   'overall_reason': "The student provides three categories, but only the self-interest example clearly describes a bad actor's motivation. The money and ideas examples lack a specific malicious action or a clear bad actor. Negative impacts are mostly generic and not well linked to deliberate harm. There is minimal insight or depth across all answers, and no scenario-specific adaptation for two of the three categories. No penalties for similarity or over-categorization were applied."},
  {'criteria_scores': [{'criterion': 'Money - Category Alignment',
     'max_score': 0.25,
     'score': 0.25,
     'reason': 'The action is clearly motivated by financial gain: a competitor attacks to gain market share and profit.',
     'is_ambiguous': False},
    {'criterion': 'Money - Action Specificity & Plausibility',
     'max_score': 0.25,
     'score': 0.25,

#### Compute metrics for both

In [91]:
baseline_eval = evaluation

In [92]:
baseline_eval

{'scores': {'ambiguity': 90.19,
  'discrimination': 18.35,
  'applicability': 44.44},
 'failures': ['Discrimination: Rubric does not separate strong and weak answers well.']}

In [93]:
improved_eval = detect_rubric_failures(improved_runs)

In [94]:
improved_eval

{'scores': {'ambiguity': 82.87,
  'discrimination': 23.15,
  'applicability': 55.56},
 'failures': ['Discrimination: Rubric does not separate strong and weak answers well.']}

In [96]:
def compare(baseline, improved):
    return {
        "ambiguity_improvement": improved["scores"]["ambiguity"] - baseline["scores"]["ambiguity"],
        "discrimination_improvement": improved["scores"]["discrimination"] - baseline["scores"]["discrimination"],
        "applicability_improvement": improved["scores"]["applicability"] - baseline["scores"]["applicability"]
    }

In [97]:
compare(baseline_eval, improved_eval)

{'ambiguity_improvement': -7.319999999999993,
 'discrimination_improvement': 4.799999999999997,
 'applicability_improvement': 11.120000000000005}